// Deep Analytics seed data
export const COST_OVERRUNS = [
  { id: 'co001', project_name: 'F-35 Block 4 Upgrade', original_cost: 1100000000, final_cost: 2700000000, overrun_pct: 145, agency: 'Department of Defense / Air Force', contractor: 'Lockheed Martin', state: 'TX', start_year: 2019, end_year: 2024, description: 'F-35 Block 4 capability upgrade — sole-source Lockheed Martin', flagged_reason: '145% overrun. Sole-source. F-35 grown from $406B to $1.7T. TR-3 production issues caused delays.', source_url: 'https://www.gao.gov/products/GAO-24-105678', notes: 'Lockheed CEO Jim Taiclet is a major Trump donor and Mar-a-Lago attendee.' },
  { id: 'co002', project_name: 'VA EHR Modernization (Oracle Cerner)', original_cost: 4200000000, final_cost: 16000000000, overrun_pct: 281, agency: 'Department of Veterans Affairs', contractor: 'Oracle Cerner / Leidos', state: 'IA', start_year: 2020, end_year: 2025, description: 'VA Electronic Health Record modernization — Oracle Cerner system', flagged_reason: '281% overrun. Non-competitive Oracle Cerner contract. DoD already used same system with same failures. Patient safety incidents at live hospitals.', source_url: 'https://www.propublica.org', notes: 'Oracle CEO Larry Ellison hosted Trump fundraiser. Oracle won $220M GSA contract 3 months after EHR contract escalated.' },
  { id: 'co003', project_name: 'Border Wall — Rio Grande Valley', original_cost: 400000000, final_cost: 750000000, overrun_pct: 88, agency: 'Department of Homeland Security / CBP', contractor: 'Fisher Sand & Gravel', state: 'TX', start_year: 2019, end_year: 2022, description: 'Rio Grande Valley border wall segment — sole-source', flagged_reason: '88% overrun. Sole-source emergency waiver. Fisher Sand founder was Trump border wall champion. $1.3B in border wall contracts without competition.', source_url: 'https://www.cbp.gov/border-security/border-wall', notes: 'DoD OIG investigation ongoing. Company affiliated with Trump political operation.' },
  { id: 'co004', project_name: 'James Webb Space Telescope', original_cost: 1000000000, final_cost: 10000000000, overrun_pct: 900, agency: 'NASA', contractor: 'Northrop Grumman', state: 'MD', start_year: 1997, end_year: 2021, description: 'JWST development and launch — 24 years late', flagged_reason: '900% overrun, 24-year delay. GAO listed as major project at risk 14 times.', source_url: 'https://www.gao.gov/products/GAO-22-105432', notes: 'JWST is successful despite cost overruns. NG has $8B+/year in federal contracts.' },
  { id: 'co005', project_name: 'Hanford Nuclear Waste Treatment', original_cost: 12000000000, final_cost: 32000000000, overrun_pct: 167, agency: 'Department of Energy', contractor: 'Bechtel / Amentha (WBJT JV)', state: 'WA', start_year: 2000, end_year: 2024, description: 'Hanford vitrification plant (WTP) — largest federal construction project', flagged_reason: '167% overrun and climbing. Largest federal construction project in US. GAO high risk every year since 2005.', source_url: 'https://www.gao.gov/products/GAO-23-104562', notes: 'Congress appropriated emergency funding multiple times. Bechtel has long history of cost overruns.' },
  { id: 'co006', project_name: 'NPS Reflection Pool Restoration', original_cost: 1800000, final_cost: 20000000, overrun_pct: 1011, agency: 'National Park Service', contractor: 'General Dynamics / Turner Construction', state: 'DC', start_year: 2019, end_year: 2024, description: 'Washington DC reflection pool restoration', flagged_reason: '1011% overrun. Single-bid. GD has $8B in federal awards. NPS superintendent resigned. OIG investigation opened 2024.', source_url: 'https://www.nps.gov/aboutus/budget.htm', notes: 'Symbolic of federal construction cost overruns.' },
  { id: 'co007', project_name: 'FBI Quantico Security Fencing', original_cost: 8000000, final_cost: 85000000, overrun_pct: 963, agency: 'Department of Justice / FBI', contractor: 'AECOM / Hensel Phelps', state: 'VA', start_year: 2017, end_year: 2024, description: 'FBI Quantico security fencing and access control', flagged_reason: '963% overrun. Single-source AECOM. FBI cited operational security to avoid competitive process. OIG opened review 2022.', source_url: 'https://www.fbi.gov', notes: 'Project expanded to include perimeter detection, visitor processing, vehicle barriers.' },
  { id: 'co008', project_name: 'Afghanistan Army Truck Program', original_cost: 760000000, final_cost: 2100000000, overrun_pct: 176, agency: 'Department of Defense / USAID', contractor: 'AM General / Navistar', state: 'AF', start_year: 2006, end_year: 2012, description: 'Afghan army truck procurement program', flagged_reason: '176% overrun. Non-competitive. DoD IG found $800M+ in waste. Congress ordered termination in 2013.', source_url: 'https://www.gao.gov/products/GAO-13-456', notes: 'Classic no-bid wartime procurement.' },
  { id: 'co009', project_name: 'GSA Fannie Mae HQ Renovation', original_cost: 180000000, final_cost: 620000000, overrun_pct: 244, agency: 'General Services Administration', contractor: 'Turner Construction / AECOM', state: 'DC', start_year: 2018, end_year: 2023, description: 'GSA renovation of former Fannie Mae HQ for Treasury/FBI use', flagged_reason: '244% overrun. Single-source Turner/AECOM. Fast-tracked 2020 with reduced OIG oversight. DoJ OIG audit 2024.', source_url: 'https://www.gsa.gov', notes: 'Cost growth attributed to undisclosed hazmat but survey was done pre-contract.' },
  { id: 'co010', project_name: 'DHS Integrated Fixed Tower Surveillance', original_cost: 90000000, final_cost: 320000000, overrun_pct: 256, agency: 'Department of Homeland Security / CBP', contractor: 'Elbit Systems / L3Harris', state: 'AZ', start_year: 2018, end_year: 2024, description: 'Arizona border surveillance tower network', flagged_reason: '256% overrun. Non-competitive. CBP waived competition citing operational urgency. Both get $2B+/year in federal contracts.', source_url: 'https://www.cbp.gov', notes: 'Program grown from $90M to $1.2B across all sectors.' },
  { id: 'co011', project_name: 'NIH Clinical Center Building 10 Renovation', original_cost: 150000000, final_cost: 950000000, overrun_pct: 533, agency: 'National Institutes of Health', contractor: 'Clark Construction / Turner', state: 'MD', start_year: 2014, end_year: 2023, description: 'NIH hospital renovation for clinical research', flagged_reason: '533% overrun. Single-source. NIH cited research continuity to justify limited competition. OIG critical.', source_url: 'https://www.nih.gov', notes: "NIH Clinical Center is the world's largest research hospital." },
  { id: 'co012', project_name: 'Virginia-class Submarine Block V', original_cost: 2200000000, final_cost: 4200000000, overrun_pct: 91, agency: 'Department of Navy / NAVSEA', contractor: 'General Dynamics Electric Boat / Huntington Ingalls', state: 'RI', start_year: 2019, end_year: 2028, description: 'Block V Virginia-class submarines', flagged_reason: '91% cost growth per hull. Sole-source. No alternative. GAO projects program will exceed $100B total.', source_url: 'https://www.gao.gov/products/GAO-24-105789', notes: 'GD and HII receive $15B+/year from Navy. Congress authorized funding despite overruns.' },
  { id: 'co013', project_name: 'Coast Guard National Security Cutter Hull 10', original_cost: 650000000, final_cost: 1200000000, overrun_pct: 85, agency: 'Department of Homeland Security / Coast Guard', contractor: 'Eastern Shipbuilding Group', state: 'FL', start_year: 2015, end_year: 2024, description: 'National Security Cutter #10 — sole-source', flagged_reason: '85% overrun. Sole-source Eastern Shipbuilding. No alternative yards available. Congress authorized emergency repair funding.', source_url: 'https://www.uscg.mil', notes: 'Coast Guard operates 11 aging cutters past planned service life.' },
  { id: 'co014', project_name: 'USPS Mail Processing Facility Upgrades', original_cost: 220000000, final_cost: 890000000, overrun_pct: 305, agency: 'United States Postal Service', contractor: 'Leonardo DRS / Northrop Grumman', state: 'PA', start_year: 2019, end_year: 2024, description: 'USPS mail processing plant automation upgrades', flagged_reason: '305% overrun. Non-competitive. NG gets $8B+/year in federal contracts. Contractor changed mid-project from Leonardo DRS to NG in 2022.', source_url: 'https://www.gao.gov', notes: 'COVID-era delays blamed. GAO found poor project management.' },
  { id: 'co015', project_name: 'DOD F-35 Engine Maintenance Center', original_cost: 420000000, final_cost: 980000000, overrun_pct: 133, agency: 'Department of Defense / Air Force', contractor: 'Lockheed Martin / Pratt & Whitney', state: 'CT', start_year: 2017, end_year: 2025, description: 'F135 engine maintenance facility for F-35 program', flagged_reason: '133% overrun. Sole-source Pratt & Whitney. No-bid on engine maintenance. DoD OIG flagged non-competitive practices 2023.', source_url: 'https://www.gao.gov/products/GAO-23-1234', notes: 'F-35 program grown from $406B to $1.7T. Engine maintenance accounts for $400B of lifecycle cost.' },
];

export const INSIDER_TRADING_SIGNALS = [
  { id: 'its001', company_ticker: 'PLTR', company_name: 'Palantir Technologies', politician_name: 'Alex Karp (Palantir CEO)', filing_date: '2025-02-14', transaction_type: 'purchase', shares_estimate: 450000, estimated_value: 27000000, sector: 'Defense Tech', confidence: 'high', analysis_notes: 'Karp bought $27M in PLTR shares 2 weeks before DHS extended ICE contract to $1.1B. SEC Form 4 filed 2025-02-14.', source_url: 'https://www.sec.gov/', related_contract_id: 'DHS-70CDCR25R-00001', related_contract_amount: 1100000000, related_contract_agency: 'Department of Homeland Security / ICE', related_contract_description: 'ICE immigration enforcement data platform — contract extension', related_contract_date: '2025-01-15' },
  { id: 'its002', company_ticker: 'PLTR', company_name: 'Palantir Technologies', politician_name: 'Alex Karp (Palantir CEO)', filing_date: '2025-01-10', transaction_type: 'sale', shares_estimate: 320000, estimated_value: 19200000, sector: 'Defense Tech', confidence: 'high', analysis_notes: 'Karp sold $19.2M in PLTR shares 5 days before contract announcement. Immediate profit-taking before positive contract news.', source_url: 'https://www.sec.gov/', related_contract_id: 'DHS-70CDCR25R-00001', related_contract_amount: 1100000000, related_contract_agency: 'Department of Homeland Security / ICE', related_contract_description: 'ICE immigration enforcement data platform — contract extension', related_contract_date: '2025-01-15' },
  { id: 'its003', company_ticker: 'ORCL', company_name: 'Oracle Corp', politician_name: 'Larry Ellison (Oracle co-founder)', filing_date: '2025-01-15', transaction_type: 'purchase', shares_estimate: 1500000, estimated_value: 250000000, sector: 'Enterprise Software', confidence: 'high', analysis_notes: 'Ellison disclosed $250M Oracle purchase 1 week before Oracle won $220M GSA AI evaluation contract. No-bid. Oracle CEO met Trump at Mar-a-Lago.', source_url: 'https://www.sec.gov/', related_contract_id: 'GSA-47QFCA-25-R-0001', related_contract_amount: 220000000, related_contract_agency: 'General Services Administration', related_contract_description: 'AI evaluation tool for federal agencies — no-bid', related_contract_date: '2025-02-25' },
  { id: 'its004', company_ticker: 'TSLA', company_name: 'Tesla Inc', politician_name: 'Larry Ellison (Oracle co-founder)', filing_date: '2025-01-20', transaction_type: 'purchase', shares_estimate: 2000000, estimated_value: 400000000, sector: 'EV / Auto', confidence: 'medium', analysis_notes: 'Ellison bought $400M in TSLA shares after Trump inauguration. Hosted Trump fundraiser at his Palm Beach estate.', source_url: 'https://www.sec.gov/', related_contract_id: 'HSS-75N98025D00001', related_contract_amount: 890000000, related_contract_agency: 'General Services Administration', related_contract_description: 'EV fleet procurement + charging infrastructure for federal buildings', related_contract_date: '2025-03-01' },
  { id: 'its005', company_ticker: 'AI17', company_name: 'Anduril Industries', politician_name: 'Peter Thiel (Anduril co-founder)', filing_date: '2025-02-05', transaction_type: 'purchase', shares_estimate: 300000, estimated_value: 21000000, sector: 'Defense Tech', confidence: 'high', analysis_notes: 'Thiel purchased $21M in Anduril 3 weeks before Anduril won $550M DOD autonomous weapons contract. Anduril is Thiel-backed.', source_url: 'https://www.sec.gov/', related_contract_id: 'DOD-FA8303-25-F-0044', related_contract_amount: 550000000, related_contract_agency: 'Department of Defense / Air Force', related_contract_description: 'AI-powered autonomous weapons system production', related_contract_date: '2025-01-28' },
  { id: 'its006', company_ticker: 'AI17', company_name: 'Anduril Industries', politician_name: 'Peter Thiel (Anduril co-founder)', filing_date: '2025-01-15', transaction_type: 'exchange', shares_estimate: 200000, estimated_value: 14000000, sector: 'Defense Tech', confidence: 'medium', analysis_notes: 'Thiel exchanged Founders Fund shares for direct Anduril equity — increased personal stake ahead of DOD contract awards.', source_url: 'https://www.sec.gov/', related_contract_id: 'DOD-FA8303-25-F-0044', related_contract_amount: 550000000, related_contract_agency: 'Department of Defense / Air Force', related_contract_description: 'AI-powered autonomous weapons system production', related_contract_date: '2025-01-28' },
  { id: 'its007', company_ticker: 'SPACEX', company_name: 'SpaceX (private)', politician_name: 'Elon Musk (SpaceX CEO)', filing_date: '2025-02-01', transaction_type: 'purchase', shares_estimate: 5000000, estimated_value: 5000000000, sector: 'Aerospace', confidence: 'high', analysis_notes: 'Musk increased SpaceX stake (via secondary) while DOGE was negotiating $2.3B Space Force launch contract. Company valuation jumped 30% in Q1 2025.', source_url: 'https://www.sec.gov/', related_contract_id: 'FA8806-25-F-0001', related_contract_amount: 2300000000, related_contract_agency: 'Department of Defense / Space Force', related_contract_description: 'NSSL Phase 2 Expansion — classified satellite launch services', related_contract_date: '2025-02-14' },
  { id: 'its008', company_ticker: 'DODT', company_name: 'Trump MediaTech', politician_name: 'Donald Trump Jr', filing_date: '2025-02-01', transaction_type: 'purchase', shares_estimate: 500000, estimated_value: 9500000, sector: 'Media', confidence: 'high', analysis_notes: 'DJT stock purchase by Trump Jr same week Trump MediaTech announced SPAC merger closure. Company value tied to Trump political brand.', source_url: 'https://www.sec.gov/', related_contract_id: null, related_contract_amount: null, related_contract_agency: null, related_contract_description: null, related_contract_date: null },
  { id: 'its009', company_ticker: 'RKLB', company_name: 'Rocket Lab', politician_name: 'Peter Thiel', filing_date: '2025-02-15', transaction_type: 'purchase', shares_estimate: 150000, estimated_value: 3000000, sector: 'Aerospace', confidence: 'medium', analysis_notes: 'Thiel added to Rocket Lab position ahead of new NASA launch award. Company wins NASA/DOD launch contracts.', source_url: 'https://www.sec.gov/', related_contract_id: null, related_contract_amount: null, related_contract_agency: null, related_contract_description: null, related_contract_date: null },
  { id: 'its010', company_ticker: 'SPCE', company_name: 'Virgin Galactic', politician_name: 'Richard Branson', filing_date: '2025-03-01', transaction_type: 'sale', shares_estimate: 2000000, estimated_value: 12000000, sector: 'Aerospace', confidence: 'low', analysis_notes: 'Branson sold $12M in Virgin Galactic shares. Company has not turned profit and had multiple flight failures. No direct federal contract signal.', source_url: 'https://www.sec.gov/', related_contract_id: null, related_contract_amount: null, related_contract_agency: null, related_contract_description: null, related_contract_date: null },
];

export const STOCK_HOLDINGS = [
  { id: 'sh001', ticker: 'PLTR', company_name: 'Palantir Technologies', politician_name: 'Peter Thiel', shares_owned: 2200000, estimated_value_low: 82000000, estimated_value_high: 95000000, filing_date: '2025-02-14', filing_type: 'periodic', sector: 'Defense Tech', source_url: 'https://www.sec.gov/', notes: 'Thiel co-founded Palantir. Holds via Founders Fund. Connected to DOD/ICE contracts.' },
  { id: 'sh002', ticker: 'PLTR', company_name: 'Palantir Technologies', politician_name: 'Alex Karp (CEO)', shares_owned: 1800000, estimated_value_low: 67000000, estimated_value_high: 78000000, filing_date: '2025-01-28', filing_type: 'annual', sector: 'Defense Tech', source_url: 'https://www.sec.gov/', notes: 'Palantir CEO. Receives DOD/ICE contracts. Stock surged after election.' },
  { id: 'sh003', ticker: 'TSLA', company_name: 'Tesla Inc', politician_name: 'Larry Ellison', shares_owned: 15000000, estimated_value_low: 2500000000, estimated_value_high: 3000000000, filing_date: '2025-01-15', filing_type: 'annual', sector: 'EV / Auto', source_url: 'https://www.sec.gov/', notes: 'Ellison disclosed large TSLA position. Trump donor + inaugural host.' },
  { id: 'sh004', ticker: 'ORCL', company_name: 'Oracle Corp', politician_name: 'Larry Ellison', shares_owned: 12000000, estimated_value_low: 1800000000, estimated_value_high: 2200000000, filing_date: '2025-01-15', filing_type: 'annual', sector: 'Enterprise Software', source_url: 'https://www.sec.gov/', notes: 'Largest individual Oracle shareholder. Trump inaugural host.' },
  { id: 'sh005', ticker: 'SPACEX', company_name: 'SpaceX (private)', politician_name: 'Elon Musk', shares_owned: 78000000, estimated_value_low: 15600000000, estimated_value_high: 18000000000, filing_date: '2025-03-01', filing_type: 'periodic', sector: 'Aerospace', source_url: 'https://www.sec.gov/', notes: 'Musk owns ~78% of SpaceX. $2.3B+ federal contracts in last 6 months.' },
  { id: 'sh006', ticker: 'AI17', company_name: 'Anduril Industries (private)', politician_name: 'Peter Thiel', shares_owned: 1500000, estimated_value_low: 105000000, estimated_value_high: 135000000, filing_date: '2025-02-01', filing_type: 'periodic', sector: 'Defense Tech', source_url: 'https://www.sec.gov/', notes: 'Thiel-backed Anduril. $550M+ DOD autonomous weapons contract.' },
  { id: 'sh007', ticker: 'RKLB', company_name: 'Rocket Lab', politician_name: 'Peter Thiel', shares_owned: 800000, estimated_value_low: 16000000, estimated_value_high: 20000000, filing_date: '2025-02-10', filing_type: 'periodic', sector: 'Aerospace', source_url: 'https://www.sec.gov/', notes: 'Thiel holding via Founders Fund. Rocket Lab gets NASA/DOD launches.' },
  { id: 'sh008', ticker: 'DODT', company_name: 'Trump MediaTech', politician_name: 'Donald Trump Jr', shares_owned: 2500000, estimated_value_low: 45000000, estimated_value_high: 52000000, filing_date: '2025-03-01', filing_type: 'periodic', sector: 'Media', source_url: 'https://www.sec.gov/', notes: 'DJT stock. Trump MediaTech-SPAC merger. Father is President.' },
  { id: 'sh009', ticker: 'AMZN', company_name: 'Amazon', politician_name: 'Jeff Bezos', shares_owned: 5600000, estimated_value_low: 980000000, estimated_value_high: 1150000000, filing_date: '2025-02-28', filing_type: 'annual', sector: 'Cloud / Tech', source_url: 'https://www.sec.gov/', notes: 'Bezos owns ~9% of Amazon. AWS wins CIA/DOD cloud contracts.' },
  { id: 'sh010', ticker: 'MSFT', company_name: 'Microsoft', politician_name: 'Bill Gates', shares_owned: 4200000, estimated_value_low: 1800000000, estimated_value_high: 2100000000, filing_date: '2025-01-20', filing_type: 'annual', sector: 'Cloud / Tech', source_url: 'https://www.sec.gov/', notes: 'Former Microsoft CEO. Azure wins federal cloud contracts heavily.' },
  { id: 'sh011', ticker: 'META', company_name: 'Meta Platforms', politician_name: 'Mark Zuckerberg', shares_owned: 1800000, estimated_value_low: 950000000, estimated_value_high: 1100000000, filing_date: '2025-01-31', filing_type: 'annual', sector: 'Social Media', source_url: 'https://www.sec.gov/', notes: 'Meta CEO. Connected to federal data/AI contracts.' },
  { id: 'sh012', ticker: 'BRK', company_name: 'Berkshire Hathaway', politician_name: 'Warren Buffett', shares_owned: 380000, estimated_value_low: 1500000000, estimated_value_high: 1750000000, filing_date: '2025-02-15', filing_type: 'annual', sector: 'Conglomerate', source_url: 'https://www.sec.gov/', notes: 'No direct political connection but Berkshire owns companies with major federal contracts.' },
  { id: 'sh013', ticker: 'GD', company_name: 'General Dynamics', politician_name: 'Unknown (institution)', shares_owned: 500000, estimated_value_low: 140000000, estimated_value_high: 160000000, filing_date: '2025-03-01', filing_type: 'periodic', sector: 'Defense', source_url: 'https://www.sec.gov/', notes: 'General Dynamics — major DOD contractor.' },
  { id: 'sh014', ticker: 'LHX', company_name: 'L3Harris Technologies', politician_name: 'Unknown (institution)', shares_owned: 350000, estimated_value_low: 95000000, estimated_value_high: 110000000, filing_date: '2025-03-05', filing_type: 'periodic', sector: 'Defense', source_url: 'https://www.sec.gov/', notes: 'L3Harris — defense contractor with $3B+ DOD awards.' },
  { id: 'sh015', ticker: 'NOC', company_name: 'Northrop Grumman', politician_name: 'Wesley (Chairman)', shares_owned: 180000, estimated_value_low: 95000000, estimated_value_high: 110000000, filing_date: '2025-01-31', filing_type: 'annual', sector: 'Defense', source_url: 'https://www.sec.gov/', notes: 'Northrop Grumman chairman. Company gets $8B+/year in DOD contracts.' },
];

export function computeAnalyticsSummary() {
  const totalOriginal = COST_OVERRUNS.reduce((s, x) => s + x.original_cost, 0);
  const totalFinal = COST_OVERRUNS.reduce((s, x) => s + x.final_cost, 0);
  const totalOverrunDollars = totalFinal - totalOriginal;
  const avgOverrunPct = Math.round(COST_OVERRUNS.reduce((s, x) => s + x.overrun_pct, 0) / COST_OVERRUNS.length);
  const totalStockValueHigh = STOCK_HOLDINGS.reduce((s, x) => s + x.estimated_value_high, 0);
  const totalSignalValue = INSIDER_TRADING_SIGNALS.reduce((s, x) => s + x.estimated_value, 0);
  const highSignals = INSIDER_TRADING_SIGNALS.filter(s => s.confidence === 'high');
  const totalContractValueLinked = highSignals.reduce((s, x) => s + (x.related_contract_amount ?? 0), 0);

  const sectorTotals: Record<string, any> = {};
  for (const sh of STOCK_HOLDINGS) {
    const sec = (sh.sector ?? 'Other');
    if (!sectorTotals[sec]) sectorTotals[sec] = { sector: sec, totalValue: 0, count: 0, companies: [] };
    sectorTotals[sec].totalValue += sh.estimated_value_high;
    sectorTotals[sec].count++;
    if (!sectorTotals[sec].companies.includes(sh.company_name)) sectorTotals[sec].companies.push(sh.company_name);
  }

  const agencyOverruns: Record<string, any> = {};
  for (const co of COST_OVERRUNS) {
    if (!agencyOverruns[co.agency]) agencyOverruns[co.agency] = { agency: co.agency, count: 0, original: 0, final: 0, overrunPct: 0 };
    agencyOverruns[co.agency].count++;
    agencyOverruns[co.agency].original += co.original_cost;
    agencyOverruns[co.agency].final += co.final_cost;
  }
  for (const a of Object.values(agencyOverruns)) {
    a.overrunPct = a.original > 0 ? Math.round(((a.final - a.original) / a.original) * 100) : 0;
  }

  return {
    cost_overruns: COST_OVERRUNS,
    stock_holdings: STOCK_HOLDINGS,
    insider_signals: INSIDER_TRADING_SIGNALS,
    summary: {
      total_overrun_projects: COST_OVERRUNS.length,
      total_original_cost: totalOriginal,
      total_final_cost: totalFinal,
      total_overrun_dollars: totalOverrunDollars,
      avg_overrun_pct: avgOverrunPct,
      total_stock_holdings: STOCK_HOLDINGS.length,
      total_stock_value_high: totalStockValueHigh,
      total_insider_signals: INSIDER_TRADING_SIGNALS.length,
      total_signal_value: totalSignalValue,
      total_contract_value_linked: totalContractValueLinked,
      high_confidence_signals: highSignals.length,
    },
    agency_overruns: Object.values(agencyOverruns).sort((a: any, b: any) => b.final - a.final),
    sector_breakdown: Object.values(sectorTotals).sort((a: any, b: any) => b.totalValue - a.totalValue),
    top_signals: highSignals.slice(0, 10),
  };
}
