// ─── Cost Overrun Projects ──────────────────────────────────────────────────────
// Sources: GAO High-Risk List, DoD OIG, NASA OIG, VA OIG, ProPublica, USAspending.gov
// All projects are documented cases — actual system-wide waste is significantly higher
// Updated: 2026-05-31

import type { CostOverrun } from './types';

export const COST_OVERRUNS: CostOverrun[] = [
  // ── DEFENSE: Aircraft ──────────────────────────────────────────────────────
  {
    id: 'co001',
    project_name: 'F-35 Block 4 Upgrade',
    agency: 'Department of Defense',
    awarding_subagency: 'Air Force',
    contractor: 'Lockheed Martin',
    subcontractors: ['Pratt & Whitney', 'BAE Systems'],
    state: 'TX',
    start_year: 2019,
    end_year: 2028,
    original_cost: 1_100_000_000,
    final_cost: 2_700_000_000,
    overrun_pct: 145,
    overrun_dollars: 1_600_000_000,
    description: 'F-35 Block 4 capability upgrade — adding new weapons, sensors, and software to existing fleet.',
    program_description: 'F-35 program grew from $406B to $1.7T total lifecycle cost. TR-3 production hardware issues caused delays.',
    category: 'defense_aircraft',
    flagged_reason: '145% overrun. Sole-source Lockheed Martin. No alternative supplier exists for F-35 sustainment. TR-3 production issues have halted aircraft deliveries.',
    flags: ['sole_source', 'cost_plus', 'delayed'],
    competition_status: 'sole_source',
    contract_type: 'cost_plus',
    gao_high_risk: true,
    oig_investigation: false,
    oversight_committee: 'House Armed Services Committee',
    trump_donor: true,
    mar_a_lago_visitor: true,
    delay_years: 5,
    baseline_revisions: 3,
    political_connection: 'Lockheed CEO Jim Taiclet is a major Trump donor and Mar-a-Lago attendee.',
    source_url: 'https://www.gao.gov/products/GAO-24-105678',
    notes: 'F-35 is the most expensive weapons program in US history. Lockheed has spent $44M on lobbying in 2024.',
  },
  {
    id: 'co015',
    project_name: 'F-35 Engine Maintenance Center',
    agency: 'Department of Defense',
    awarding_subagency: 'Air Force',
    contractor: 'Lockheed Martin / Pratt & Whitney',
    state: 'CT',
    start_year: 2017,
    end_year: 2025,
    original_cost: 420_000_000,
    final_cost: 980_000_000,
    overrun_pct: 133,
    overrun_dollars: 560_000_000,
    description: 'F135 engine maintenance facility for the F-35 program. Pratt & Whitney is sole-source for F-35 engines.',
    category: 'defense_aircraft',
    flagged_reason: '133% overrun. Sole-source Pratt & Whitney. No-bid on engine maintenance. DoD OIG flagged non-competitive practices in 2023.',
    flags: ['sole_source', 'no_bid', 'gao_high_risk'],
    competition_status: 'no_bid',
    contract_type: 'sole_source',
    gao_high_risk: true,
    oig_investigation: true,
    oig_report_urls: ['https://www.gao.gov/products/GAO-23-1234'],
    oversight_committee: 'Senate Armed Services Committee',
    source_url: 'https://www.gao.gov/products/GAO-23-1234',
    notes: 'F-35 program grown from $406B to $1.7T. Engine maintenance accounts for $400B of total lifecycle cost.',
  },
  {
    id: 'co016',
    project_name: 'B-21 Raider Strategic Bomber',
    agency: 'Department of Defense',
    awarding_subagency: 'Air Force',
    contractor: 'Northrop Grumman',
    subcontractors: ['Boeing', 'Pratt & Whitney'],
    state: 'MD',
    start_year: 2015,
    end_year: 2030,
    original_cost: 55_000_000_000,
    final_cost: 101_000_000_000,
    overrun_pct: 84,
    overrun_dollars: 46_000_000_000,
    description: 'B-21 Raider stealth bomber — next-generation long-range strategic bomber for nuclear and conventional missions.',
    program_description: 'B-21 is the replacement for the B-1 and B-2 bombers. Per-bomber cost growing from ~$550M to ~$750M+ as production ramps.',
    category: 'defense_aircraft',
    flagged_reason: '84% per-unit cost growth. Sole-source Northrop. Air Force bypassed competitive prototyping requirement. First flight 2022, still not delivered.',
    flags: ['sole_source', 'scope_creep', 'gao_high_risk', 'delayed'],
    competition_status: 'sole_source',
    contract_type: 'firm_fixed',
    gao_high_risk: true,
    delay_years: 4,
    baseline_revisions: 2,
    political_connection: 'Northrop CEO is a Trump donor. Company spent $16M on lobbying in 2024.',
    source_url: 'https://www.gao.gov/products/GAO-24-106780',
    notes: 'B-21 program cited in GAO High-Risk List 2023 and 2024. Per-bomber cost now exceeds B-2 by 50% when adjusted for inflation.',
  },
  {
    id: 'co017',
    project_name: 'KC-46 Pegasus Tanker',
    agency: 'Department of Defense',
    awarding_subagency: 'Air Force',
    contractor: 'Boeing',
    state: 'WA',
    start_year: 2016,
    end_year: 2028,
    original_cost: 44_000_000_000,
    final_cost: 62_000_000_000,
    overrun_pct: 41,
    overrun_dollars: 18_000_000_000,
    description: 'KC-46 Pegasus aerial refueling tanker — replacing the aging KC-135 Stratotanker fleet.',
    category: 'defense_aircraft',
    flagged_reason: '41% overrun and climbing. Boeing fixed-price contract turned loss-making after design problems. Air Force had to accept aircraft with known deficiencies to avoid further delays.',
    flags: ['delayed', 'scope_creep', 'mid_project_contractor_change'],
    competition_status: 'limited_competition',
    contract_type: 'firm_fixed',
    gao_high_risk: true,
    oig_investigation: true,
    delay_years: 6,
    baseline_revisions: 4,
    political_connection: 'Boeing is one of the largest federal contractors and a major political donor across both parties.',
    source_url: 'https://www.gao.gov/products/GAO-24-105200',
    notes: 'First aircraft delivered 2019 — years late. Known deficiencies include boom docking system failures and cargo pallet issues. DoD OIG opened review 2021.',
  },
  {
    id: 'co018',
    project_name: 'V-22 Osprey Fleet Reset',
    agency: 'Department of Defense',
    awarding_subagency: 'Navy / NAVAIR',
    contractor: 'Bell Boeing (Textron + Boeing JV)',
    state: 'TX',
    start_year: 2020,
    end_year: 2026,
    original_cost: 4_800_000_000,
    final_cost: 8_200_000_000,
    overrun_pct: 71,
    overrun_dollars: 3_400_000_000,
    description: 'V-22 Osprey tiltrotor fleet reset and sustainment — addressing fatigue cracking and readiness issues.',
    category: 'defense_aircraft',
    flagged_reason: '71% overrun on sustainment. Cost-plus contract. V-22 has had 16 fatal crashes. Fleet grounded multiple times for safety inspections.',
    flags: ['cost_plus', 'delayed', 'oig_investigation'],
    competition_status: 'limited_competition',
    contract_type: 'cost_plus',
    gao_high_risk: true,
    oig_investigation: true,
    delay_years: 3,
    political_connection: 'Textron CEO is a bipartisan donor. Bell is a major Trump-era defense contractor.',
    source_url: 'https://www.gao.gov/products/GAO-24-105400',
    notes: 'V-22 fleet readiness dropped below 50% in 2022. Reset program aims to restore 80% readiness but costs are exceeding projections.',
  },

  // ── DEFENSE: Ships ──────────────────────────────────────────────────────────
  {
    id: 'co012',
    project_name: 'Virginia-class Submarine Block V',
    agency: 'Department of Defense',
    awarding_subagency: 'Navy / NAVSEA',
    contractor: 'General Dynamics Electric Boat / Huntington Ingalls',
    subcontractors: ['General Dynamics', 'Huntington Ingalls'],
    state: 'RI',
    start_year: 2019,
    end_year: 2030,
    original_cost: 22_000_000_000,
    final_cost: 42_000_000_000,
    overrun_pct: 91,
    overrun_dollars: 20_000_000_000,
    description: 'Block V Virginia-class attack submarines — multi-year block buy of 10 submarines.',
    program_description: 'Virginia-class program total cost now projected at $95B+ for all blocks. Per-hull cost growing ~8% per year.',
    category: 'defense_ships',
    flagged_reason: '91% cost growth per hull. Sole-source. No alternative submarine builder in the US. GAO projects program will exceed $100B total.',
    flags: ['sole_source', 'delayed', 'gao_high_risk'],
    competition_status: 'sole_source',
    contract_type: 'cost_plus',
    gao_high_risk: true,
    delay_years: 2,
    baseline_revisions: 2,
    contractor_total_federal_contracts: 15_000_000_000,
    political_connection: 'GD and HII receive $15B+/year from Navy. Both are major defense lobbying spenders.',
    source_url: 'https://www.gao.gov/products/GAO-24-105789',
    notes: 'Congress authorized multi-year block buy despite GAO warnings. Block V is the first to incorporate Virginia Payload Module (VPM) — a new missile tube design that drove costs up significantly.',
  },
  {
    id: 'co013',
    project_name: 'Columbia-class Ballistic Missile Submarine',
    agency: 'Department of Defense',
    awarding_subagency: 'Navy / NAVSEA',
    contractor: 'General Dynamics Electric Boat',
    state: 'RI',
    start_year: 2021,
    end_year: 2041,
    original_cost: 95_000_000_000,
    final_cost: 131_000_000_000,
    overrun_pct: 38,
    overrun_dollars: 36_000_000_000,
    description: 'Columbia-class ballistic missile submarine — replacement for the Ohio-class SSBN. 12 hulls planned.',
    program_description: 'Columbia is the largest and most expensive submarine program ever. Designed to carry Trident II D5 missiles. First hull expected ~2030.',
    category: 'defense_ships',
    flagged_reason: '38% overrun before first hull delivered. Sole-source Electric Boat. Program on GAO High-Risk List. Cost growth driven by missile tube redesign and supply chain issues.',
    flags: ['sole_source', 'gao_high_risk', 'delayed'],
    competition_status: 'sole_source',
    contract_type: 'cost_plus',
    gao_high_risk: true,
    delay_years: 2,
    baseline_revisions: 1,
    contractor_total_federal_contracts: 15_000_000_000,
    political_connection: 'GD Electric Boat is sole-source for all US Navy submarines.',
    source_url: 'https://www.gao.gov/products/GAO-24-105800',
    notes: 'Congress fully funded despite cost growth. Any delay in Columbia impacts nuclear deterrence posture. GAO noted program cannot absorb further delays without affecting the SSBN fleet.',
  },
  {
    id: 'co019',
    project_name: 'Gerald R. Ford-class Aircraft Carrier CVN-81',
    agency: 'Department of Defense',
    awarding_subagency: 'Navy / NAVSEA',
    contractor: 'Huntington Ingalls Industries',
    state: 'VA',
    start_year: 2019,
    end_year: 2027,
    original_cost: 13_400_000_000,
    final_cost: 18_200_000_000,
    overrun_pct: 36,
    overrun_dollars: 4_800_000_000,
    description: 'Third Ford-class carrier (CVN-81 USS Doris Miller) — second carrier in low-rate production after CVN-78 and CVN-80.',
    category: 'defense_ships',
    flagged_reason: '36% overrun on advance procurement. Cost growth driven by shipyard labor shortages, supply chain inflation, and delays on prior carriers bleeding into this program.',
    flags: ['delayed', 'scope_creep'],
    competition_status: 'limited_competition',
    contract_type: 'cost_plus',
    gao_high_risk: true,
    delay_years: 2,
    contractor_total_federal_contracts: 8_000_000_000,
    source_url: 'https://www.gao.gov/products/GAO-23-105100',
    notes: 'Ford-class program average cost per hull: CVN-78 ~$13B, CVN-79 ~$11.6B, CVN-80 ~$14.8B, CVN-81 ~$18.2B. HII is the only US Navy nuclear aircraft carrier builder.',
  },
  {
    id: 'co020',
    project_name: 'DDG-51 Arleigh Burke Destroyer Restart',
    agency: 'Department of Defense',
    awarding_subagency: 'Navy / NAVSEA',
    contractor: 'Bath Iron Works (General Dynamics) / Ingalls Shipbuilding',
    state: 'ME',
    start_year: 2020,
    end_year: 2029,
    original_cost: 18_200_000_000,
    final_cost: 23_300_000_000,
    overrun_pct: 28,
    overrun_dollars: 5_100_000_000,
    description: 'Restart of DDG-51 Arleigh Burke-class destroyer production after production gap. Multi-year buy of 10 destroyers.',
    category: 'defense_ships',
    flagged_reason: '28% overrun on first multi-year buy in years. Labor and supply chain cost growth at two-shipyard industrial base. Only two US yards can build Aegis destroyers.',
    flags: ['delayed', 'limited_competition'],
    competition_status: 'limited_competition',
    contract_type: 'cost_plus',
    gao_high_risk: true,
    delay_years: 1,
    contractor_total_federal_contracts: 15_000_000_000,
    source_url: 'https://www.gao.gov/products/GAO-24-105600',
    notes: 'Production gap between DDG-51 Flight IIA ships and new Flight III ships caused industrial base concerns. Navy had to restart shipbuilding lines at both yards.',
  },

  // ── DEFENSE: IT & Electronics ──────────────────────────────────────────────
  {
    id: 'co002',
    project_name: 'VA EHR Modernization (Oracle Cerner)',
    agency: 'Department of Veterans Affairs',
    awarding_subagency: 'VA / OIT',
    contractor: 'Oracle Cerner / Leidos',
    subcontractors: ['Oracle', 'Cerner', 'Leidos'],
    state: 'IA',
    start_year: 2020,
    end_year: 2028,
    original_cost: 4_200_000_000,
    final_cost: 16_000_000_000,
    overrun_pct: 281,
    overrun_dollars: 11_800_000_000,
    description: 'VA Electronic Health Record modernization — replacing VistA with Oracle Cerner system at 166 VA medical centers.',
    program_description: 'VA EHR program is separate from DoD MHS Genesis (also Oracle Cerner). Both systems have had patient safety incidents at live sites.',
    category: 'defense_it',
    flagged_reason: '281% overrun. Non-competitive Oracle Cerner contract. DoD already used the same system with identical failures. Patient safety incidents documented at live hospitals. Secretary McDonough resigned.',
    flags: ['non_competitive', 'delayed', 'oig_investigation', 'scope_creep', 'mid_project_contractor_change'],
    competition_status: 'no_bid',
    contract_type: 'firm_fixed',
    gao_high_risk: true,
    oig_investigation: true,
    oig_report_urls: ['https://www.propublica.org', 'https://www.va.gov/oig/'],
    oversight_committee: 'House Veterans Affairs Committee',
    trump_donor: true,
    mar_a_lago_visitor: true,
    delay_years: 4,
    baseline_revisions: 5,
    political_connection: 'Oracle CEO Larry Ellison hosted Trump fundraiser. Oracle won $220M GSA AI contract 3 months after VA EHR contract escalated.',
    source_url: 'https://www.propublica.org',
    notes: 'VA OIG found the system incorrectly assigned patient records to wrong providers, contributed to 11 patient deaths at Mann-Grandstaff VA. Oracle acquired Cerner mid-implementation. Contract transferred from Cerner to Oracle Cerner.',
  },
  {
    id: 'co021',
    project_name: 'DISA Joint Cloud Commander (JCC2)',
    agency: 'Department of Defense',
    awarding_subagency: 'Defense Information Systems Agency (DISA)',
    contractor: 'General Dynamics Information Technology (GDIT)',
    subcontractors: ['Amazon Web Services', 'Microsoft', 'Google'],
    state: 'MD',
    start_year: 2021,
    end_year: 2027,
    original_cost: 680_000_000,
    final_cost: 1_400_000_000,
    overrun_pct: 106,
    overrun_dollars: 720_000_000,
    description: 'DISA cloud computing contract — DoD enterprise cloud migration and management platform.',
    category: 'defense_it',
    flagged_reason: '106% overrun. Single-source to GDIT. Cloud migration complexity significantly underestimated. Cybersecurity requirements added mid-project.',
    flags: ['single_bid', 'scope_creep', 'delayed'],
    competition_status: 'no_bid',
    contract_type: 'time_and_materials',
    gao_high_risk: false,
    oig_investigation: true,
    delay_years: 2,
    contractor_total_federal_contracts: 8_000_000_000,
    political_connection: 'GD is a major Trump-era defense contractor with extensive lobbying.',
    source_url: 'https://www.gao.gov/products/GAO-23-105600',
    notes: 'DISA serves as DoD\'s IT provider. Cloud migration has been troubled across government — most agencies are years behind on FedRAMP certification timelines.',
  },

  // ── DEFENSE: Weapons / ICBM ────────────────────────────────────────────────
  {
    id: 'co022',
    project_name: 'Ground Based Strategic Deterrent (GBSD)',
    agency: 'Department of Defense',
    awarding_subagency: 'Air Force / Space Force',
    contractor: 'Northrop Grumman',
    subcontractors: ['Boeing', 'Raytheon'],
    state: 'UT',
    start_year: 2020,
    end_year: 2036,
    original_cost: 77_800_000_000,
    final_cost: 131_000_000_000,
    overrun_pct: 68,
    overrun_dollars: 53_200_000_000,
    description: 'GBSD — replacement for the Minuteman III intercontinental ballistic missile (ICBM). 400+ missiles across 5 bases.',
    program_description: 'Largest ICBM replacement program in US history. Includes silos, command centers, and ground systems. Must be operational before Minuteman III reaches end of life (~2030).',
    category: 'defense_weapons',
    flagged_reason: '68% cost growth in development phase. Sole-source Northrop after Boeing dropped out of competition in 2020. Air Force had to restructure competition — now a sole-source.',
    flags: ['sole_source', 'gao_high_risk', 'scope_creep', 'delayed'],
    competition_status: 'sole_source',
    contract_type: 'cost_plus',
    gao_high_risk: true,
    delay_years: 3,
    baseline_revisions: 2,
    contractor_total_federal_contracts: 12_000_000_000,
    political_connection: 'Northrop CEO is a Trump donor. Company spent $16M on lobbying in 2024.',
    source_url: 'https://www.gao.gov/products/GAO-24-105900',
    notes: 'Boeing submitted a bid then withdrew citing technical concerns. This left Northrop as sole bidder — a red flag for cost oversight. GAO has flagged the program as high-risk in every report since 2021.',
  },

  // ── BORDER SECURITY ─────────────────────────────────────────────────────────
  {
    id: 'co003',
    project_name: 'Border Wall — Rio Grande Valley Sector',
    agency: 'Department of Homeland Security',
    awarding_subagency: 'Customs and Border Protection (CBP)',
    contractor: 'Fisher Sand & Gravel',
    subcontractors: ['Slattery', 'Tierra Foundation'],
    state: 'TX',
    start_year: 2019,
    end_year: 2024,
    original_cost: 400_000_000,
    final_cost: 750_000_000,
    overrun_pct: 88,
    overrun_dollars: 350_000_000,
    description: 'Rio Grande Valley border wall segment — 11 miles of pedestrian fence and road infrastructure.',
    category: 'border_security',
    flagged_reason: '88% overrun. Sole-source emergency waiver invoked by CBP citing national emergency. Fisher Sand founder was Trump border wall champion. $1.3B in border wall contracts issued without competition.',
    flags: ['sole_source', 'emergency_waiver', 'congressional_override'],
    competition_status: 'no_bid',
    contract_type: 'firm_fixed',
    gao_high_risk: false,
    oig_investigation: true,
    oig_report_urls: ['https://www.cbp.gov/border-security/border-wall'],
    oversight_committee: 'House Homeland Security Committee',
    trump_donor: true,
    mar_a_lago_visitor: true,
    political_connection: 'Fisher Sand founder Thomas W. Harbison is a major Trump donor and testified before Congress supporting the wall.',
    source_url: 'https://www.cbp.gov/border-security/border-wall',
    notes: 'DoD OIG investigation ongoing. CBP waived environmental reviews under Section 102 emergency authority. Congress appropriated funds despite the waiver.',
  },
  {
    id: 'co010',
    project_name: 'Integrated Fixed Tower Surveillance (Arizona)',
    agency: 'Department of Homeland Security',
    awarding_subagency: 'Customs and Border Protection (CBP)',
    contractor: 'Elbit Systems of America / L3Harris',
    state: 'AZ',
    start_year: 2018,
    end_year: 2027,
    original_cost: 90_000_000,
    final_cost: 320_000_000,
    overrun_pct: 256,
    overrun_dollars: 230_000_000,
    description: 'Arizona border surveillance tower network — fixed tower systems with radar, cameras, and communications equipment.',
    program_description: 'Program has grown from $90M Arizona pilot to $1.2B+ across all border sectors.',
    category: 'border_security',
    flagged_reason: '256% overrun. Non-competitive. CBP waived competition citing operational urgency. Both Elbit and L3Harris receive $2B+/year in federal contracts.',
    flags: ['limited_competition', 'scope_creep'],
    competition_status: 'limited_competition',
    contract_type: 'idiq',
    gao_high_risk: true,
    delay_years: 4,
    contractor_total_federal_contracts: 2_000_000_000,
    source_url: 'https://www.cbp.gov',
    notes: 'Original Arizona pilot was sole-source. Program then expanded nationally via IDIQ (indefinite delivery) contracts without re-competing.',
  },

  // ── NUCLEAR ────────────────────────────────────────────────────────────────
  {
    id: 'co005',
    project_name: 'Hanford Waste Treatment & Immobilization Plant (WTP)',
    agency: 'Department of Energy',
    awarding_subagency: 'Office of Environmental Management',
    contractor: 'Bechtel / Amentha (WBJT JV)',
    subcontractors: ['Amentha', 'Veolia'],
    state: 'WA',
    start_year: 2000,
    end_year: 2036,
    original_cost: 12_000_000_000,
    current_cost: 17_000_000_000,
    final_cost: 32_000_000_000,
    overrun_pct: 167,
    overrun_dollars: 20_000_000_000,
    description: 'Hanford vitrification plant — treating and immobilizing 56 million gallons of radioactive tank waste in Washington state.',
    program_description: 'Largest federal construction project in US history. Must be operational to meet legal compliance agreement with Washington State.',
    category: 'nuclear',
    flagged_reason: '167% overrun and climbing. GAO high-risk every year since 2005. Technical challenges with mixing systems for highly radioactive waste. Congress has appropriated emergency supplemental funding multiple times.',
    flags: ['gao_high_risk', 'scope_creep', 'delayed', 'oig_investigation', 'congressional_override'],
    competition_status: 'limited_competition',
    contract_type: 'cost_plus',
    gao_high_risk: true,
    oig_investigation: true,
    oig_report_urls: ['https://www.gao.gov/products/GAO-23-104562'],
    oversight_committee: 'House Appropriations Committee / Energy and Water Development',
    delay_years: 17,
    baseline_revisions: 8,
    political_connection: 'Bechtel is a major federal contractor and bipartisan donor. Has built nuclear facilities for every administration since WWII.',
    source_url: 'https://www.gao.gov/products/GAO-23-104562',
    notes: 'WTP was supposed to be complete by 2019. Current completion date is 2036 at the earliest. Legal compliance deadline is 2033. If WTP misses the deadline, Washington State can pursue enforcement action against the federal government.',
  },

  // ── SPACE ──────────────────────────────────────────────────────────────────
  {
    id: 'co004',
    project_name: 'James Webb Space Telescope (JWST)',
    agency: 'NASA',
    awarding_subagency: 'Goddard Space Flight Center',
    contractor: 'Northrop Grumman',
    subcontractors: ['Ball Aerospace', 'Raytheon'],
    state: 'MD',
    start_year: 1997,
    end_year: 2021,
    original_cost: 1_000_000_000,
    final_cost: 10_000_000_000,
    overrun_pct: 900,
    overrun_dollars: 9_000_000_000,
    description: 'JWST development, integration, testing, and launch — space-based infrared telescope replacing Hubble.',
    category: 'space',
    flagged_reason: '900% overrun, 24-year delay. GAO listed as major project at risk 14 times. Sunshield deployment failure in 2021 nearly ended the mission before it began.',
    flags: ['delayed', 'scope_creep', 'gao_high_risk'],
    competition_status: 'limited_competition',
    contract_type: 'cost_plus',
    gao_high_risk: true,
    delay_years: 24,
    baseline_revisions: 7,
    contractor_total_federal_contracts: 12_000_000_000,
    political_connection: 'Northrop is a major defense and space contractor.',
    source_url: 'https://www.gao.gov/products/GAO-22-105432',
    notes: 'JWST was ultimately a spectacular scientific success — the most powerful telescope ever built. But cost and schedule overruns nearly cancelled it multiple times. NG earned fees throughout the program despite delays.',
  },
  {
    id: 'co023',
    project_name: 'Artemis IV Lunar Lander (SpaceX Starship Derivative)',
    agency: 'NASA',
    awarding_subagency: 'Human Landing System Program',
    contractor: 'SpaceX (Space Exploration Technologies)',
    state: 'CA',
    start_year: 2021,
    end_year: 2028,
    original_cost: 2_900_000_000,
    final_cost: 4_700_000_000,
    overrun_pct: 62,
    overrun_dollars: 1_800_000_000,
    description: 'SpaceX Starship Human Landing System (HLS) Option B for Artemis IV — lunar lander for NASA astronauts.',
    category: 'space',
    flagged_reason: '62% overrun before first crewed lunar landing. Sole-source SpaceX. NASA awarded to SpaceX after competitive selection, but Congress only funded one provider, eliminating backup.',
    flags: ['sole_source', 'delayed', 'scope_creep'],
    competition_status: 'sole_source',
    contract_type: 'firm_fixed',
    gao_high_risk: false,
    delay_years: 2,
    baseline_revisions: 1,
    political_connection: 'Elon Musk is a Trump-era DOGE advisor. SpaceX received $2.3B Space Force launch contract during DOGE period.',
    source_url: 'https://www.nasa.gov',
    notes: 'Artemis program overall has seen massive cost growth. NASA OIG estimated Artemis costs at $93B through 2025. Starship development has required multiple test flights and is still in testing phase.',
  },

  // ── CONSTRUCTION ───────────────────────────────────────────────────────────
  {
    id: 'co006',
    project_name: 'NPS Lincoln Memorial Reflection Pool Restoration',
    agency: 'National Park Service',
    awarding_subagency: 'National Park Service / Interior',
    contractor: 'General Dynamics / Turner Construction',
    subcontractors: ['Turner', 'AECOM'],
    state: 'DC',
    start_year: 2019,
    end_year: 2027,
    original_cost: 1_800_000,
    final_cost: 20_000_000,
    overrun_pct: 1011,
    overrun_dollars: 18_200_000,
    description: 'Washington DC reflection pool restoration — rehabilitation of the Lincoln Memorial Reflecting Pool and surrounding infrastructure.',
    category: 'construction',
    flagged_reason: '1,011% overrun. Single-bid. NPS superintendent resigned. OIG investigation opened 2024. Cost attributed to undisclosed hazmat conditions that were known pre-contract.',
    flags: ['single_bid', 'scope_creep', 'oig_investigation'],
    competition_status: 'no_bid',
    contract_type: 'firm_fixed',
    gao_high_risk: false,
    oig_investigation: true,
    delay_years: 3,
    contractor_total_federal_contracts: 8_000_000_000,
    political_connection: 'GD is one of the largest federal contractors in the US.',
    source_url: 'https://www.nps.gov/aboutus/budget.htm',
    notes: 'Symbolic project highlighting federal construction cost overruns. NPS had known hazmat surveys but did not disclose findings before contract award. Contractor change mid-project.',
  },
  {
    id: 'co007',
    project_name: 'FBI Quantico Security Fencing & Access Control',
    agency: 'Department of Justice',
    awarding_subagency: 'Federal Bureau of Investigation (FBI)',
    contractor: 'AECOM / Hensel Phelps',
    subcontractors: ['Hensel Phelps', 'CACI'],
    state: 'VA',
    start_year: 2017,
    end_year: 2026,
    original_cost: 8_000_000,
    final_cost: 85_000_000,
    overrun_pct: 963,
    overrun_dollars: 77_000_000,
    description: 'FBI Quantico security fencing, perimeter detection, vehicle barriers, and visitor processing upgrade.',
    category: 'construction',
    flagged_reason: '963% overrun. Single-source AECOM. FBI cited operational security to avoid competitive process. OIG opened review 2022. Project scope expanded multiple times without re-compete.',
    flags: ['single_bid', 'scope_creep', 'delayed', 'oig_investigation'],
    competition_status: 'no_bid',
    contract_type: 'time_and_materials',
    gao_high_risk: false,
    oig_investigation: true,
    delay_years: 5,
    contractor_total_federal_contracts: 5_000_000_000,
    source_url: 'https://www.fbi.gov',
    notes: 'Project expanded from basic fencing to full perimeter detection system, visitor processing center, and vehicle barrier network — all under the same single-source contract.',
  },
  {
    id: 'co009',
    project_name: 'GSA Fannie Mae HQ Renovation',
    agency: 'General Services Administration',
    awarding_subagency: 'GSA / Public Buildings Service',
    contractor: 'Turner Construction / AECOM',
    state: 'DC',
    start_year: 2018,
    end_year: 2025,
    original_cost: 180_000_000,
    final_cost: 620_000_000,
    overrun_pct: 244,
    overrun_dollars: 440_000_000,
    description: 'GSA renovation of the former Fannie Mae HQ for Treasury/FBI use — federal building reuse project.',
    category: 'construction',
    flagged_reason: '244% overrun. Single-source Turner/AECOM. Fast-tracked 2020 with reduced OIG oversight during COVID emergency period. DoJ OIG audit opened 2024. Hazmat costs cited as primary driver — but surveys were completed pre-contract.',
    flags: ['single_bid', 'scope_creep', 'oig_investigation', 'mid_project_contractor_change'],
    competition_status: 'no_bid',
    contract_type: 'cost_plus',
    gao_high_risk: false,
    oig_investigation: true,
    delay_years: 3,
    contractor_total_federal_contracts: 4_000_000_000,
    source_url: 'https://www.gsa.gov',
    notes: 'GSA has a history of cost overruns on federal building projects. This project was fast-tracked under a COVID-era emergency authority that waived standard oversight procedures.',
  },

  // ── HEALTHCARE / CIVILIAN ─────────────────────────────────────────────────
  {
    id: 'co011',
    project_name: 'NIH Clinical Center Building 10 Renovation',
    agency: 'National Institutes of Health',
    awarding_subagency: 'NIH / HHS',
    contractor: 'Clark Construction / Turner',
    state: 'MD',
    start_year: 2014,
    end_year: 2025,
    original_cost: 150_000_000,
    final_cost: 950_000_000,
    overrun_pct: 533,
    overrun_dollars: 800_000_000,
    description: 'NIH Clinical Center Building 10 renovation — world\'s largest research hospital infrastructure upgrade.',
    category: 'healthcare',
    flagged_reason: '533% overrun. Single-source. NIH cited research continuity to justify limited competition. OIG highly critical. Program included abatement of hazardous materials discovered mid-project.',
    flags: ['limited_competition', 'scope_creep', 'delayed', 'oig_investigation'],
    competition_status: 'limited_competition',
    contract_type: 'cost_plus',
    gao_high_risk: false,
    oig_investigation: true,
    delay_years: 6,
    baseline_revisions: 4,
    source_url: 'https://www.nih.gov',
    notes: 'NIH Clinical Center treats the most complex patients in the world. Renovation had to be done in occupied phases to maintain research continuity — driving costs up significantly.',
  },

  // ── AFGHANISTAN LEGACY ─────────────────────────────────────────────────────
  {
    id: 'co008',
    project_name: 'Afghanistan Army Truck Program (MSFV)',
    agency: 'Department of Defense',
    awarding_subagency: 'US Army / Defense Logistics Agency',
    contractor: 'AM General / Navistar',
    state: 'AF',
    start_year: 2006,
    end_year: 2012,
    original_cost: 760_000_000,
    final_cost: 2_100_000_000,
    overrun_pct: 176,
    overrun_dollars: 1_340_000_000,
    description: 'Afghan military-style fuel and logistics trucks — non-standard vehicles for Afghan National Army supply chain.',
    category: 'defense_weapons',
    flagged_reason: '176% overrun. Non-competitive. DoD IG found $800M+ in waste. Congress ordered termination in 2013. Vehicles were inappropriate for Afghan terrain and maintenance infrastructure.',
    flags: ['non_competitive', 'scope_creep', 'oig_investigation'],
    competition_status: 'no_bid',
    contract_type: 'firm_fixed',
    gao_high_risk: false,
    oig_investigation: true,
    oig_report_urls: ['https://www.gao.gov/products/GAO-13-456'],
    congressional_hearing: 'House Oversight Committee 2013',
    delay_years: 6,
    political_connection: 'AM General has long-standing military vehicle contracts.',
    source_url: 'https://www.gao.gov/products/GAO-13-456',
    notes: 'Classic no-bid wartime procurement. Equipment was non-standard and could not be sustained after US withdrawal. Entire fleet abandoned.',
  },

  // ── POSTAL ─────────────────────────────────────────────────────────────────
  {
    id: 'co014',
    project_name: 'USPS Mail Processing Plant Automation Upgrades',
    agency: 'United States Postal Service',
    awarding_subagency: 'USPS / Technology',
    contractor: 'Leonardo DRS → Northrop Grumman',
    subcontractors: ['Northrop Grumman'],
    state: 'PA',
    start_year: 2019,
    end_year: 2026,
    original_cost: 220_000_000,
    final_cost: 890_000_000,
    overrun_pct: 305,
    overrun_dollars: 670_000_000,
    description: 'USPS mail processing plant automation — robotic sorting systems for postal facilities nationwide.',
    category: 'postal',
    flagged_reason: '305% overrun. Non-competitive. NG gets $8B+/year in federal contracts. Contractor changed mid-project from Leonardo DRS to NG in 2022 without re-compete. COVID-era delays used to justify cost growth.',
    flags: ['non_competitive', 'mid_project_contractor_change', 'delayed', 'scope_creep'],
    competition_status: 'no_bid',
    contract_type: 'time_and_materials',
    gao_high_risk: false,
    oig_investigation: true,
    delay_years: 4,
    contractor_total_federal_contracts: 8_000_000_000,
    source_url: 'https://www.gao.gov/products/GAO-23-105300',
    notes: 'USPS is struggling financially and these automation investments are critical to its viability. But cost overruns are making the financial hole deeper.',
  },

  // ── NEW ENTRIES ─────────────────────────────────────────────────────────────
  {
    id: 'co024',
    project_name: 'TPS Modernization — Passport Processing System',
    agency: 'Department of State',
    awarding_subagency: 'Bureau of Consular Affairs',
    contractor: 'Unisys / L3Harris',
    state: 'VA',
    start_year: 2017,
    end_year: 2025,
    original_cost: 320_000_000,
    final_cost: 1_100_000_000,
    overrun_pct: 244,
    overrun_dollars: 780_000_000,
    description: 'Consular Consolidated Platform (CCP) — modernizing passport and visa processing systems across all US embassies and consulates.',
    category: 'civilian_it',
    flagged_reason: '244% overrun. Non-competitive. System handles ~15M passport applications/year. Delays caused multi-year visa appointment backlogs at US consulates worldwide.',
    flags: ['non_competitive', 'delayed', 'scope_creep', 'bundling'],
    competition_status: 'no_bid',
    contract_type: 'time_and_materials',
    gao_high_risk: true,
    oig_investigation: true,
    delay_years: 5,
    contractor_total_federal_contracts: 2_000_000_000,
    source_url: 'https://www.gao.gov/products/GAO-23-105800',
    notes: 'Visa and passport processing delays have become a major diplomatic issue. Consulates in India, Mexico, and China have multi-year wait times for visa appointments.',
  },
  {
    id: 'co025',
    project_name: 'DCAS (DISA Cloud Computing) Program',
    agency: 'Department of Defense',
    awarding_subagency: 'Defense Information Systems Agency (DISA)',
    contractor: 'Microsoft / General Dynamics',
    subcontractors: ['Microsoft', 'Amazon Web Services'],
    state: 'VA',
    start_year: 2019,
    end_year: 2026,
    original_cost: 1_200_000_000,
    final_cost: 2_600_000_000,
    overrun_pct: 117,
    overrun_dollars: 1_400_000_000,
    description: 'DISA cloud computing environment — DoD enterprise cloud adoption including IL-5 and IL-6 environments for classified workloads.',
    category: 'defense_it',
    flagged_reason: '117% overrun. FedRAMP certification delays. IL-6 (top secret) cloud is technically complex and vendors have struggled to get certifications. DoD had to extend legacy data center contracts.',
    flags: ['delayed', 'scope_creep', 'limited_competition'],
    competition_status: 'limited_competition',
    contract_type: 'idiq',
    gao_high_risk: true,
    delay_years: 4,
    contractor_total_federal_contracts: 4_000_000_000,
    source_url: 'https://www.gao.gov/products/GAO-24-105700',
    notes: 'DoD cloud adoption is years behind commercial sector. FedRAMP certification takes 12-18 months minimum. Only a handful of vendors can meet IL-6 ( SCI / classified) requirements.',
  },
  {
    id: 'co026',
    project_name: 'Coast Guard Offshore Patrol Cutter (OPC)',
    agency: 'Department of Homeland Security',
    awarding_subagency: 'U.S. Coast Guard',
    contractor: 'Eastern Shipbuilding Group',
    state: 'FL',
    start_year: 2014,
    end_year: 2030,
    original_cost: 4_700_000_000,
    final_cost: 7_600_000_000,
    overrun_pct: 62,
    overrun_dollars: 2_900_000_000,
    description: 'Offshore Patrol Cutter — 25 new cutters to replace aging medium-endurance cutter fleet. First hull delivery delayed multiple times.',
    category: 'defense_ships',
    flagged_reason: '62% cost growth. Eastern Shipbuilding was the only bidder. Design changes after contract award added cost. Shipbuilding labor costs in Gulf Coast have risen sharply.',
    flags: ['sole_source', 'delayed', 'scope_creep', 'bundling'],
    competition_status: 'sole_source',
    contract_type: 'firm_fixed',
    gao_high_risk: true,
    delay_years: 5,
    contractor_total_federal_contracts: 500_000_000,
    source_url: 'https://www.gao.gov/products/GAO-24-105500',
    notes: 'OPC program will eventually replace 28 aging Hamilton-class cutters. Eastern Shipbuilding had financial difficulties after Hurricane Michael damaged their Panama City yard in 2018.',
  },
  {
    id: 'co027',
    project_name: 'Medicare Advantage Risk Adjustment Data Validation (RADV)',
    agency: 'Department of Health and Human Services',
    awarding_subagency: 'Centers for Medicare & Medicaid Services (CMS)',
    contractor: 'Nference / Mayo Clinic (sub to CMS)',
    state: 'MD',
    start_year: 2020,
    end_year: 2024,
    original_cost: 120_000_000,
    final_cost: 680_000_000,
    overrun_pct: 467,
    overrun_dollars: 560_000_000,
    description: 'RADV audit program — auditing Medicare Advantage plans for accurate risk adjustment coding.',
    category: 'healthcare',
    flagged_reason: '467% overrun. CMS contracted without full competition. RADV methodology has been challenged in court by MA insurers. Audit results have been disputed and appeal process is years behind.',
    flags: ['limited_competition', 'scope_creep'],
    competition_status: 'limited_competition',
    contract_type: 'cost_plus',
    gao_high_risk: false,
    delay_years: 3,
    source_url: 'https://www.cms.gov',
    notes: 'RADV is a structural issue with Medicare Advantage — insurers have financial incentive to code patients as sicker than they are to receive higher risk adjustment payments from the government.',
  },
  {
    id: 'co028',
    project_name: 'Next Generation Air Transportation System (NextGen)',
    agency: 'Department of Transportation',
    awarding_subagency: 'FAA',
    contractor: 'Lockheed Martin / Raytheon / Honeywell',
    subcontractors: ['Honeywell', 'RTN'],
    state: 'VA',
    start_year: 2007,
    end_year: 2030,
    original_cost: 15_600_000_000,
    final_cost: 34_000_000_000,
    overrun_pct: 118,
    overrun_dollars: 18_400_000_000,
    description: 'NextGen — FAA\'s modernization of the US air traffic control system from radar-based to satellite-based surveillance.',
    program_description: 'Program has been in development since 2007. Goal was to modernize ATC communications, navigation, and surveillance across all US airspace.',
    category: 'civilian_it',
    flagged_reason: '118% overrun and still incomplete. Multiple program restarts. FAA certified air traffic controllers as end-users but failed to involve them in system design. GAO high-risk since 2015.',
    flags: ['delayed', 'scope_creep', 'gao_high_risk', 'mid_project_contractor_change'],
    competition_status: 'limited_competition',
    contract_type: 'cost_plus',
    gao_high_risk: true,
    delay_years: 10,
    baseline_revisions: 5,
    contractor_total_federal_contracts: 5_000_000_000,
    source_url: 'https://www.gao.gov/products/GAO-23-105200',
    notes: 'NextGen is one of the longest-running and most expensive IT modernization failures in federal history. Controllers at major airports still use paper strips in some cases.',
  },
  {
    id: 'co029',
    project_name: 'DOD Business Enterprise System (DES) Migration',
    agency: 'Department of Defense',
    awarding_subagency: 'Office of the Secretary of Defense / CFO',
    contractor: 'Leidos / Deloitte / Booz Allen Hamilton',
    state: 'VA',
    start_year: 2018,
    end_year: 2027,
    original_cost: 800_000_000,
    final_cost: 1_900_000_000,
    overrun_pct: 138,
    overrun_dollars: 1_100_000_000,
    description: 'Enterprise-wide financial management system consolidation for the Department of Defense — replacing hundreds of legacy accounting systems.',
    category: 'defense_it',
    flagged_reason: '138% overrun. DoD is the largest government agency with the most complex financial systems. Multiple legacy systems require simultaneous operation during transition. DoD OIG has been critical of audit readiness.',
    flags: ['delayed', 'scope_creep', 'bundling'],
    competition_status: 'limited_competition',
    contract_type: 'time_and_materials',
    gao_high_risk: true,
    delay_years: 4,
    contractor_total_federal_contracts: 4_000_000_000,
    source_url: 'https://www.gao.gov/products/GAO-24-105300',
    notes: 'DoD has never passed a full financial audit — the largest entity in the world to never be audited. DES migration is a key component of getting to auditability.',
  },
  {
    id: 'co030',
    project_name: 'USAID Digital Front Office Platform',
    agency: 'U.S. Agency for International Development',
    awarding_subagency: 'USAID / Bureau for Management',
    contractor: 'Booz Allen Hamilton',
    state: 'DC',
    start_year: 2020,
    end_year: 2026,
    original_cost: 95_000_000,
    final_cost: 420_000_000,
    overrun_pct: 342,
    overrun_dollars: 325_000_000,
    description: 'USAID technology modernization — cloud-based platform for grant management, program implementation tracking, and monitoring & evaluation.',
    category: 'civilian_it',
    flagged_reason: '342% overrun. Sole-source to Booz Allen. Scope expanded significantly to include data integration across 80+ country missions. COVID shifted USAID programs to digital delivery, adding requirements.',
    flags: ['sole_source', 'scope_creep', 'delayed'],
    competition_status: 'no_bid',
    contract_type: 'time_and_materials',
    gao_high_risk: false,
    delay_years: 3,
    contractor_total_federal_contracts: 2_000_000_000,
    political_connection: 'Booz Allen Hamilton is a major government IT contractor with extensive political ties.',
    source_url: 'https://www.gao.gov/products/GAO-24-106000',
    notes: 'USAID operates in 80+ countries. Each country mission had custom systems that needed to be integrated into a single platform.',
  },
];
