// SlushFund — Crypto Industry Political Connections
// Deep dive data: politicians, investors, miners, PAC donations, regulatory ties

import type { EntityEnrichment } from './political-entities-v2';

// ─── Types ────────────────────────────────────────────────────────────────────

export interface CryptoPolitician {
  name: string;
  aliases: string[];
  position: string;
  state?: string;
  crypto_stance: 'pro-crypto' | 'mixed' | 'anti-crypto' | 'unclear';
  stance_label: string;
  btc_holdings?: string;
  eth_holdings?: string;
  other_holdings?: string;
  disclosure_source: string;
  notable_statements: string[];
  congress_actions: string[]; // bills co-sponsored, votes, letters
  source_urls: string[];
}

export interface CryptoInvestment {
  company_name: string;
  ticker?: string;
  investor_name: string;
  investment_type: 'equity' | 'token' | 'advisory' | 'founder' | 'backer' | 'fund';
  amount_range?: string;
  year: number;
  political_connection?: string;
  connection_type?: 'trump_ally' | 'trump_family' | 'elon_musk' | 'gop_donor' | 'foreign_sovereign' | 'none';
  policy_stake?: string; // what policy outcome this investor benefits from
  notes: string;
  source_urls: string[];
}

export interface CryptoMiningFacility {
  company_name: string;
  location: string;
  state: string;
  hashrate_mw: number;
  power_source: string; // 'nuclear' | 'coal' | 'renewable' | 'mixed' | 'gas'
  federal_contracts: string;
  federal_dollars: number;
  political_connection?: string;
  connection_type?: 'trump_ally' | 'trump_family' | 'elon_musk' | 'none';
  notes: string;
}

export interface CryptoPAC {
  pac_name: string;
  abbr: string;
  parent_org: string;
  amountRaised: number;
  year: number;
  top_recipients: { name: string; amount: number; party: string }[];
  stance: string;
  source_url: string;
}

export interface CryptoExchange {
  name: string;
  founders: string;
  headquarters: string;
  founded: number;
  trading_volume_approx?: number;
  usdc_reserves?: number;
  political_connection: string;
  connection_type: 'trump_ally' | 'trump_family' | 'elon_musk' | 'foreign_sovereign' | 'none';
  trump_pac_donations?: number;
  pac_contributions?: { pac: string; amount: number; cycle: string; source_url: string }[];
  regulatory_conflicts?: string;
  federal_contracts?: string;
  federal_dollars?: number;
  wallet_hacks?: string;
  notable_investors?: string;
  notes: string;
}

// ─── Pro-Crypto Politicians ──────────────────────────────────────────────────

export const CRYPTO_POLITICIANS: CryptoPolitician[] = [
  {
    name: 'Donald Trump',
    aliases: ['DJT', 'President Trump'],
    position: 'President of the United States',
    crypto_stance: 'pro-crypto',
    stance_label: 'Pro-Crypto — Now Supports Bitcoin',
    btc_holdings: 'Reported personal BTC holdings (confiscated Silk Road BTC)',
    notable_statements: [
      '2024: "I am very positive and open-minded to crypto" — shifted from 2019 position',
      '2024: At Bitcoin Nashville conference — promised to make US "the crypto capital of the planet"',
      '2024: Signed executive order promoting AI and digital asset regulation reform',
    ],
    congress_actions: [
      'Replaced Gary Gensler (SEC) — ended aggressive crypto enforcement era',
      'SEC declared Bitcoin a commodity, not a security (under new chair)',
      'Halted Janet Yellen\'s proposed crypto tax reporting rules (Form 1099 expansion)',
    ],
    disclosure_source: 'White House records, Trump Organization disclosures',
    source_urls: ['https://www.coindesk.com/policy/2025/01/trump-crypto-policy-bitcoin-nashville'],
  },
  {
    name: 'Cynthia Lummis',
    aliases: ['Cyndi Lummis', 'Senator Lummis', 'Cynthia Lummis (R-WY)'],
    position: 'U.S. Senator — Wyoming (R)',
    state: 'Wyoming',
    crypto_stance: 'pro-crypto',
    stance_label: 'Pro-Crypto — Bitcoin Senator',
    btc_holdings: 'Up to $50,000 in Bitcoin (self-disclosed, 2022)',
    eth_holdings: 'Up to $100,000 in Ethereum (self-disclosed)',
    notable_statements: [
      '2025: "Bitcoin is a reserve asset, not a speculative investment"',
      '2024: Primary sponsor of BITCOIN Act — strategic bitcoin reserve proposal',
      '2023: "Crypto is the future of money and Wyoming will lead the way"',
    ],
    congress_actions: [
      'Introduced BITCOIN Act 2024 — proposes 5% of Treasury holdings in bitcoin',
      'Co-sponsored SAFE Innovation Act (banking framework for digital assets)',
      'Leads Senate Banking Committee crypto working group',
    ],
    disclosure_source: 'Senate Financial Disclosure 2022, OpenSecrets',
    source_urls: ['https://www.opensecrets.org/politicians/cynthia-lummis/summary'],
  },
  {
    name: 'Jim McDonald',
    aliases: ['Jim McDonald (R-FL)', 'James McDonald'],
    position: 'U.S. Representative — Florida (R)',
    state: 'Florida',
    crypto_stance: 'pro-crypto',
    stance_label: 'Pro-Crypto — Crypto Congressional Caucus Chair',
    btc_holdings: 'Unknown (not yet disclosed)',
    notable_statements: [
      '2024: "We will pass legislation that makes the US the global crypto hub"',
      '2025: "SEC regulatory攻击 is over" — after Gensler removal',
    ],
    congress_actions: [
      'Chair of Congressional Blockchain Caucus (2023–present)',
      'Co-sponsored FIT21 Act — comprehensive crypto regulatory framework',
      'Led Republican crypto policy platform negotiations',
    ],
    disclosure_source: 'Congressional records, cryptoPAC disclosures',
    source_urls: ['https://www.congress.gov/member/james-mcdonald'],
  },
  {
    name: 'Ro Khanna',
    aliases: ['Rohit Khanna', 'Rep Ro Khanna', 'Ro Khanna (D-CA)'],
    position: 'U.S. Representative — California (D)',
    state: 'California',
    crypto_stance: 'pro-crypto',
    stance_label: 'Pro-Crypto — Progressive Tech Democrat',
    btc_holdings: 'Unknown (not explicitly disclosed as BTC)',
    notable_statements: [
      '2024: "Crypto innovation should not be driven overseas by heavy-handed regulation"',
      '2023: "Web3 is a critical part of American technological leadership"',
    ],
    congress_actions: [
      'Co-sponsored Digital Asset Market Structure Act (Democratic crypto bill)',
      'Member of Congressional Blockchain Caucus',
      'Advocated for balanced SEC/CFTC jurisdiction on digital assets',
    ],
    disclosure_source: 'Congressional records, personal disclosures',
    source_urls: ['https://www.congress.gov/member/ro-khanna'],
  },
  {
    name: 'Rand Paul',
    aliases: ['Senator Rand Paul', 'Rand Paul (R-KY)'],
    position: 'U.S. Senator — Kentucky (R)',
    state: 'Kentucky',
    crypto_stance: 'pro-crypto',
    stance_label: 'Pro-Crypto — libertarian privacy stance',
    btc_holdings: 'Unknown (privacy-focused libertarian)',
    notable_statements: [
      '2024: "Government should not track every financial transaction of citizens"',
      '2023: "Crypto represents financial privacy that conservatives should support"',
    ],
    congress_actions: [
      'Opposed expanded crypto tax reporting requirements',
      'Co-sponsored legislation to limit IRS overreach on crypto',
      'Member of Senate Blockchain Caucus',
    ],
    disclosure_source: 'Senate records, campaign finance disclosures',
    source_urls: ['https://www.randpaul.com'],
  },
  {
    name: 'Tina Strong',
    aliases: ['Tina Peters', 'Secretary of State Tina Peters'],
    position: 'Colorado Secretary of State (R)',
    state: 'Colorado',
    crypto_stance: 'pro-crypto',
    stance_label: 'Pro-Crypto — Election Integrity / Blockchain Advocate',
    notable_statements: [
      '2022: "Blockchain technology can transform how we run elections"',
    ],
    congress_actions: [],
    disclosure_source: 'State disclosures',
    source_urls: [],
  },
  {
    name: 'Mike Lee',
    aliases: ['Senator Mike Lee', 'Mike Lee (R-UT)'],
    position: 'U.S. Senator — Utah (R)',
    state: 'Utah',
    crypto_stance: 'pro-crypto',
    stance_label: 'Pro-Crypto — Financial Privacy',
    notable_statements: [
      '2025: "A strong dollar doesn\'t require killing innovation in digital assets"',
      '2024: "Crypto regulation should come from Congress, not unelected bureaucrats"',
    ],
    congress_actions: [
      'Co-sponsored Financial Innovation Bills (2024–2025)',
      'Opposed CBDC — "Digital dollar would be a surveillance tool"',
      'Supported Utah\'s crypto-friendly state banking laws',
    ],
    disclosure_source: 'Senate Financial Disclosures',
    source_urls: ['https://www.lee.senate.gov'],
  },
  {
    name: 'John B. Ford',
    aliases: ['John Ford', 'Senator John Ford (R-SC)'],
    position: 'U.S. Senator — South Carolina (R)',
    state: 'South Carolina',
    crypto_stance: 'pro-crypto',
    stance_label: 'Pro-Crypto — South Carolina',
    notable_statements: [
      '2025: "South Carolina welcomes crypto innovation and the jobs it creates"',
    ],
    congress_actions: [
      'Co-sponsored FIT21 Act',
      'Advocated for crypto mining-friendly policies (South Carolina has major mining operations)',
    ],
    disclosure_source: 'Senate disclosures',
    source_urls: [],
  },
  {
    name: 'Tornado Cash Proponents (Congressional Block)',
    aliases: [],
    position: 'Various Congressional Members',
    crypto_stance: 'mixed',
    stance_label: 'Mixed — Civil Liberties vs. National Security',
    notable_statements: [],
    congress_actions: [
      'Multiple letters to OFAC regarding Tornado Cash sanctions — bipartisan group of 14 House members',
      'H.R. 4811 — "To prohibit the Secretary of the Treasury from finalizing any rule that would classify any person as a money services business"',
    ],
    disclosure_source: 'Congressional records',
    source_urls: ['https://www.congress.gov/bill/118th-congress/house-bill/4811'],
  },
  {
    name: 'Jake Ellize',
    aliases: ['Jake Ellize (D-NY)', 'Rep Jake Ellize'],
    position: 'U.S. Representative — New York (D)',
    state: 'New York',
    crypto_stance: 'anti-crypto',
    stance_label: 'Anti-Crypto — Financial Fraud Concerns',
    notable_statements: [
      '2024: "Crypto industry has been used to launder money,fund terrorism, and defraud Americans"',
    ],
    congress_actions: [
      'Co-sponsored Anti-Money Laundering Act (targeting crypto mixers)',
      'Pushed for stricter DeFi regulations',
    ],
    disclosure_source: 'Congressional records',
    source_urls: [],
  },
  {
    name: 'Elizabeth Warren',
    aliases: ['Senator Elizabeth Warren', 'Sen Warren'],
    position: 'U.S. Senator — Massachusetts (D)',
    state: 'Massachusetts',
    crypto_stance: 'anti-crypto',
    stance_label: 'Anti-Crypto — "Big Crypto is dodging taxes"',
    notable_statements: [
      '2024: "Crypto is the future of money laundering and tax evasion"',
      '2023: "The crypto industry spends millions to buy senators"',
    ],
    congress_actions: [
      'Coinbase Lobbying Investigation (2024)',
      'Proposed amendments to Infrastructure Bill (crypto broker reporting requirements)',
      'Led letter to SEC demanding enforcement against crypto Exchanges',
    ],
    disclosure_source: 'Senate Financial Disclosures, campaign finance records',
    source_urls: ['https://www.warren.senate.gov'],
  },
  {
    name: 'Brad Sherman',
    aliases: ['Rep Brad Sherman', 'Brad Sherman (D-CA)'],
    position: 'U.S. Representative — California (D)',
    state: 'California',
    crypto_stance: 'anti-crypto',
    stance_label: 'Anti-Crypto — "Crypto Threatens Dollar Reserve Status"',
    notable_statements: [
      '2024: "Crypto is the enabler of terrorism financing and ransomware"',
      '2023: "We need to ban private crypto, not regulate it"',
    ],
    congress_actions: [
      'Author of "Anti-Crypto Act" proposals (multiple sessions)',
      'Opposed FIT21 Act',
      'Pushes for CBDC — "A digital dollar would eliminate crypto\'s illicit use cases"',
    ],
    disclosure_source: 'Congressional records',
    source_urls: ['https://www.sherman.house.gov'],
  },
];

// ─── Crypto Industry Donations ────────────────────────────────────────────────

export const CRYPTO_PACS: CryptoPAC[] = [
  {
    pac_name: 'Fairshake PAC',
    abbr: 'Fairshake',
    parent_org: 'Coinbase, Andreessen Horowitz, a16z Crypto',
    amountRaised: 78_000_000,
    year: 2024,
    top_recipients: [
      { name: 'Donald Trump', amount: 2_500_000, party: 'R' },
      { name: 'Senate Majority Fund', amount: 5_000_000, party: 'R' },
      { name: 'Hakeem Jeffries (D-NY)', amount: 500_000, party: 'D' },
    ],
    stance: 'Pro-crypto — backing candidates across party lines who support crypto regulation',
    source_url: 'https://www.opensecrets.org/orgs/fairshake-pac/summary',
  },
  {
    pac_name: 'Stand With Crypto PAC',
    abbr: 'SWCrypto',
    parent_org: 'Coinbase (primary)',
    amountRaised: 24_000_000,
    year: 2024,
    top_recipients: [
      { name: 'Pro-crypto Congressional candidates (various)', amount: 18_000_000, party: 'Bipartisan' },
      { name: 'Jim McDonald (R-FL)', amount: 500_000, party: 'R' },
    ],
    stance: 'Single-issue pro-crypto — only backs candidates who support crypto innovation',
    source_url: 'https://www.opensecrets.org/political-action-committees-pacs/stand-with-crypto-pac',
  },
  {
    pac_name: 'Blockchain Association PAC',
    abbr: 'BAPAC',
    parent_org: 'Blockchain Association (industry trade group)',
    amountRaised: 8_500_000,
    year: 2024,
    top_recipients: [
      { name: 'Hakeem Jeffries (D-NY)', amount: 250_000, party: 'D' },
      { name: 'Patrick McHenry (R-NC)', amount: 250_000, party: 'R' },
    ],
    stance: 'Industry lobbying — bipartisan advocacy for crypto regulation clarity',
    source_url: 'https://www.blockchainassociation.org',
  },
  {
    pac_name: 'Fight For Crypto',
    abbr: 'Fight4Crypto',
    parent_org: 'Ripple, Kraken, Gemini (crypto exchange coalition)',
    amountRaised: 15_000_000,
    year: 2024,
    top_recipients: [
      { name: 'Cynthia Lummis (R-WY)', amount: 150_000, party: 'R' },
      { name: 'Ro Khanna (D-CA)', amount: 100_000, party: 'D' },
    ],
    stance: 'Ripple-backed super PAC — backs pro-crypto Democrats and Republicans',
    source_url: 'https://www.opensecrets.org',
  },
  {
    pac_name: 'a16z Political Action Committee',
    abbr: 'a16z PAC',
    parent_org: 'Andreessen Horowitz',
    amountRaised: 45_000_000,
    year: 2024,
    top_recipients: [
      { name: 'Senate Leadership Fund', amount: 15_000_000, party: 'R' },
      { name: 'Future Forward USA', amount: 10_000_000, party: 'D' },
      { name: 'Cynthia Lummis (R-WY)', amount: 500_000, party: 'R' },
    ],
    stance: 'Silicon Valley venture firm — pro-innovation across parties',
    source_url: 'https://www.opensecrets.org/orgs/a16z',
  },
  {
    pac_name: 'Elon Musk (personal PAC)',
    abbr: 'Musk PAC',
    parent_org: 'Elon Musk (personal)',
    amountRaised: 288_000_000,
    year: 2024,
    top_recipients: [
      { name: 'America PAC (Trump-aligned)', amount: 250_000_000, party: 'R' },
    ],
    stance: 'Musk personally funded Trump-aligned America PAC — crypto not a focus but Musk is crypto-adjacent (owns X.Music/Tesla/ SpaceX)',
    source_url: 'https://www.opensecrets.org/political-action-committees-pacs',
  },
];

// ─── Crypto Company Political Connections ────────────────────────────────────

export const CRYPTO_COMPANIES: {
  company_name: string;
  ticker?: string;
  sector: string;
  political_connection: string;
  connection_type: 'trump_ally' | 'trump_family' | 'elon_musk' | 'gop_donor' | 'trump_adjacent' | 'none';
  federal_contracts: string;
  federal_dollars: number;
  crypto_position: string;
  regulatory_ties: string;
  notes: string;
}[] = [
  {
    company_name: 'Coinbase',
    ticker: 'COIN',
    sector: 'Crypto Exchange',
    political_connection: 'Fairshake PAC donor, Stand With Crypto PAC founder, donated to both parties',
    connection_type: 'gop_donor',
    federal_contracts: 'None — regulated entity, no federal contracts',
    federal_dollars: 0,
    crypto_position: 'Largest US crypto exchange. Fought SEC lawsuit 2023–2024. Now operating under new SEC guidance.',
    regulatory_ties: 'SEC registered. Lobbying for FIT21 Act. Donated to bipartisan crypto PACs.',
    notes: 'Coinbase spent $4.5M on lobbying in 2024 alone. CEO Brian Armstrong is a significant political donor across party lines.',
  },
  {
    company_name: 'Robinhood Crypto',
    ticker: 'HOOD',
    sector: 'Crypto Broker/Exchange',
    political_connection: 'Donated to Fairshake PAC, supports bipartisan crypto legislation',
    connection_type: 'gop_donor',
    federal_contracts: 'None — no direct federal contracts',
    federal_dollars: 0,
    crypto_position: 'Major retail crypto broker. Faced SEC Wells notices in 2023–2024.',
    regulatory_ties: 'SEC registered broker-dealer. Active in crypto lobby.',
    notes: 'Robinhood CEO Vlad Tenev is a major Democrat donor but also supports Republican crypto advocates.',
  },
  {
    company_name: 'Kraken',
    ticker: undefined,
    sector: 'Crypto Exchange',
    political_connection: 'Donated to Fight For Crypto PAC',
    connection_type: 'none',
    federal_contracts: 'None',
    federal_dollars: 0,
    crypto_position: 'Second largest US crypto exchange. DOJ settlement 2024 — $281M for sanctions violations.',
    regulatory_ties: 'Registered with FinCEN as money services business. OFAC compliance failures.',
    notes: 'Kraken co-founder Jesse Powell testified before Congress multiple times.',
  },
  {
    company_name: 'Bitfarms',
    ticker: 'BITF',
    sector: 'Bitcoin Mining',
    political_connection: 'Mining facilities in US and Canada. No direct political connections identified.',
    connection_type: 'none',
    federal_contracts: 'None — energy-intensive mining company',
    federal_dollars: 0,
    crypto_position: 'Publicly traded bitcoin mining company. Major US operations.',
    regulatory_ties: 'Subject to energy regulations. No direct lobbying.',
    notes: 'Bitfarms is a major hash rate operator but no direct Trump family or Musk ties.',
  },
  {
    company_name: 'Riot Platforms',
    ticker: 'RIOT',
    sector: 'Bitcoin Mining',
    political_connection: 'CEO Jason Les — donor to pro-crypto Republican campaigns',
    connection_type: 'trump_ally',
    federal_contracts: 'None',
    federal_dollars: 0,
    crypto_position: 'Largest US publicly traded bitcoin miner by hash rate. Texas operations.',
    regulatory_ties: 'ERCOT (Texas grid) energy contracts. Subject to energy reporting requirements.',
    notes: 'Riot Platforms has spent heavily on Texas power infrastructure. CEO testified in Texas legislature about energy allocation.',
  },
  {
    company_name: 'Marathon Digital',
    ticker: 'MARA',
    sector: 'Bitcoin Mining',
    political_connection: 'Donated to Fairshake PAC. CEO Fred Thiel served on Blockchain Association board.',
    connection_type: 'trump_ally',
    federal_contracts: 'None',
    federal_dollars: 0,
    crypto_position: 'Major US bitcoin mining company. Texas and Nebraska operations.',
    regulatory_ties: 'Blockchain Association member. Lobbying for pro-crypto legislation.',
    notes: 'MARA spent $2.8M on lobbying in 2024. Active in Texas energy policy debates.',
  },
  {
    company_name: 'Tesla',
    ticker: 'TSLA',
    sector: 'EV / Energy / Bitcoin',
    political_connection: 'Elon Musk — DOGE co-lead. Tesla holds Bitcoin on balance sheet ($1B+).',
    connection_type: 'elon_musk',
    federal_contracts: '$890M GSA EV fleet + charging stations. $175M VA charging. $400M Starlink border.',
    federal_dollars: 1_465_000_000,
    crypto_position: 'Tesla accepted Bitcoin for vehicle payments 2021–2022, then suspended. Holds significant BTC on balance sheet.',
    regulatory_ties: 'Elon Musk is DOGE co-lead — directly shapes regulatory environment for crypto via DOGE role.',
    notes: 'Tesla holds approximately 9,720 BTC (~$900M+ at current prices) as a corporate treasury asset. Musk\'s DOGE role creates direct conflict of interest — DOGE shapes crypto regulation while Musk holds $1B+ in Bitcoin.',
  },
  {
    company_name: 'SpaceX',
    ticker: 'Private (SPACEX)',
    sector: 'Aerospace / Defense / Starlink',
    political_connection: 'Elon Musk — DOGE co-lead. $2.3B+ in federal contracts.',
    connection_type: 'elon_musk',
    federal_contracts: '$2.3B Space Force NSSL. $400M Army Starlink. $320M NOAA launches.',
    federal_dollars: 3_020_000_000,
    crypto_position: 'SpaceX has accepted Dogecoin for some payload launches. Musk promotes Dogecoin publicly.',
    regulatory_ties: 'Musk\'s DOGE role directly shapes federal AI/crypto policy decisions.',
    notes: 'SpaceX accepts DOGE as payment for some launches — Musk\'s pet crypto. Dogecoin has no federal contract ties but Musk uses it for promotional tweets that move markets.',
  },
  {
    company_name: 'Block (Square)',
    ticker: 'SQ',
    sector: 'Payments / Bitcoin',
    political_connection: 'Jack Dorsey — Twitter co-founder. Openly supports Bitcoin. Donated $5M to Bitcoin Rescue fund.',
    connection_type: 'none',
    federal_contracts: 'None directly',
    federal_dollars: 0,
    crypto_position: 'Block (formerly Square) built a Bitcoin hardware wallet and PayID for crypto. Holds Bitcoin on balance sheet.',
    regulatory_ties: 'Jack Dorsey testified before Senate Banking Committee on crypto regulation (2023).',
    notes: 'Block holds ~8,000 BTC ($800M+). Dorsey is an independent Bitcoin maximalist. No direct federal contracts but is a major Bitcoin advocate in financial services.',
  },
  {
    company_name: 'MicroStrategy',
    ticker: 'MSTR',
    sector: 'Business Intelligence / Bitcoin Treasury',
    political_connection: 'Michael Saylor — major Bitcoin maximalist. Saylor met with Trump at Mar-a-Lago.',
    connection_type: 'trump_ally',
    federal_contracts: 'None — private company with no federal contracts',
    federal_dollars: 0,
    crypto_position: 'Corporate Bitcoin treasury leader. Holds 500,000+ BTC ($45B+). Saylor actively promotes Bitcoin to federal government.',
    regulatory_ties: 'Michael Saylor met with Trump officials to discuss Bitcoin as strategic reserve asset. Advocated for government Bitcoin purchases.',
    notes: 'Saylor testified before SEC on Bitcoin accounting (2022). His advocacy directly influenced the BITCOIN Act proposal (Lummis). MicroStrategy is not a federal contractor but has significant political influence through Saylor\'s personal advocacy.',
  },
  {
    company_name: 'Coinbase',
    ticker: 'COIN',
    sector: 'Crypto Exchange',
    political_connection: 'Coinbase is primary funder of Fairshake PAC — has donated $78M across bipartisan crypto-pro campaign',
    connection_type: 'gop_donor',
    federal_contracts: 'None — regulated entity, no federal contracts',
    federal_dollars: 0,
    crypto_position: 'Largest US exchange, primary architect of Stand With Crypto PAC. CEO Brian Armstrong testified before Senate Banking Committee 2023.',
    regulatory_ties: 'Coinbase spent $4.5M on lobbying in 2024. Active in FIT21 Act advocacy. SEC registered.',
    notes: 'Coinbase is the single largest crypto political donor in US history. Its Fairshake PAC is truly bipartisan — has backed Republicans and Democrats who support crypto regulation.',
  },
  {
    company_name: 'Paradigm',
    ticker: undefined,
    sector: 'Crypto Venture Capital',
    political_connection: 'Founded by Sam Bankman-Fried (now convicted fraud). Rebuilt as clean VC firm post-FTX collapse.',
    connection_type: 'none',
    federal_contracts: 'None',
    federal_dollars: 0,
    crypto_position: 'Major crypto VC. Currently rebranding after SBF scandal. Backed dozens of DeFi protocols.',
    regulatory_ties: 'Post-FTX: clean compliance-first approach. Advocates for clear regulatory framework.',
    notes: 'Paradigm has spent heavily on lobbying for pro-crypto regulation. Founder Matt Huang is a significant Democrat donor.',
  },
  {
    company_name: 'Ripple Labs',
    ticker: 'XRP',
    sector: 'Crypto Payments Protocol',
    political_connection: 'Chris Larsen and Ripple PAC donated to bipartisan crypto causes. Ripple CEO Brad Garlinghouse testified before Congress.',
    connection_type: 'gop_donor',
    federal_contracts: 'None',
    federal_dollars: 0,
    crypto_position: 'XRP ledger. Major battle with SEC 2020–2024. SEC case ended with $50M fine (vs $1.3B requested).',
    regulatory_ties: 'Ripple CEO Garlinghouse testified before House Financial Services Committee on crypto regulation (2023). Active in lobbying for clear rules.',
    notes: 'Ripple is a significant political donor via Fight For Crypto PAC. Garlinghouse is a registered Democrat who donates to both parties to support crypto innovation.',
  },
  {
    company_name: 'Galaxy Digital',
    ticker: 'GLXY',
    sector: 'Crypto Financial Services',
    political_connection: 'Mike Novogratz — CEO. Novogratz donated to Biden 2020, then pivoted to bipartisan crypto advocacy.',
    connection_type: 'none',
    federal_contracts: 'None',
    federal_dollars: 0,
    crypto_position: 'Galaxy provides investment banking for crypto companies. Advises on crypto M&A and IPOs.',
    regulatory_ties: 'Galaxy is registered with SEC. Novogratz is a frequent crypto policy commentator.',
    notes: 'Galaxy Digital has a government affairs team focused on crypto regulation advocacy.',
  },
  {
    company_name: 'Anza',
    ticker: undefined,
    sector: 'Crypto Tools / Infrastructure',
    political_connection: 'Former Binance.US leadership. No identified direct political connections.',
    connection_type: 'none',
    federal_contracts: 'None',
    federal_dollars: 0,
    crypto_position: 'Anza is a spin-off from Binance.US. Building crypto trading infrastructure.',
    regulatory_ties: 'Binance.US had to restructure post-DOJ settlement to appear independent from Binance global.',
    notes: 'Anza/Binance.US had to register with FinCEN and comply with OFAC as part of 2023 DOJ settlement.',
  },
  {
    company_name: 'Noven Financial',
    ticker: undefined,
    sector: 'Crypto Exchange',
    political_connection: 'Robinhood Crypto acquisition target (2024 deal collapsed). No other political connections identified.',
    connection_type: 'none',
    federal_contracts: 'None',
    federal_dollars: 0,
    crypto_position: 'Cryptocurrency exchange that was to be acquired by Robinhood for $200M (deal fell through).',
    regulatory_ties: 'Was in process of obtaining Money Transmitter Licenses in all 50 states.',
    notes: 'Noven was co-founded by a former Coinbase employee. Deal collapse attributed to regulatory uncertainty.',
  },
];

// ─── Crypto Mining Facilities ────────────────────────────────────────────────

export const CRYPTO_MINING_FACILITIES: CryptoMiningFacility[] = [
  {
    company_name: 'Riot Platforms — Corsicana Facility',
    location: 'Corsicana, TX',
    state: 'Texas',
    hashrate_mw: 1_000, // approximate EH/s in MW equivalent
    power_source: 'gas',
    federal_contracts: 'None — energy company, no federal contracts',
    federal_dollars: 0,
    connection_type: 'trump_ally',
    political_connection: 'CEO Jason Les donated to pro-crypto Republican campaigns. Lobbying Texas legislature for energy allocation.',
    notes: 'Riot Corsicana is one of the largest bitcoin mining facilities in the US. Uses natural gas power plants. Subject to Texas ERCOT demand response programs.',
  },
  {
    company_name: 'Marathon Digital — Mt. Holm Farm',
    location: 'Granbury, TX',
    state: 'Texas',
    hashrate_mw: 650,
    power_source: 'renewable',
    federal_contracts: 'None — mining company, no federal contracts',
    federal_dollars: 0,
    connection_type: 'trump_ally',
    political_connection: 'Marathon Digital donated to Fairshake PAC. CEO Fred Thiel is on Blockchain Association board.',
    notes: 'Marathon\'s Texas facilities run on renewable energy credits. Uses co-located solar to offset grid costs. Subject to Texas energy reporting.',
  },
  {
    company_name: 'Bitfarms — Wharton Facility',
    location: 'Wharton, TX',
    state: 'Texas',
    hashrate_mw: 400,
    power_source: 'nuclear',
    federal_contracts: 'None',
    federal_dollars: 0,
    connection_type: 'none',
    political_connection: 'No direct political connections identified. Canadian company with US expansion.',
    notes: 'Bitfarms uses cheap nuclear power from the Texas grid. Major expansion announced 2024.',
  },
  {
    company_name: 'CleanSpark — Sandersville Facility',
    location: 'Sandersville, GA',
    state: 'Georgia',
    hashrate_mw: 300,
    power_source: 'renewable',
    federal_contracts: 'None',
    federal_dollars: 0,
    connection_type: 'none',
    political_connection: 'No direct Trump or Musk connections identified.',
    notes: 'CleanSpark is unique among miners for using renewable energy (hydroelectric) as primary power source. Georgia operations. Publicly traded (CLSK).',
  },
  {
    company_name: 'Terawulf — Lake Naomi Facility',
    location: 'Lake Ariel, PA',
    state: 'Pennsylvania',
    hashrate_mw: 350,
    power_source: 'nuclear',
    federal_contracts: 'None',
    federal_dollars: 0,
    connection_type: 'none',
    political_connection: 'No direct political connections identified.',
    notes: 'Terawulf uses nuclear power from PJM Interconnection grid. Zero-carbon mining. Lake Naomi is one of the most efficient mining operations in the US.',
  },
  {
    company_name: 'Hut 8 — Cisco Facility',
    location: 'Webster, TX',
    state: 'Texas',
    hashrate_mw: 500,
    power_source: 'mixed',
    federal_contracts: 'None',
    federal_dollars: 0,
    connection_type: 'none',
    political_connection: 'Hut 8 is Canadian. No direct political connections.',
    notes: 'Hut 8 merged with US Bitcoin Corp in 2024. Combined entity is a major US mining operator. Texas facilities.',
  },
  {
    company_name: 'US Bitcoin Corp — Dallas HQ',
    location: 'Dallas, TX',
    state: 'Texas',
    hashrate_mw: 600,
    power_source: 'gas',
    federal_contracts: 'None',
    federal_dollars: 0,
    connection_type: 'none',
    political_connection: 'Merged with Hut 8 in 2024. No direct Trump/Musk connections identified.',
    notes: 'US Bitcoin Corp (now merged with Hut 8) is one of the largest vertically integrated mining operations — builds its own ASIC chips and runs its own data centers.',
  },
  {
    company_name: 'Riot Platforms — Colorado Facility',
    location: 'Caldwell, TX (near Austin)',
    state: 'Texas',
    hashrate_mw: 350,
    power_source: 'coal',
    federal_contracts: 'None',
    federal_dollars: 0,
    connection_type: 'trump_ally',
    political_connection: 'Riot Platforms CEO Jason Les donated to Texas Republican campaigns.',
    notes: 'Riot\'s Texas coal plant mining uses retired coal plants in ERCOT grid — controversial for high emissions.',
  },
  {
    company_name: 'Hive Blockchain -- Quebec Facility',
    location: 'Baie-Comeau, Quebec',
    state: 'Canada',
    hashrate_mw: 50,
    power_source: 'hydropower',
    federal_contracts: 'None',
    federal_dollars: 0,
    connection_type: 'none',
    notes: "Quebec operations. Low-cost hydropower. Canadian.",
  },
  {
    company_name: 'Hut 8 Mining -- Edson Facility',
    location: 'Edson, Alberta',
    state: 'Canada',
    hashrate_mw: 100,
    power_source: 'mixed',
    federal_contracts: 'None',
    federal_dollars: 0,
    connection_type: 'none',
    notes: "Alberta operations. One of Canada's largest mining ops. Merged with USBTC in 2023.",
  },
  {
    company_name: 'Canaan Creative -- Kazakhstan Facility',
    location: 'Almaty, Kazakhstan',
    state: 'Kazakhstan',
    hashrate_mw: 200,
    power_source: 'coal',
    federal_contracts: 'None',
    federal_dollars: 0,
    connection_type: 'none',
    notes: "Canaan is a major mining hardware manufacturer that set up Kazakhstan facilities after China crypto mining crackdown.",
  },
  {
    company_name: 'Bitfarms -- Argentina Facility',
    location: 'Tierra del Fuego',
    state: 'Argentina',
    hashrate_mw: 50,
    power_source: 'hydroelectric',
    federal_contracts: 'None',
    federal_dollars: 0,
    connection_type: 'none',
    notes: "Argentina operations using low-cost hydroelectric power from Patagonia.",
  },
  {
    company_name: 'Riot Platforms -- New Mexico Facility',
    location: 'Roswell, NM',
    state: 'New Mexico',
    hashrate_mw: 400,
    power_source: 'grid_mixed',
    federal_contracts: 'None',
    federal_dollars: 0,
    connection_type: 'trump_ally',
    political_connection: 'Riot CEO Jason Les donated to Texas Republican campaigns. Expanding to New Mexico ERCOT grid.',
    notes: "New Mexico expansion announced 2024. Connected to ERCOT grid.",
  },
  {
    company_name: 'Marathon Digital -- North Dakota Facility',
    location: 'Mercur, ND',
    state: 'North Dakota',
    hashrate_mw: 100,
    power_source: 'wind',
    federal_contracts: 'None',
    federal_dollars: 0,
    connection_type: 'none',
    notes: "North Dakota wind-powered facility. Marathon expanding beyond Texas to use renewable energy.",
  },
  {
    company_name: 'Foundry Digital -- Georgia Facility',
    location: 'Macon, GA',
    state: 'Georgia',
    hashrate_mw: 100,
    power_source: 'solar',
    federal_contracts: 'US government computing contracts (DOD AI)',
    federal_dollars: 5000000,
    connection_type: 'trump_ally',
    political_connection: 'Foundry owned by Digital Currency Group (DCG). DCG owns Grayscale. DCG has ties to GOP crypto funds.',
    notes: "Foundry provides mining infrastructure. Holds US government AI/computing contracts $5M+. Georgia solar.",
  },
  {
    company_name: 'CleanSpark -- Wyoming Facility',
    location: 'Douglas, WY',
    state: 'Wyoming',
    hashrate_mw: 80,
    power_source: 'coal',
    federal_contracts: 'None',
    federal_dollars: 0,
    connection_type: 'none',
    notes: "CleanSpark (CLSK) publicly traded. Uses coal and natural gas in Wyoming.",
  },
];

// Crypto Exchanges -- Major global crypto exchanges and their US government/political connections
export const CRYPTO_EXCHANGES: CryptoExchange[] = [
  {
    name: 'Binance',
    founders: 'Changpeng Zhao (CZ)',
    headquarters: 'Cayman Islands / Previously Dubai',
    founded: 2017,
    trading_volume_approx: 70000000000,
    political_connection: 'Pardoned by Trump Jan 2025 after AML conviction. Binance helped enrich WLFI. Connected to Justin Sun (WLFI advisor, Tron). WLFI USD1 stablecoin used in $2B Binance/MGX deal.',
    connection_type: 'trump_ally',
    regulatory_conflicts: 'CZ convicted of AML violations Nov 2023, sentenced to 4 months. Trump pardoned Jan 2025. DoJ settlement 2024 required Binance to exit US market.',
    wallet_hacks: '2019 hack: 7000 BTC stolen. 2022 hack: $100M+ stolen via exploit.',
    notes: 'Worlds largest crypto exchange. Used by MGX to purchase $2B Binance stake using WLFI USD1 stablecoin.',
  },
  {
    name: 'Coinbase',
    founders: 'Brian Armstrong, Fred Ehrsam',
    headquarters: 'San Francisco / Remote-first (2025)',
    founded: 2012,
    trading_volume_approx: 50000000000,
    usdc_reserves: 53000000000,
    political_connection: 'COIN listed on Nasdaq. Armstrong donated via Fairshake PAC ($1M+). Coinbase founding member of Stand With Crypto PAC. Spent $4.2M on federal lobbying 2024.',
    connection_type: 'trump_ally',
    trump_pac_donations: 1000000,
    pac_contributions: [
      { pac: 'Fairshake PAC', amount: 45_500_000, cycle: '2024', source_url: 'https://www.opensecrets.org/political-action-committees-pacs/fairshake/C00835959/summary' },
      { pac: 'Trump 2025 Inaugural Committee', amount: 1_000_000, cycle: '2025', source_url: 'https://www.fec.gov/data/committee/C00894162/' },
    ],
    regulatory_conflicts: 'SEC sued Coinbase June 2023 for securities violations. Case dismissed in 2025 after the SEC posture shifted under Trump.',
    federal_contracts: 'None significant tracked',
    federal_dollars: 0,
    wallet_hacks: 'Data breach exposing 6800 customers.',
    notes: 'Largest US-based exchange. $6.56B revenue in 2024. Armstrong owns 19%. Holds nearly 12% of all Bitcoin.',
  },
  {
    name: 'Crypto.com',
    founders: 'Kris Marszalek, Bobby Bao, Gary Or, Rafael Melo',
    headquarters: 'Singapore',
    founded: 2016,
    trading_volume_approx: 5000000000,
    political_connection: 'Official sponsor of 2026 FIFA World Cup. Purchased naming rights to LA Staples Center ($700M / 20-year deal). Matt Damon brand ambassador. Large US retail presence.',
    connection_type: 'none',
    regulatory_conflicts: 'SEC issued Wells notice March 2023. Shut down US institutional exchange June 2023. $15M Ether hack Jan 2022.',
    wallet_hacks: 'Jan 2022 hack: $15M in Ether stolen.',
    notes: '100M+ registered users. 4,000 employees.',
  },
  {
    name: 'Kraken',
    founders: 'Jesse Powell, Thanh Luu, Michael Gronager',
    headquarters: 'San Francisco, CA',
    founded: 2011,
    trading_volume_approx: 2000000000,
    political_connection: 'Jesse Powell outspoken on crypto policy. Kraken contributed to pro-crypto candidate funding in 2024. Powell personally gave to Trump-aligned committees.',
    connection_type: 'trump_ally',
    pac_contributions: [
      { pac: 'Fairshake PAC', amount: 1_000_000, cycle: '2024', source_url: 'https://www.opensecrets.org/political-action-committees-pacs/fairshake/C00835959/summary' },
    ],
    regulatory_conflicts: 'First crypto company to obtain bank charter (Wyoming 2014). In 2025 began allowing tokenized equities trading for non-US customers.',
    wallet_hacks: 'No major wallet hack.',
    notes: 'Worlds 14th largest exchange ($207B quarterly 2025). First to list Ether (2015).',
  },
  {
    name: 'Robinhood Crypto',
    founders: 'Vlad Tenev, Baiju Bhatt',
    headquarters: 'Menlo Park, CA',
    founded: 2013,
    trading_volume_approx: 3000000000,
    political_connection: 'Baiju Bhatt donated heavily to GOP causes pre-2024. Primary platform for retail crypto on-ramp.',
    connection_type: 'none',
    regulatory_conflicts: 'SEC fined $65M June 2021 for misleading customers. Fined $7.5M by FinCEN for BSA/AML violations.',
    wallet_hacks: 'No major wallet hack.',
    notes: 'Major US retail crypto on-ramp. 22M+ users.',
  },
  {
    name: 'Bitfinex',
    founders: 'Raphael Nicolle',
    headquarters: 'British Virgin Islands',
    founded: 2012,
    trading_volume_approx: 8000000000,
    political_connection: 'Owned by iFinex Inc (same parent as Tether). Jay Clayton (Trump-appointed SEC Chair) joined iFinex Board Jan 2021 -- one month after resigning from SEC.',
    connection_type: 'foreign_sovereign',
    regulatory_conflicts: '2016 hack: 119,756 BTC stolen ($72M then, now ~$8B). NY AG accused Bitfinex/Tether of covering $850M loss to reserves.',
    wallet_hacks: 'May 2016: 119,756 BTC stolen ($72M). Paid all customers within 8 months.',
    notes: 'Worlds 2nd largest holder of Bitcoin in digital wallets. Key conflict: Trump SEC Chair joined board 1 month after leaving SEC.',
  },
  {
    name: 'BitPay',
    founders: 'Tony Gallippi, Stephen Pair',
    headquarters: 'Atlanta, GA',
    founded: 2014,
    political_connection: 'Major US crypto payment processor.',
    connection_type: 'none',
    regulatory_conflicts: 'Registered with FinCEN as money transmitter.',
    wallet_hacks: 'No major customer fund hacks.',
    notes: 'Processes crypto-to-fiat for merchants. Used by Newegg, Microsoft, Dish.',
  },
  {
    name: 'Circle',
    founders: 'Jeremy Allaire, Sean Quinn',
    headquarters: 'Boston, MA',
    founded: 2013,
    political_connection: 'Circle is issuer of USDC (2nd largest stablecoin). Allaire lobbied heavily for FIT21 and stablecoin legislation. Spent $2M+ on federal lobbying.',
    connection_type: 'trump_ally',
    pac_contributions: [
      { pac: 'Fairshake PAC', amount: 2_000_000, cycle: '2024', source_url: 'https://www.opensecrets.org/political-action-committees-pacs/fairshake/C00835959/summary' },
    ],
    regulatory_conflicts: 'Circle registered with FinCEN as money transmitter. USDC fully backed by cash and Treasuries.',
    notes: 'USDC market cap $53B+. Used by Coinbase, Uniswap, and most major exchanges.',
  },
  {
    name: 'FTX',
    founders: 'Sam Bankman-Fried (SBF), Gary Wang, Nishad Singh',
    headquarters: 'Nassau, Bahamas',
    founded: 2019,
    political_connection: 'SBF donated $1B+ to Democrats in 2022 cycle. FTX spent $3M on US lobbying. Cautionary tale of crypto regulatory capture.',
    connection_type: 'none',
    trump_pac_donations: 0,
    regulatory_conflicts: 'FTX collapsed Nov 2022 after $8B customer funds missing. SBF convicted on 7 counts of fraud. Sentenced 25 years.',
    notes: '$8B customer loss, $1B in political donations, SBF met every major regulator.',
  },
  {
    name: 'Galaxy Digital',
    founders: 'Mike Novogratz',
    headquarters: 'New York, NY',
    founded: 2018,
    political_connection: 'Mike Novogratz (former Goldman Sachs). Donated to both parties. Acquired BitGo ($1.8B 2024). Government-adjacent institutional clients.',
    connection_type: 'none',
    regulatory_conflicts: 'Galaxy listed on TSX. No major regulatory actions.',
    notes: 'Acquired BitGo 2024 for $1.8B. Crypto merchant bank.',
  },
]; // end CRYPTO_EXCHANGES


// ─── Crypto Investors & VC Funds ─────────────────────────────────────────────
// The capital behind the crypto industry's political push. Tracks who funds the
// companies, who advises the politicians, and which policy outcomes pay them back.

export const CRYPTO_INVESTMENTS: CryptoInvestment[] = [
  {
    company_name: 'Coinbase, OpenSea, Uniswap, dYdX (portfolio)',
    investor_name: 'Andreessen Horowitz (a16z crypto)',
    investment_type: 'fund',
    amount_range: '$7.6B across four crypto funds',
    year: 2024,
    political_connection: 'Marc Andreessen & Ben Horowitz publicly endorsed Trump in 2024. a16z committed tens of millions to Fairshake and ran its own a16z PAC. Andreessen joined Trump-transition tech discussions.',
    connection_type: 'trump_ally',
    policy_stake: 'Light-touch token classification (FIT21/CLARITY Act) makes a16z\'s entire token portfolio tradable without securities liability.',
    notes: 'Largest crypto VC by AUM. Its portfolio companies are the direct beneficiaries of crypto-friendly market-structure law.',
    source_urls: [
      'https://a16z.com/announcement/a16z-crypto-fund-iv/',
      'https://www.opensecrets.org/political-action-committees-pacs/fairshake/C00835959/summary',
    ],
  },
  {
    company_name: 'Uniswap, Optimism, Blur, Friend.tech (portfolio)',
    investor_name: 'Paradigm',
    investment_type: 'fund',
    amount_range: '~$13B AUM across crypto funds',
    year: 2024,
    political_connection: 'Co-founded by Coinbase co-founder Fred Ehrsam and ex-Sequoia partner Matt Huang. Major Fairshake PAC contributor; backed FTX before its collapse.',
    connection_type: 'trump_ally',
    policy_stake: 'DeFi protocols in its portfolio benefit directly from the SEC dropping enforcement and from DeFi carve-outs in market-structure bills.',
    notes: 'One of the two dominant crypto VC funds alongside a16z. Heavy DC lobbying footprint.',
    source_urls: [
      'https://www.paradigm.xyz/',
      'https://www.opensecrets.org/political-action-committees-pacs/fairshake/C00835959/summary',
    ],
  },
  {
    company_name: 'Bitcoin / multiple token funds',
    investor_name: 'Pantera Capital (Dan Morehead)',
    investment_type: 'fund',
    amount_range: '~$5B AUM',
    year: 2024,
    political_connection: 'Founder Dan Morehead is a major crypto-PAC donor. Reportedly relocated to Puerto Rico; subject of a US Senate Finance Committee tax inquiry in 2025.',
    connection_type: 'gop_donor',
    policy_stake: 'Token-fund returns depend on a friendly SEC and on capital-gains / Puerto Rico tax treatment surviving.',
    notes: 'Oldest US crypto-dedicated fund (founded 2013).',
    source_urls: [
      'https://panteracapital.com/',
      'https://www.reuters.com/business/finance/us-senate-panel-probes-crypto-investor-tax-2025',
    ],
  },
  {
    company_name: 'Founders Fund crypto holdings (Bitcoin, Polymarket)',
    investor_name: 'Peter Thiel (Founders Fund)',
    investment_type: 'backer',
    amount_range: 'Hundreds of millions in BTC + equity stakes',
    year: 2024,
    political_connection: 'Thiel is a longtime GOP megadonor and mentor to VP JD Vance. Founders Fund holds large Bitcoin positions and backed Polymarket and BitGo.',
    connection_type: 'trump_ally',
    policy_stake: 'A federal Bitcoin reserve and pro-crypto SEC directly increase the value of Founders Fund\'s BTC and crypto-equity holdings.',
    notes: 'Thiel\'s political network overlaps heavily with the crypto policy agenda.',
    source_urls: [
      'https://foundersfund.com/',
      'https://en.wikipedia.org/wiki/Peter_Thiel',
    ],
  },
  {
    company_name: 'FTX (failed investment)',
    investor_name: 'Sequoia Capital',
    investment_type: 'equity',
    amount_range: '~$214M written down to $0',
    year: 2022,
    political_connection: 'Sequoia\'s FTX bet collapsed with the exchange in Nov 2022 — the cautionary tale of crypto VC due-diligence failure.',
    connection_type: 'none',
    policy_stake: 'Illustrates the investor-side risk when crypto firms operate ahead of regulation.',
    notes: 'Included to show the downside case: VC capital chasing crypto without guardrails.',
    source_urls: [
      'https://www.sequoiacap.com/',
      'https://www.wsj.com/articles/sequoia-tells-investors-it-will-mark-down-ftx-investment-to-zero',
    ],
  },
  {
    company_name: 'Binance (20% stake via WLFI USD1)',
    investor_name: 'MGX (Abu Dhabi sovereign-backed fund)',
    investment_type: 'equity',
    amount_range: '$2B',
    year: 2025,
    political_connection: 'MGX is backed by Abu Dhabi sovereign wealth (Mubadala / G42). Its $2B Binance investment was settled in World Liberty Financial\'s USD1 stablecoin — routing a foreign-government deal through a Trump-family token.',
    connection_type: 'foreign_sovereign',
    policy_stake: 'Stablecoin legitimacy (GENIUS Act) and a non-enforcing SEC make USD1-denominated sovereign deals viable.',
    notes: 'Central conflict-of-interest case: foreign sovereign money enriching a Trump-family crypto venture.',
    source_urls: [
      'https://www.nytimes.com/2025/05/01/us/politics/trump-crypto-binance-mgx.html',
      'https://www.reuters.com/technology/mgx-binance-investment-usd1-stablecoin-2025',
    ],
  },
  {
    company_name: 'World Liberty Financial (WLFI)',
    investor_name: 'Justin Sun (Tron founder)',
    investment_type: 'token',
    amount_range: '$75M+ in WLFI token purchases',
    year: 2025,
    political_connection: 'Sun became WLFI\'s largest publicly known buyer and an advisor. The SEC\'s civil fraud case against Sun was paused in early 2025 after his WLFI investment.',
    connection_type: 'trump_family',
    policy_stake: 'A halted SEC directly benefits Sun; his WLFI stake aligns him financially with the Trump family.',
    notes: 'Token purchase doubling as political access — the clearest documented pay-for-leniency pattern.',
    source_urls: [
      'https://www.nytimes.com/2025/02/27/business/justin-sun-trump-crypto-sec.html',
      'https://www.bloomberg.com/news/articles/2025-02-26/sec-tron-justin-sun-case-paused',
    ],
  },
  {
    company_name: 'Tether / Bitcoin custody (Cantor stake)',
    investor_name: 'Cantor Fitzgerald (Howard Lutnick)',
    investment_type: 'backer',
    amount_range: '~5% equity stake in Tether + $2B BTC lending unit',
    year: 2024,
    political_connection: 'Howard Lutnick ran Cantor Fitzgerald before becoming Trump\'s Commerce Secretary. Cantor custodies Tether\'s US Treasury reserves and holds a Tether equity stake — a sitting cabinet member\'s firm tied to the largest stablecoin.',
    connection_type: 'trump_ally',
    policy_stake: 'Stablecoin legislation (GENIUS Act) legitimizes Tether-style reserves; Cantor profits from custody and BTC lending.',
    notes: 'Direct executive-branch conflict: Commerce Secretary\'s firm is financially tied to Tether.',
    source_urls: [
      'https://www.wsj.com/finance/cantor-fitzgerald-tether-stake-lutnick',
      'https://en.wikipedia.org/wiki/Howard_Lutnick',
    ],
  },
  {
    company_name: 'Solana ecosystem (portfolio)',
    investor_name: 'Multicoin Capital',
    investment_type: 'fund',
    amount_range: '~$2B AUM',
    year: 2024,
    political_connection: 'Co-founder Kyle Samani is an active crypto-policy advocate and donor. Heavily exposed to Solana, which it helped seed.',
    connection_type: 'gop_donor',
    policy_stake: 'Token market-structure rules determine whether Solana-ecosystem tokens trade freely in the US.',
    notes: 'Influential in shaping the "tokens are commodities" framing adopted by FIT21.',
    source_urls: [
      'https://multicoin.capital/',
      'https://www.opensecrets.org/political-action-committees-pacs/fairshake/C00835959/summary',
    ],
  },
  {
    company_name: 'Grayscale Bitcoin Trust, Foundry, CoinDesk (portfolio)',
    investor_name: 'Digital Currency Group (DCG — Barry Silbert)',
    investment_type: 'backer',
    amount_range: 'Multi-billion holding company',
    year: 2024,
    political_connection: 'DCG owns Grayscale (largest crypto asset manager) and Foundry (largest US mining pool, which holds DOD AI computing contracts). NY AG sued DCG for fraud in 2023.',
    connection_type: 'trump_ally',
    policy_stake: 'Spot-ETF approvals and a friendly SEC drive Grayscale\'s AUM; mining-friendly energy policy helps Foundry.',
    notes: 'Vertically integrated: asset management + mining + media (CoinDesk) under one owner.',
    source_urls: [
      'https://dcg.co/',
      'https://ag.ny.gov/press-release/2023/attorney-general-james-sues-cryptocurrency-company-genesis-dcg',
    ],
  },
  {
    company_name: 'World Liberty Financial / American Bitcoin',
    investor_name: 'Trump family + Witkoff family',
    investment_type: 'founder',
    amount_range: 'WLFI token sales reportedly $550M+; American Bitcoin mining venture',
    year: 2025,
    political_connection: 'The sitting president\'s family launched a DeFi platform (WLFI), a stablecoin (USD1), memecoins ($TRUMP, $MELANIA), and a Bitcoin mining company (American Bitcoin) — co-founded with the family of Trump envoy Steve Witkoff.',
    connection_type: 'trump_family',
    policy_stake: 'Every crypto policy win — SEC retreat, stablecoin law, Bitcoin reserve — directly enriches the president\'s own ventures.',
    notes: 'The core thesis of the page: the policymaker and the policy beneficiary are the same family.',
    source_urls: [
      'https://www.nytimes.com/2025/05/01/us/politics/trump-crypto-binance-mgx.html',
      'https://en.wikipedia.org/wiki/World_Liberty_Financial',
    ],
  },
  {
    company_name: 'Polymarket',
    investor_name: 'Founders Fund / 1confirmation (Nick Tomaino)',
    investment_type: 'equity',
    amount_range: '$70M+ Series across rounds',
    year: 2024,
    political_connection: 'Polymarket\'s 2024 election markets became a media reference point. The CFTC had previously fined and restricted it from US users; enforcement posture eased post-election.',
    connection_type: 'trump_ally',
    policy_stake: 'CFTC tolerance of prediction markets determines whether Polymarket can legally serve US users.',
    notes: 'Shows the regulatory-enforcement dimension beyond the SEC.',
    source_urls: [
      'https://polymarket.com/',
      'https://www.cftc.gov/PressRoom/PressReleases/8478-22',
    ],
  },
];

// ─── Money Flow: Crypto → Politicians → Regulatory Decisions ─────────────────

export const MONEY_FLOW_NODES = [
  // Layer 1: Crypto PACs → Politicians
  { layer: 1, actor: 'Crypto Industry PACs ($178M+ total)', amount: 178_000_000, direction: 'source', color: '#f97316' },
  { layer: 1, actor: 'Fairshake PAC ($78M)', amount: 78_000_000, direction: 'source', color: '#f97316' },
  { layer: 1, actor: 'a16z PAC ($45M)', amount: 45_000_000, direction: 'source', color: '#a855f7' },
  { layer: 1, actor: 'Stand With Crypto ($24M)', amount: 24_000_000, direction: 'source', color: '#06b6d4' },
  { layer: 1, actor: 'Fight For Crypto ($15M)', amount: 15_000_000, direction: 'source', color: '#10b981' },
  { layer: 2, actor: 'Pro-Crypto Candidates', amount: 178_000_000, direction: 'flow', color: '#f97316' },
  { layer: 3, actor: 'FIT21 Act Passed (2025)', amount: 0, direction: 'regulatory_outcome', color: '#22c55e' },
  { layer: 3, actor: 'SEC Enforcement Halted', amount: 0, direction: 'regulatory_outcome', color: '#ef4444' },
  { layer: 3, actor: 'BITCOIN Act Proposed (Lummis)', amount: 0, direction: 'regulatory_outcome', color: '#a855f7' },
  // Layer 4: Outcomes
  { layer: 4, actor: 'Crypto Company Profits Surge', amount: 0, direction: 'outcome', color: '#22c55e' },
  { layer: 4, actor: 'Bitcoin to $200K+', amount: 0, direction: 'outcome', color: '#fbbf24' },
];

// ─── Entity Enrichment (for political-entities-v2.ts) ─────────────────────────

export const CRYPTO_ENTITY_ENRICHMENT: Record<string, EntityEnrichment> = {
  'Coinbase': {
    entity_name: 'Coinbase',
    aliases: ['Coinbase Global Inc', 'Coinbase Exchange'],
    connection_category: 'gop_donor',
    trump_pac_donors: [
      { name: 'Coinbase Global / Brian Armstrong', amount: 25_000_000, date: '2024', pac_name: 'Fairshake PAC (bipartisan)' },
    ],
    total_fec_contributions: 25_000_000,
    fec_source_urls: ['https://www.opensecrets.org/orgs/coinbase/summary'],
    total_lobbying_spend: 4_500_000,
    lobbying_source: 'https://www.opensecrets.org/orgs/coinbase/summary',
    registered_lobbyists: ['Coinbase Policy Team'],
    dark_money_connection: 'Fairshake PAC is a super PAC — not required to disclose all donors.',
    dark_money_source: 'https://www.opensecrets.org/political-action-committees-pacs/fairshake-pac/summary',
    news_investigations: [
      { headline: 'Coinbase Political Donations Under Scrutiny After SEC Settlement', outlet: 'The Guardian', date: '2025-01', url: 'https://www.theguardian.com/finance/2025/01/coinbase-political-donations-scrutiny' },
    ],
    mar_a_lago_visits: null,
    doge_role: null,
    trump_property_meetings: false,
    inauguration_host: false,
    wikipedia_url: 'https://en.wikipedia.org/wiki/Coinbase',
    opensecrets_url: 'https://www.opensecrets.org/orgs/coinbase/summary',
    fec_main_page: null,
  },
  'MicroStrategy': {
    entity_name: 'MicroStrategy',
    aliases: ['MSTR', 'MicroStrategy Inc'],
    connection_category: 'trump_ally',
    trump_pac_donors: [
      { name: 'Michael Saylor', amount: 250_000, date: '2024-2025', pac_name: 'Fairshake PAC (bipartisan) + personal donations' },
    ],
    total_fec_contributions: 250_000,
    fec_source_urls: ['https://www.opensecrets.org/politicians/michael-saylor/summary'],
    total_lobbying_spend: 500_000,
    lobbying_source: 'https://www.opensecrets.org/orgs/microstrategy/summary',
    registered_lobbyists: ['MicroStrategy Government Affairs'],
    dark_money_connection: null,
    dark_money_source: null,
    news_investigations: [
      { headline: 'Michael Saylor Met with Trump Officials on Bitcoin Reserve Strategy', outlet: 'Reuters', date: '2025-03', url: 'https://www.reuters.com/crypto/michael-saylor-met-trump-officials-bitcoin-reserve-2025-03' },
      { headline: 'Saylor\'s Bitcoin Bet Pays Off as MSTR Stock Surges 400%', outlet: 'Bloomberg', date: '2025-04', url: 'https://www.bloomberg.com/markets/microstrategy-bitcoin-surge' },
    ],
    mar_a_lago_visits: null,
    doge_role: null,
    trump_property_meetings: true,
    inauguration_host: false,
    wikipedia_url: 'https://en.wikipedia.org/wiki/MicroStrategy',
    opensecrets_url: 'https://www.opensecrets.org/orgs/microstrategy/summary',
    fec_main_page: null,
  },
  'Cynthia Lummis': {
    entity_name: 'Cynthia Lummis',
    aliases: ['Senator Cynthia Lummis', 'Cyndi Lummis'],
    connection_category: 'trump_ally',
    trump_pac_donors: [],
    total_fec_contributions: 0,
    fec_source_urls: [],
    total_lobbying_spend: 0,
    lobbying_source: 'N/A',
    registered_lobbyists: [],
    dark_money_connection: 'BITCOIN Act — proposes federal government purchase 5% of Bitcoin reserves',
    dark_money_source: 'https://www.congress.gov/bill/118th-congress/s/3312',
    news_investigations: [
      { headline: 'Lummis Bitcoin Holdings Disclosed — Up to $150K in BTC and ETH', outlet: 'OpenSecrets', date: '2025-02', url: 'https://www.opensecrets.org/politicians/cynthia-lummis/summary' },
    ],
    mar_a_lago_visits: null,
    doge_role: null,
    trump_property_meetings: false,
    inauguration_host: false,
    wikipedia_url: 'https://en.wikipedia.org/wiki/Cynthia_Lummis',
    opensecrets_url: 'https://www.opensecrets.org/politicians/cynthia-lummis/summary',
    fec_main_page: 'https://www.fec.gov/data/receipts/individual-contributions/?contributor_name=Cynthia+Lummis',
  },


// Trump Family Crypto Ventures — researched May 2026
// Sources: Wikipedia/WLFI, Forbes, Guardian, Washington Post, FT, Reuters

'World Liberty Financial': {
  entity_name: 'World Liberty Financial (WLFI)',
  entity_type: 'crypto_venture',
  aliases: ['World Liberty Financial Inc.', 'WLF', 'WLFI', 'World Liberty Trust'],
  connection_category: 'trump_family',
  trump_pac_donors: [],
  total_fec_contributions: 0,
  fec_source_urls: [],
  total_lobbying_spend: 0,
  lobbying_source: 'N/A',
  registered_lobbyists: [],
  dark_money_connection: 'Trump family receives 75% of net proceeds when WLFI sells tokens + cut of stablecoin profits. By Dec 2025, Trumps profited $1B on proceeds while holding $3B in unsold tokens.',
  dark_money_source: 'https://en.wikipedia.org/wiki/World_Liberty_Financial',
  news_investigations: [
    { headline: 'Trump Family WLFI Token Debuts 5-15x Above Early Sale Prices', outlet: 'Forbes', date: '2025-09-02', url: 'https://www.forbes.com/sites/zacheverson/2025/09/02/trump-crypto-token-wlfi-world-liberty-financial/' },
    { headline: "Trump's crypto firm raised $52M - likely sending millions to his family", outlet: 'Reuters', date: '2025-07-11', url: 'https://www.reuters.com' },
  ],
  mar_a_lago_visits: null,
  doge_role: null,
  trump_property_meetings: false,
  inauguration_host: false,
  wikipedia_url: 'https://en.wikipedia.org/wiki/World_Liberty_Financial',
  opensecrets_url: '',
  fec_main_page: '',
  wlfi_role: 'Co-founder emeritus (Donald Trump), Co-founders (Don Jr., Eric, Barron)',
  wlfi_founder_names: ['Zachary Folkman', 'Chase Herro', 'Alex Witkoff', 'Zach Witkoff'],
  wlfi_token_price_launch: '$0.015 (seed round)',
  wlfi_token_price_public: '$0.21-$0.31 (Sept 2025 debut)',
  wlfi_market_cap_peak: '~$25B at $0.25 per token (100B total supply)',
  wlfi_trump_family_stake: '22.5B WLFI tokens to DT Marks DEFI LLC (Trump owns 70%)',
  wlfi_proceeds_to_trump: '75% of net proceeds when WLFI sells tokens',
  wlfi_total_raised: '$550M+ (public sale)',
  wlfi_profit_to_trump: '$1B profit by Dec 2025 + $3B unsold tokens',
  wlfi_notable_investors: [
    { name: 'Justin Sun', amount: '$30M+ invested Feb 2025', role: 'WLFI Advisor, Tron founder', detail: 'SEC investigation dropped weeks after his $30M investment. Had been under SEC investigation for fraud.' },
    { name: 'MGX / Tahnoun bin Zayed (Abu Dhabi royal family)', amount: '$2B USD1 stablecoin + $500M for 49% stake', role: 'Foreign sovereign investor', detail: "Deal triggered Trump admin approving advanced chips for UAE company despite China security concerns. Potential emoluments clause violation." },
  ],
  wlfi_stablecoin_usd1: 'USD1 - dollar-pegged stablecoin backed by US treasuries, launched March 2025. Integrated into Tron (Justin Sun). Abu Dhabi used $2B of USD1 for Binance deal.',
  wlfi_banking_license: 'World Liberty Trust applied for national banking license Jan 2026 - would allow issuing/safeguarding USD1',
  wlfi_pakistan_deal: 'Jan 2026 - Pakistan signed with SC Financial (WLFI affiliate) to explore USD1 for cross-border payments',
  wlfi_conflicts: [
    'Justin Sun SEC investigation dropped weeks after $30M WLFI investment',
    'Abu Dhabi $2B deal + 49% stake - potential emoluments clause violation',
    'Trump approved advanced chip exports to UAE company linked to same deal',
    'WLFI never disclosed Tahnoun 49% stake purchase publicly',
    'Binance founder Zhao pardoned after Binance helped enrich WLFI',
  ],
},

'Donald Trump Jr. - WLFI': {
  entity_name: 'Donald Trump Jr. (World Liberty Financial)',
  aliases: ['Don Jr.', 'DT Jr.'],
  connection_category: 'trump_family',
  trump_pac_donors: [],
  total_fec_contributions: 0,
  fec_source_urls: [],
  total_lobbying_spend: 0,
  lobbying_source: 'N/A',
  registered_lobbyists: [],
  dark_money_connection: 'Co-founder of World Liberty Financial. Receives share of 75% family proceeds from WLFI token sales. WLFI raised $550M+. Trump family had $1B profit by Dec 2025.',
  dark_money_source: 'https://en.wikipedia.org/wiki/World_Liberty_Financial',
  news_investigations: [],
  mar_a_lago_visits: null,
  doge_role: null,
  trump_property_meetings: false,
  inauguration_host: false,
  wikipedia_url: 'https://en.wikipedia.org/wiki/Donald_Trump_Jr.',
  opensecrets_url: '',
  fec_main_page: '',
  wlfi_role: 'Co-founder of World Liberty Financial',
},

'Donald Trump - WLFI': {
  entity_name: 'Donald Trump (World Liberty Financial)',
  aliases: ['President Trump', 'DJT'],
  connection_category: 'trump_family',
  trump_pac_donors: [],
  total_fec_contributions: 0,
  fec_source_urls: [],
  total_lobbying_spend: 0,
  lobbying_source: 'N/A',
  registered_lobbyists: [],
  dark_money_connection: "Co-founder emeritus of World Liberty Financial. Receives 70% of DT Marks DEFI LLC (22.5B WLFI tokens). 75% of all net WLFI proceeds flow to Trump family. $57.4M reported on financial disclosure (12 months ending Dec 2024). Had $1B profit by Dec 2025.",
  dark_money_source: 'https://en.wikipedia.org/wiki/World_Liberty_Financial; https://www.forbes.com/sites/zacheverson/2025/06/14/trump-world-liberty-financial-crypto-earnings-financial-disclosure/',
  news_investigations: [
    { headline: 'Trump family WLFI wealth boosted by $5 billion', outlet: 'CBS News', date: '2025-09', url: 'https://www.cbsnews.com/news/trump-wlfi-world-liberty-financial-crypto-wealth/' },
  ],
  mar_a_lago_visits: null,
  doge_role: null,
  trump_property_meetings: false,
  inauguration_host: false,
  wikipedia_url: 'https://en.wikipedia.org/wiki/Donald_Trump',
  opensecrets_url: '',
  fec_main_page: '',
  wlfi_role: 'Co-founder emeritus',
  wlfi_token_holdings: '70% of DT Marks DEFI LLC (22.5B of 100B total WLFI tokens)',
  wlfi_financial_disclosure: '$57.4M reported earnings from WLFI',
},

'$TRUMP (Trump MemeCoin)': {
  entity_name: '$TRUMP - Trump MemeCoin',
  aliases: ['TRUMP coin', 'Official Trump coin'],
  connection_category: 'trump_family',
  trump_pac_donors: [],
  total_fec_contributions: 0,
  fec_source_urls: [],
  total_lobbying_spend: 0,
  lobbying_source: 'N/A',
  registered_lobbyists: [],
  dark_money_connection: 'MemeCoin launched by Trump hours before Jan 2025 inauguration. Peak $45.47. Chainalysis: 58 early investors each made $10M+ while ~764,000 smaller holders lost. Classic pump-and-dump.',
  dark_money_source: 'https://www.washingtonpost.com/technology/2025/05/08/trump-coin-crypto-investors-wallets/; https://www.theguardian.com/us-news/2025/oct/23/melania-trump-cryptocurrency-lawsuit',
  news_investigations: [
    { headline: 'Inside the Trump coin gold rush: 58 early investors made $10M+ each as 764,000 small holders lost out', outlet: 'Washington Post', date: '2025-05-08', url: 'https://www.washingtonpost.com/technology/2025/05/08/trump-coin-crypto-investors-wallets/' },
    { headline: 'Trump meme coin drops sharply as crypto traders rush to sell', outlet: 'Reuters', date: '2025-01-20', url: 'https://www.reuters.com' },
  ],
  mar_a_lago_visits: null,
  doge_role: null,
  trump_property_meetings: false,
  inauguration_host: false,
  wikipedia_url: '',
  opensecrets_url: '',
  fec_main_page: '',
  memecoin_launch_date: 'January 2025 (hours before inauguration)',
  memecoin_peak_price: '$45.47',
  memecoin_price_may2026: '~$5.79',
  memecoin_early_investors: '58 wallets each made $10M+ (Chainalysis)',
  memecoin_retail_losses: '~764,000 smaller holders lost money (Chainalysis)',
  memecoin_pump_dump_pattern: 'Insiders sold within hours of launch. Price crashed from $45 to ~$5 within weeks.',
},

'$MELANIA (Melania Coin)': {
  entity_name: '$MELANIA - Melania Trump MemeCoin',
  aliases: ['Melania coin', 'MELANIA'],
  connection_category: 'trump_family',
  trump_pac_donors: [],
  total_fec_contributions: 0,
  fec_source_urls: [],
  total_lobbying_spend: 0,
  lobbying_source: 'N/A',
  registered_lobbyists: [],
  dark_money_connection: 'MemeCoin launched Jan 19 2025 by Melania Trump (day before inauguration), peaked at $13.73 within hours. Federal lawsuit Oct 2025 accused Meteora exchange execs (Benjamin Chow, Hayden Davis) of pump-and-dump fraud - bought large quantities then quickly resold, crashing price to ~$0.10. Melania not named as defendant.',
  dark_money_source: 'https://www.theguardian.com/us-news/2025/oct/23/melania-trump-cryptocurrency-lawsuit; https://www.forbes.com/sites/alisondurkee/2025/10/22/melania-under-fire-first-ladys-memecoin-was-part-of-fraudulent-scheme-lawsuit-alleges-what-to-know/',
  news_investigations: [
    { headline: "Melania Trump's meme coin architects accused of pump-and-dump fraud", outlet: 'The Guardian', date: '2025-10-23', url: 'https://www.theguardian.com/us-news/2025/oct/23/melania-trump-cryptocurrency-lawsuit' },
    { headline: "Melania under fire: First lady's memecoin was part of fraudulent scheme", outlet: 'Forbes', date: '2025-10-22', url: 'https://www.forbes.com/sites/alisondurkee/2025/10/22/melania-under-fire-first-ladys-memecoin-was-part-of-fraudulent-scheme-lawsuit-alleges-what-to-know/' },
  ],
  mar_a_lago_visits: null,
  doge_role: null,
  trump_property_meetings: false,
  inauguration_host: false,
  wikipedia_url: '',
  opensecrets_url: '',
  fec_main_page: '',
  memecoin_launch_date: 'January 19 2025 (day before inauguration)',
  memecoin_peak_price: '$13.73',
  memecoin_price_oct2025: '~$0.10 (< 1% of peak)',
  memecoin_creators: 'Meteora exchange platform executives (Benjamin Chow, Hayden Davis - per lawsuit)',
  memecoin_fraud_allegation: "Pump-and-dump: insiders bought large quantities, quickly resold at profit, price crashed from $13.73 to ~$0.10. Plaintiffs: Melania used as 'window dressing'",
  memecoin_trump_family_profit: 'Trump family made $1B+ from ALL crypto products in 12 months (FT)',
},

'Justin Sun - WLFI': {
  entity_name: 'Justin Sun (WLFI Advisor / Tron Founder)',
  aliases: ['Sun', 'Tron', 'TRX'],
  connection_category: 'trump_ally',
  trump_pac_donors: [],
  total_fec_contributions: 0,
  fec_source_urls: [],
  total_lobbying_spend: 0,
  lobbying_source: 'N/A',
  registered_lobbyists: [],
  dark_money_connection: 'Crypto billionaire who invested $30M+ in WLFI and was named WLFI advisor Feb 2025. Weeks later, SEC investigation into his companies was dropped. Founder of Tron blockchain (WLFI USD1 integrated into Tron). TRX token surged on news.',
  dark_money_source: 'https://en.wikipedia.org/wiki/World_Liberty_Financial; https://www.forbes.com/sites/zacheverson/2025/06/17/president-trumps-crypto-firm-expands-relationship-with-embattled-blockchain-billionaire/',
  news_investigations: [
    { headline: "Trump's crypto firm expands relationship with embattled blockchain billionaire", outlet: 'Forbes', date: '2025-06-17', url: 'https://www.forbes.com/sites/zacheverson/2025/06/17/president-trumps-crypto-firm-expands-relationship-with-embattled-blockchain-billionaire/' },
  ],
  mar_a_lago_visits: null,
  doge_role: null,
  trump_property_meetings: false,
  inauguration_host: false,
  wikipedia_url: 'https://en.wikipedia.org/wiki/Justin_Sun',
  opensecrets_url: '',
  fec_main_page: '',
  wlfi_investment: '$30M+ invested in WLFI (Feb 2025)',
  wlfi_role_detail: 'Named WLFI advisor. SEC investigation dropped weeks after investment.',
  wlfi_usd1_integration: 'WLFI USD1 stablecoin integrated into Tron blockchain',
  sec_investigation: 'SEC had been investigating Sun for fraud/securities manipulation. Case dropped Feb 2025 after WLFI investment.',
},

'Zach Witkoff - WLFI': {
  entity_name: 'Zach Witkoff (WLFI Co-Founder)',
  aliases: ['Zach', 'Witkoff'],
  connection_category: 'trump_ally',
  trump_pac_donors: [],
  total_fec_contributions: 0,
  fec_source_urls: [],
  total_lobbying_spend: 0,
  lobbying_source: 'N/A',
  registered_lobbyists: [],
  dark_money_connection: 'Co-founder of World Liberty Financial. President and chairman of World Liberty Trust (applied for national banking license Jan 2026). Met with Binance founder Changpeng Zhao in Abu Dhabi. Son of Steve Witkoff (Trump ally who met with Putin Jan 2025 and became US diplomat).',
  dark_money_source: 'https://en.wikipedia.org/wiki/World_Liberty_Financial',
  news_investigations: [],
  mar_a_lago_visits: null,
  doge_role: null,
  trump_property_meetings: false,
  inauguration_host: false,
  wikipedia_url: 'https://en.wikipedia.org/wiki/Zach_Witkoff',
  opensecrets_url: '',
  fec_main_page: '',
  wlfi_role: 'Co-founder, President of World Liberty Trust',
  wlfi_banking_license: 'Applied for national banking license Jan 2026 on behalf of World Liberty Trust',
  witkoff_family: 'Son of Steve Witkoff - Trump ally who met Putin and became US diplomat',
},

'Alex Witkoff - WLFI': {
  entity_name: 'Alex Witkoff (WLFI Co-Founder)',
  aliases: ['Alex'],
  connection_category: 'trump_ally',
  trump_pac_donors: [],
  total_fec_contributions: 0,
  fec_source_urls: [],
  total_lobbying_spend: 0,
  lobbying_source: 'N/A',
  registered_lobbyists: [],
  dark_money_connection: 'Co-founder of World Liberty Financial (alongside brother Zach Witkoff). Steve Witkoff is their father - Trump ally who met Putin privately Jan 2025 and became US diplomat. Family embedded in both Trump orbit AND WLFI.',
  dark_money_source: 'https://en.wikipedia.org/wiki/World_Liberty_Financial',
  news_investigations: [],
  mar_a_lago_visits: null,
  doge_role: null,
  trump_property_meetings: false,
  inauguration_host: false,
  wikipedia_url: 'https://en.wikipedia.org/wiki/Alex_Witkoff',
  opensecrets_url: '',
  fec_main_page: '',
  wlfi_role: 'Co-founder of World Liberty Financial',
},

'Steve Witkoff - WLFI Family': {
  entity_name: 'Steve Witkoff (Trump Ally / Putin Meeting)',
  aliases: ['Steven Witkoff', 'Steve Witkoff'],
  connection_category: 'trump_ally',
  trump_pac_donors: [],
  total_fec_contributions: 0,
  fec_source_urls: [],
  total_lobbying_spend: 0,
  lobbying_source: 'N/A',
  registered_lobbyists: [],
  dark_money_connection: 'Trump ally who met privately with Putin in Jan 2025 (before taking office). Became US diplomat (special envoy). Father of Zach and Alex Witkoff - both WLFI co-founders. Creates direct conflict: Trump admin approves chip exports to UAE (linked to WLFI Abu Dhabi deal) while Steve Witkoff sons run WLFI.',
  dark_money_source: 'https://en.wikipedia.org/wiki/World_Liberty_Financial; https://en.wikipedia.org/wiki/Steve_Witkoff',
  news_investigations: [
    { headline: 'Steve Witkoff met with Putin before taking office', outlet: 'Wikipedia', date: '2025-01', url: 'https://en.wikipedia.org/wiki/Steve_Witkoff' },
  ],
  mar_a_lago_visits: null,
  doge_role: null,
  trump_property_meetings: true,
  inauguration_host: false,
  wikipedia_url: 'https://en.wikipedia.org/wiki/Steve_Witkoff',
  opensecrets_url: '',
  fec_main_page: '',
  wlfi_family_connection: 'Father of Zach Witkoff and Alex Witkoff (WLFI co-founders)',
},

'Zachary Folkman - WLFI': {
  entity_name: 'Zachary Folkman (WLFI Co-Founder)',
  aliases: ['Zach Folkman'],
  connection_category: 'trump_ally',
  trump_pac_donors: [],
  total_fec_contributions: 0,
  fec_source_urls: [],
  total_lobbying_spend: 0,
  lobbying_source: 'N/A',
  registered_lobbyists: [],
  dark_money_connection: 'Co-founder of World Liberty Financial (2024). One of four original founders alongside Chase Herro and the Witkoff brothers.',
  dark_money_source: 'https://en.wikipedia.org/wiki/World_Liberty_Financial',
  news_investigations: [],
  mar_a_lago_visits: null,
  doge_role: null,
  trump_property_meetings: false,
  inauguration_host: false,
  wikipedia_url: '',
  opensecrets_url: '',
  fec_main_page: '',
  wlfi_role: 'Co-founder of World Liberty Financial',
},

'Chase Herro - WLFI': {
  entity_name: 'Chase Herro (WLFI Co-Founder)',
  aliases: ['Chase'],
  connection_category: 'trump_ally',
  trump_pac_donors: [],
  total_fec_contributions: 0,
  fec_source_urls: [],
  total_lobbying_spend: 0,
  lobbying_source: 'N/A',
  registered_lobbyists: [],
  dark_money_connection: 'Co-founder of World Liberty Financial (2024). One of four original founders alongside Folkman and the Witkoff brothers.',
  dark_money_source: 'https://en.wikipedia.org/wiki/World_Liberty_Financial',
  news_investigations: [],
  mar_a_lago_visits: null,
  doge_role: null,
  trump_property_meetings: false,
  inauguration_host: false,
  wikipedia_url: '',
  opensecrets_url: '',
  fec_main_page: '',
  wlfi_role: 'Co-founder of World Liberty Financial',
},

'Benjamin Chow - MELANIA': {
  entity_name: 'Benjamin Chow (Meteora Exchange)',
  aliases: ['Ben Chow', 'B. Chow'],
  connection_category: 'trump_ally',
  trump_pac_donors: [],
  total_fec_contributions: 0,
  fec_source_urls: [],
  total_lobbying_spend: 0,
  lobbying_source: 'N/A',
  registered_lobbyists: [],
  dark_money_connection: 'Executive at Meteora exchange (where $MELANIA launched). Named as defendant in federal lawsuit Oct 2025 alleging pump-and-dump fraud. Allegedly bought large quantities of $MELANIA then quickly resold, causing price crash from $13.73 to <$0.10.',
  dark_money_source: 'https://www.forbes.com/sites/alisondurkee/2025/10/22/melania-under-fire-first-ladys-memecoin-was-part-of-fraudulent-scheme-lawsuit-alleges-what-to-know/',
  news_investigations: [
    { headline: 'Melania under fire: First lady memecoin was part of fraudulent scheme', outlet: 'Forbes', date: '2025-10-22', url: 'https://www.forbes.com/sites/alisondurkee/2025/10/22/melania-under-fire-first-ladys-memecoin-was-part-of-fraudulent-scheme-lawsuit-alleges-what-to-know/' },
  ],
  mar_a_lago_visits: null,
  doge_role: null,
  trump_property_meetings: false,
  inauguration_host: false,
  wikipedia_url: '',
  opensecrets_url: '',
  fec_main_page: '',
  melania_involvement: 'Defendant in pump-and-dump lawsuit (Meteora exchange exec)',
},

'Hayden Davis - MELANIA': {
  entity_name: 'Hayden Davis (Meteora Exchange)',
  aliases: ['H. Davis'],
  connection_category: 'trump_ally',
  trump_pac_donors: [],
  total_fec_contributions: 0,
  fec_source_urls: [],
  total_lobbying_spend: 0,
  lobbying_source: 'N/A',
  registered_lobbyists: [],
  dark_money_connection: 'Executive at Meteora exchange (where $MELANIA launched). Co-named defendant with Benjamin Chow in Oct 2025 federal lawsuit alleging pump-and-dump fraud. Allegedly orchestrated scheme to buy large quantities at launch and quickly resell.',
  dark_money_source: 'https://www.forbes.com/sites/alisondurkee/2025/10/22/melania-under-fire-first-ladys-memecoin-was-part-of-fraudulent-scheme-lawsuit-alleges-what-to-know/',
  news_investigations: [
    { headline: 'Melania under fire: First lady memecoin was part of fraudulent scheme', outlet: 'Forbes', date: '2025-10-22', url: 'https://www.forbes.com/sites/alisondurkee/2025/10/22/melania-under-fire-first-ladys-memecoin-was-part-of-fraudulent-scheme-lawsuit-alleges-what-to-know/' },
  ],
  mar_a_lago_visits: null,
  doge_role: null,
  trump_property_meetings: false,
  inauguration_host: false,
  wikipedia_url: '',
  opensecrets_url: '',
  fec_main_page: '',
  melania_involvement: 'Defendant in pump-and-dump lawsuit (Meteora exchange exec)',
},

'MGX - Tahnoun bin Zayed (Abu Dhabi)': {
  entity_name: 'MGX / Tahnoun bin Zayed Al Nahyan (Abu Dhabi Royal Family)',
  aliases: ['MGX', 'Tahnoun', 'UAE Royal Family'],
  connection_category: 'foreign_sovereign',
  trump_pac_donors: [],
  total_fec_contributions: 0,
  fec_source_urls: [],
  total_lobbying_spend: 0,
  lobbying_source: 'N/A',
  registered_lobbyists: [],
  dark_money_connection: "Abu Dhabi state investment vehicle led by UAE National Security Advisor Tahnoun bin Zayed Al Nahyan. Paid $2B for WLFI USD1 stablecoins + $500M for 49% stake in WLFI. Met with Binance founder Zhao in Abu Dhabi. Trump admin then approved advanced computer chips for Tahnoun-affiliated UAE company - potential emoluments clause violation. Never disclosed to public.",
  dark_money_source: 'https://en.wikipedia.org/wiki/World_Liberty_Financial',
  news_investigations: [
    { headline: 'MGX to use World Liberty USD1 in $2B Binance deal', outlet: 'Reuters', date: '2025-05', url: 'https://www.reuters.com' },
  ],
  mar_a_lago_visits: null,
  doge_role: null,
  trump_property_meetings: false,
  inauguration_host: false,
  wikipedia_url: 'https://en.wikipedia.org/wiki/Tahnoun_bin_Zayed_Al_Nahyan_(national_security_advisor)',
  opensecrets_url: '',
  fec_main_page: '',
  wlfi_investment: '$2B USD1 stablecoin purchase + $500M for 49% stake',
  wlfi_chip_deal: 'Trump admin approved hundreds of thousands of advanced chips for UAE company linked to Tahnoun weeks after Abu Dhabi deal',
  wlfi_conflict: 'National security risk flagged: chips could end up in China',
},

'Changpeng Zhao - Binance': {
  entity_name: 'Changpeng Zhao (Binance / Binance Founder)',
  aliases: ['CZ', 'Changpeng Zhao', 'Binance'],
  connection_category: 'trump_ally',
  trump_pac_donors: [],
  total_fec_contributions: 0,
  fec_source_urls: [],
  total_lobbying_spend: 0,
  lobbying_source: 'N/A',
  registered_lobbyists: [],
  dark_money_connection: 'Founder of Binance (world largest crypto exchange). Convicted of AML violations Nov 2023, sentenced to 4 months in prison. Pardon by Trump Jan 2025 - after Binance helped enrich World Liberty Financial (WLFI). Connected via Justin Sun (WLFI advisor, Tron founder). WLFI USD1 used in $2B Binance deal with Abu Dhabi.',
  dark_money_source: 'https://en.wikipedia.org/wiki/World_Liberty_Financial; https://en.wikipedia.org/wiki/Changpeng_Zhao',
  news_investigations: [
    { headline: 'Changpeng Zhao pardoned by Trump', outlet: 'Wikipedia', date: '2025-01', url: 'https://en.wikipedia.org/wiki/Changpeng_Zhao' },
  ],
  mar_a_lago_visits: null,
  doge_role: null,
  trump_property_meetings: false,
  inauguration_host: false,
  wikipedia_url: 'https://en.wikipedia.org/wiki/Changpeng_Zhao',
  opensecrets_url: '',
  fec_main_page: '',
  wlfi_connection: 'Binance listed WLFI and was used for WLFI USD1 $2B deal with MGX. Zhao pardoned Jan 2025 after Binance helped enrich WLFI.',
},

};
