// SlushFund — PAC Donation Database 2016–2026
// Sources: OpenSecrets, FEC.gov, CRP, news investigations
// Tracks White House, Senate, House PAC donations with full funding chain

export interface PACDonation {
  pac_name: string;
  abbr: string;
  committee_id?: string; // FEC committee ID — enables live "FEC verified" totals
  type: 'super_pac' | 'pac' | 'leadership_pac' | 'dark_money' | 'joint_fundraising';
  connected_to: 'trump_ally' | 'democrat' | 'republican' | 'bipartisan' | 'progressive' | 'conservative' | 'crypto' | 'defense' | 'tech' | 'finance' | 'koch' | 'arabella' | 'musk' | 'gop_dark_money' | 'other';
  founding_year: number;
  total_raised_2016_2024: number; // in dollars
  raised_2024_cycle: number;
  source_org: string; // parent company or org
  founders: string[]; // key people
  primary_funders: { name: string; amount_range: string; connection: string }[];
  top_recipients: { name: string; office: 'white_house' | 'senate' | 'house' | 'rnc' | 'dnc' | 'joint'; party: 'R' | 'D' | 'B'; amount: number }[];
  spending_2016_2024: number;
  political_ads_spent: number;
  affiliated_entities: string[]; // sister orgs, linked PACs
  connection_to_trump: string;
  connection_to_congress: string;
  oversight_targets: string[]; // committees or agencies
  funder_chain?: string; // how money is routed: original donor → pass-through → super PAC
  // Race-by-race independent expenditures — money spent FOR or AGAINST a
  // specific candidate, independent of their campaign (super PAC activity).
  independent_expenditures?: {
    race: string;                          // e.g. "NY-16"
    cycle: string;                         // e.g. "2024"
    candidate: string;                     // candidate the spend concerns
    party: 'R' | 'D' | 'B';
    support_or_oppose: 'support' | 'oppose';
    amount: number;
    outcome?: string;                      // result of the race
  }[];
  source_urls?: string[]; // citations for funding claims
  notes: string;
}

export interface PACNode {
  id: string;
  name: string;
  abbr: string;
  type: 'super_pac' | 'pac' | 'dark_money' | 'trump' | 'koch' | 'arabella' | 'musk' | 'crypto' | 'defense' | 'tech' | 'finance';
  size: number; // for network graph — proportional to total raised
  raised: number;
  spent: number;
  color: string;
}

export interface PACEdge {
  source: string;
  target: string;
  label: string;
  weight: number; // 1-5
  type: 'funds' | 'affiliated' | 'joint_fundraising' | 'shares_donors';
}

// ─── Core PAC Database ─────────────────────────────────────────────────────────

export const PAC_DATABASE: PACDonation[] = [
  // ─── PRO-ISRAEL / AIPAC NETWORK ──────────────────────────────────────────────
  {
    pac_name: 'American Israel Public Affairs Committee PAC',
    abbr: 'AIPAC PAC',
    committee_id: 'C00113146',
    type: 'pac',
    connected_to: 'bipartisan',
    founding_year: 1963,
    total_raised_2016_2024: 320_000_000,
    raised_2024_cycle: 85_000_000,
    source_org: 'AIPAC',
    founders: ['AIPAC membership'],
    primary_funders: [
      { name: 'Individual AIPAC members', amount_range: '$100K–$1M+ each', connection: 'Bundled through PAC conduit' },
      { name: 'Pro-Israel Hedge Funds & Finance', amount_range: '~$30M', connection: 'Wall Street donors bundled via AIPAC' },
      { name: 'Real Estate / Property', amount_range: '~$20M', connection: 'NY/NJ real estate magnates' },
    ],
    top_recipients: [
      { name: 'Josh Gottheimer (D-NJ)', office: 'house', party: 'D', amount: 6_700_000 },
      { name: 'Brad Schneider (D-IL)', office: 'house', party: 'D', amount: 6_700_000 },
      { name: 'Shontel Brown (D-OH)', office: 'house', party: 'D', amount: 6_600_000 },
      { name: 'Chuck Schumer (D-NY)', office: 'senate', party: 'D', amount: 6_500_000 },
      { name: 'Ted Cruz (R-TX)', office: 'senate', party: 'R', amount: 6_100_000 },
      { name: 'Lindsey Graham (R-SC)', office: 'senate', party: 'R', amount: 4_600_000 },
      { name: 'Elissa Slotkin (D-MI)', office: 'senate', party: 'D', amount: 4_500_000 },
      { name: 'Jacky Rosen (D-NV)', office: 'senate', party: 'D', amount: 7_600_000 },
    ],
    spending_2016_2024: 310_000_000,
    political_ads_spent: 80_000_000,
    affiliated_entities: ['United Democracy Project (UDP)', 'Democratic Majority for Israel (DMFI)', 'Republican Jewish Coalition (RJC)'],
    connection_to_trump: 'Bipartisan — supports Trump-aligned Republicans AND Democrats who vote pro-Israel',
    connection_to_congress: 'In the 2024 cycle AIPAC PAC donated over $55.2M directly to federal candidates — at least $45.2M of it to members of the 119th Congress — making it the most broadly funded PAC in US politics. AIPAC PAC operates as a conduit: individual members earmark donations that AIPAC bundles to candidates.',
    oversight_targets: ['House Foreign Affairs Committee', 'Senate Foreign Relations Committee', 'Armed Services Committee'],
    source_urls: [
      'https://www.fec.gov/data/committee/C00113146/',
      'https://readsludge.com/2025/01/24/here-is-all-the-money-aipac-spent-on-the-2024-elections/',
      'https://www.opensecrets.org/political-action-committees-pacs/c00113146/summary/2024',
    ],
    notes: 'AIPAC is the most influential pro-Israel lobby in Washington. Its conduit PAC (FEC C00113146) routed over $55.2M to federal candidates in the 2023-2024 cycle. Combined with its super PAC arm UDP, the AIPAC network spent roughly $126.9M in 2024 — among the largest single-cycle PAC operations in US history. AIPAC funds candidates in both parties who support US-Israel security cooperation.',
  },
  {
    pac_name: 'United Democracy Project',
    abbr: 'UDP',
    committee_id: 'C00799031',
    type: 'super_pac',
    connected_to: 'bipartisan',
    founding_year: 2022,
    total_raised_2016_2024: 117_000_000,
    raised_2024_cycle: 87_000_000,
    source_org: 'AIPAC',
    founders: ['AIPAC leadership'],
    primary_funders: [
      { name: 'Jan Koum', amount_range: '$5M', connection: 'WhatsApp co-founder — single largest disclosed UDP donor in 2024' },
      { name: 'Jonathan Jacobson', amount_range: '$4.6M', connection: 'Hedge fund financier, founder of Highfields Capital' },
      { name: 'Bernard Marcus', amount_range: '$3M', connection: 'Home Depot co-founder and Republican mega-donor' },
      { name: 'David Zalik', amount_range: '$2M', connection: 'GreenSky CEO' },
      { name: 'Additional billionaire donors', amount_range: '~$45M', connection: 'More than a dozen seven-figure donors; AIPAC PAC itself routed ~$8.6M into UDP' },
    ],
    top_recipients: [
      { name: 'George Latimer (D-NY) — defeated AOC', office: 'house', party: 'D', amount: 22_700_000 },
      { name: 'Wesley Bell (D-MO) — defeated Cori Bush', office: 'house', party: 'D', amount: 16_900_000 },
      { name: 'Josh Gottheimer (D-NJ)', office: 'house', party: 'D', amount: 6_700_000 },
      { name: 'Adam Schiff (D-CA) — Senate primary', office: 'senate', party: 'D', amount: 9_600_000 },
      { name: 'Haley Stevens (D-MI)', office: 'house', party: 'D', amount: 9_100_000 },
      { name: 'Glenn Ivey (D-MD)', office: 'house', party: 'D', amount: 8_200_000 },
    ],
    spending_2016_2024: 215_000_000,
    political_ads_spent: 195_000_000,
    affiliated_entities: ['AIPAC PAC', 'DMFI', 'RJC', ' AIPAC bundling network'],
    connection_to_trump: 'Bipartisan super PAC — primarily targets Democratic primaries to unseat progressives',
    connection_to_congress: 'In 2024, spent $61M on independent expenditures — mostly in Democratic primaries against candidates deemed insufficiently pro-Israel. Has targeted AOC, Cori Bush, Ilhan Omar, Rashida Tlaib.',
    oversight_targets: [],
    funder_chain: 'UDP is AIPAC\'s super PAC arm. Donors — including AIPAC PAC itself, which routed roughly $8.6M into UDP — give unlimited checks to UDP, which then spends primarily on independent-expenditure ads, often against progressive primary challengers. The ads largely avoid mentioning Israel, instead attacking targets on unrelated issues.',
    independent_expenditures: [
      { race: 'NY-16', cycle: '2024', candidate: 'Jamaal Bowman', party: 'D', support_or_oppose: 'oppose', amount: 9_900_000, outcome: 'Bowman lost the Democratic primary' },
      { race: 'NY-16', cycle: '2024', candidate: 'George Latimer', party: 'D', support_or_oppose: 'support', amount: 4_800_000, outcome: 'Latimer won the primary — most expensive House primary in history' },
      { race: 'MO-01', cycle: '2024', candidate: 'Cori Bush', party: 'D', support_or_oppose: 'oppose', amount: 5_200_000, outcome: 'Bush lost the Democratic primary' },
      { race: 'MO-01', cycle: '2024', candidate: 'Wesley Bell', party: 'D', support_or_oppose: 'support', amount: 3_300_000, outcome: 'Bell won the primary' },
      { race: 'CA-47', cycle: '2024', candidate: 'Dave Min', party: 'D', support_or_oppose: 'oppose', amount: 4_600_000, outcome: 'Min won the primary and the general election' },
      { race: 'Multiple GOP House primaries', cycle: '2024', candidate: '4 Republican House candidates (incl. John Hostettler, Rep. Bob Good)', party: 'R', support_or_oppose: 'oppose', amount: 3_000_000, outcome: 'Hostettler and Good both lost their races' },
    ],
    source_urls: [
      'https://www.fec.gov/data/committee/C00799031/',
      'https://www.factcheck.org/2024/09/united-democracy-project-2/',
      'https://www.opensecrets.org/political-action-committees-pacs/united-democracy-project/C00799031/independent-expenditures/2024',
      'https://readsludge.com/2025/01/24/here-is-all-the-money-aipac-spent-on-the-2024-elections/',
    ],
    notes: 'UDP is AIPAC\'s most aggressive political weapon. In the 2024 cycle it disbursed roughly $61M — including ~$37.9M of independent expenditures in House races and ~$8.6M passed to other PACs. Its signature tactic is funding primary challengers against progressive Democrats who criticize Israeli government policy: in 2024 it spent ~$14.7M in NY-16 to defeat Jamaal Bowman and ~$8.5M in MO-01 to defeat Cori Bush.',
  },
  {
    pac_name: 'Democratic Majority for Israel',
    abbr: 'DMFI',
    committee_id: 'C00688857',
    type: 'super_pac',
    connected_to: 'democrat',
    founding_year: 2019,
    total_raised_2016_2024: 65_000_000,
    raised_2024_cycle: 32_000_000,
    source_org: 'Democratic pro-Israel donors',
    founders: ['Mark Mellman', 'Deborah Sagner'],
    primary_funders: [
      { name: 'Haim Saban', amount_range: '$10M+', connection: 'Media mogul — longtime Dem donor' },
      { name: 'George S. Shapiro', amount_range: '$5M+', connection: 'Healthcare investor' },
      { name: 'Dina P. Harrison', amount_range: '$3M+', connection: 'Pro-Israel donor bundler' },
    ],
    top_recipients: [
      { name: 'Josh Gottheimer (D-NJ)', office: 'house', party: 'D', amount: 3_000_000 },
      { name: 'Jon Ossoff (D-GA)', office: 'senate', party: 'D', amount: 2_000_000 },
      { name: 'Elissa Slotkin (D-MI)', office: 'senate', party: 'D', amount: 2_000_000 },
      { name: 'Madeleine Dean (D-PA)', office: 'house', party: 'D', amount: 500_000 },
    ],
    spending_2016_2024: 60_000_000,
    political_ads_spent: 55_000_000,
    affiliated_entities: ['AIPAC PAC', 'UDP', 'J Street'],
    connection_to_trump: 'Dem-only — opposes candidates across party who deviate from pro-Israel platform',
    connection_to_congress: 'Democratic counterpart to AIPAC PAC — focused on maintaining strong US-Israel ties in Democratic caucus',
    oversight_targets: ['House Foreign Affairs Committee'],
    source_urls: [
      'https://www.fec.gov/data/committee/C00688857/',
      'https://www.opensecrets.org/political-action-committees-pacs/democratic-majority-for-israel/C00688857/summary/2024',
    ],
    notes: 'DMFI splits from AIPAC by being exclusively Democratic. Founded in 2019 over progressive stances within the party, it supports a two-state solution and has backed strong US-Israel security funding. Key distinction from UDP: DMFI primarily runs positive support ads rather than opposition research.',
  },
  {
    pac_name: 'Republican Jewish Coalition',
    abbr: 'RJC',
    committee_id: 'C00391294',
    type: 'super_pac',
    connected_to: 'republican',
    founding_year: 2000,
    total_raised_2016_2024: 80_000_000,
    raised_2024_cycle: 28_000_000,
    source_org: 'GOP Jewish donors',
    founders: ['Orthodox Jewish donors', 'GOP operatives'],
    primary_funders: [
      { name: 'Miriam Adelson', amount_range: '$30M+', connection: 'Primary funder — casino magnate' },
      { name: 'Stan Hirsch', amount_range: '$3M+', connection: 'Philanthropist' },
      { name: 'GOP mega-donors', amount_range: '~$15M', connection: 'Koch-adjacent + Trump-aligned' },
    ],
    top_recipients: [
      { name: 'Donald Trump', office: 'white_house', party: 'R', amount: 10_000_000 },
      { name: 'Lindsey Graham (R-SC)', office: 'senate', party: 'R', amount: 4_600_000 },
      { name: 'Ted Cruz (R-TX)', office: 'senate', party: 'R', amount: 6_100_000 },
      { name: 'Josh Hawley (R-MO)', office: 'senate', party: 'R', amount: 2_000_000 },
      { name: 'Elise Stefanik (R-NY)', office: 'house', party: 'R', amount: 1_500_000 },
    ],
    spending_2016_2024: 75_000_000,
    political_ads_spent: 68_000_000,
    affiliated_entities: ['AIPAC PAC', 'MAGA Inc', 'NRSC'],
    connection_to_trump: 'Pro-Trump — strong relationship since Trump moved US embassy to Jerusalem',
    connection_to_congress: 'GOP arm of pro-Israel funding — coordinates with AIPAC on bipartisan messaging',
    oversight_targets: [],
    source_urls: [
      'https://www.fec.gov/data/committee/C00391294/',
      'https://www.opensecrets.org/orgs/republican-jewish-coalition/summary',
    ],
    notes: 'The Republican counterpart to DMFI. RJC has deepened ties with Trump after his 2019 Jerusalem embassy move. In 2024, RJC spent $28M — $10M supporting Trump, rest on Senate/House Republicans. Key message: Republicans are now the more reliably pro-Israel party in terms of foreign policy votes, shifting the historic bipartisan consensus.',
  },
  {
    pac_name: 'J Street',
    abbr: 'JStreet',
    committee_id: 'C00446920',
    type: 'pac',
    connected_to: 'progressive',
    founding_year: 2008,
    total_raised_2016_2024: 40_000_000,
    raised_2024_cycle: 12_000_000,
    source_org: 'Progressive Jewish donors',
    founders: ['Jeremy Ben-Ami', 'Alan Solow'],
    primary_funders: [
      { name: 'Progressive Jewish families', amount_range: '~$10M', connection: 'Lower-dollar, broader donor base' },
      { name: 'New Israel Fund supporters', amount_range: '~$5M', connection: '2-state solution advocates' },
    ],
    top_recipients: [
      { name: 'Progressive candidates open to diplomacy', office: 'joint', party: 'D', amount: 8_000_000 },
      { name: 'Pro-diplomacy congressional Democrats', office: 'joint', party: 'D', amount: 3_000_000 },
    ],
    spending_2016_2024: 38_000_000,
    political_ads_spent: 20_000_000,
    affiliated_entities: ['J StreetPAC', 'New Israel Fund'],
    connection_to_trump: 'Opposes Trump administration\'s Israel policies',
    connection_to_congress: 'Counterweight to AIPAC — supports 2-state solution, opposes settlement expansion',
    oversight_targets: [],
    source_urls: [
      'https://www.fec.gov/data/committee/C00446920/',
      'https://www.opensecrets.org/political-action-committees-pacs/j-streetpac/C00446920/summary/2024',
    ],
    notes: 'J Street is the progressive alternative to AIPAC — backs diplomatic engagement (2-state solution) over military-first approach. Much smaller than AIPAC but growing. AIPAC\'s aggressive expansion has made J Street increasingly irrelevant in DC funding circles. Key distinction: J Street\'s candidates actually oppose some US military aid packages that AIPAC backs.',
  },
  // ─── TRUMP-ARM OF POLITICS ───────────────────────────────────────────────────
  {
    pac_name: 'America PAC',
    abbr: 'APAC',
    committee_id: 'C00879510',
    type: 'super_pac',
    connected_to: 'trump_ally',
    founding_year: 2024,
    total_raised_2016_2024: 290_000_000,
    raised_2024_cycle: 290_000_000,
    source_org: 'Trump allies',
    founders: ['Elon Musk', 'Miriam Adelson', 'Doug Burgum'],
    primary_funders: [
      { name: 'Elon Musk', amount_range: '$250M+', connection: 'Primary funder — personal contribution' },
      { name: 'Miriam Adelson', amount_range: '$100M+', connection: 'Casino magnate, Sheldon Adelson widow' },
      { name: 'Doug Burgum', amount_range: '$10M+', connection: 'CEO of Great Plains / Trump tech ally' },
    ],
    top_recipients: [
      { name: 'Donald Trump', office: 'white_house', party: 'R', amount: 250_000_000 },
      { name: 'Senate Republicans', office: 'senate', party: 'R', amount: 20_000_000 },
      { name: 'House Republicans', office: 'house', party: 'R', amount: 15_000_000 },
    ],
    spending_2016_2024: 285_000_000,
    political_ads_spent: 210_000_000,
    affiliated_entities: ['RNC', 'SAVE America PAC', 'RNC Joint Fundraising'],
    connection_to_trump: 'Direct Trump 2024 campaign arm — Musk personally delivered $250M+',
    connection_to_congress: 'Funding multiple Trump-aligned Senate/House candidates in tight races',
    oversight_targets: [],
    notes: 'Founded May 2024. Primary vehicle for Trump 2024. Musk used it as his main vehicle for Trump support.',
  },
  {
    pac_name: 'SAVE America PAC',
    abbr: 'SVAM',
    committee_id: 'C00762591',
    type: 'leadership_pac',
    connected_to: 'trump_ally',
    founding_year: 2021,
    total_raised_2016_2024: 150_000_000,
    raised_2024_cycle: 95_000_000,
    source_org: 'Trump personal',
    founders: ['Donald Trump'],
    primary_funders: [
      { name: 'Trump personal funds', amount_range: '$50M+', connection: 'Self-funding through properties' },
      { name: 'Small donors', amount_range: '$40M+', connection: 'Email fundraising list' },
      { name: 'Mega donors (Lara Trump network)', amount_range: '$30M+', connection: 'Bundled via daughter-in-law network' },
    ],
    top_recipients: [
      { name: 'Donald Trump', office: 'white_house', party: 'R', amount: 60_000_000 },
      { name: 'JD Vance (Sen-OH)', office: 'senate', party: 'R', amount: 5_000_000 },
      { name: 'Elise Stefanik (R-NY)', office: 'house', party: 'R', amount: 2_500_000 },
    ],
    spending_2016_2024: 140_000_000,
    political_ads_spent: 45_000_000,
    affiliated_entities: ['Make America Great Again Inc', 'Trump 2024'],
    connection_to_trump: "Trump's personal leadership PAC — used for travel, staff, and candidate support",
    connection_to_congress: 'Supports MAGA candidates in primaries and general elections',
    oversight_targets: [],
    notes: " Trump's main political vehicle post-2021. Receives travel budget and staff salary support. Used to keep Trump-connected candidates loyal.",
  },
  {
    pac_name: 'Senate Leadership Fund',
    abbr: 'SLF',
    committee_id: 'C00571703',
    type: 'super_pac',
    connected_to: 'republican',
    founding_year: 2016,
    total_raised_2016_2024: 980_000_000,
    raised_2024_cycle: 420_000_000,
    source_org: 'McConnell-aligned Senate Republicans',
    founders: ['Lindsey Graham', 'Roy Blunt', 'Mitch McConnell allies'],
    primary_funders: [
      { name: 'Dark money (unknown)', amount_range: '~$300M', connection: 'Donor identity undisclosed' },
      { name: 'Koch Industries', amount_range: '$50M+', connection: 'Americans for Prosperity network' },
      { name: 'Defense contractors', amount_range: '$50M+', connection: 'Lockheed, Raytheon, Northrop PACs' },
      { name: ' fossil fuel', amount_range: '$40M+', connection: 'API, fuel industry' },
    ],
    top_recipients: [
      { name: 'Josh Hammer (Sen-FL)', office: 'senate', party: 'R', amount: 20_000_000 },
      { name: 'Dave McCormick (Sen-PA)', office: 'senate', party: 'R', amount: 18_000_000 },
      { name: 'Bernie Moreno (Sen-OH)', office: 'senate', party: 'R', amount: 15_000_000 },
    ],
    spending_2016_2024: 950_000_000,
    political_ads_spent: 890_000_000,
    affiliated_entities: ['Congressional Leadership Fund', 'NRSC (joint)', 'MAGA Inc'],
    connection_to_trump: 'Alignment with Trump candidates but controlled by McConnell wing',
    connection_to_congress: 'Main Senate GOP super PAC — backs candidates in competitive races',
    oversight_targets: ['Senate Armed Services Committee', 'Senate Appropriations'],
    notes: 'Most influential Senate GOP super PAC. Coordinates with McConnell leadership. Has backed both Trump-skeptical and Trump-aligned candidates depending on political calculus.',
  },
  {
    pac_name: 'Make America Great Again Inc',
    abbr: 'MAGA Inc',
    committee_id: 'C00825851',
    type: 'super_pac',
    connected_to: 'trump_ally',
    founding_year: 2021,
    total_raised_2016_2024: 350_000_000,
    raised_2024_cycle: 200_000_000,
    source_org: 'Trump-aligned',
    founders: ['Taylor Budowich', 'Rebecca Chicone'],
    primary_funders: [
      { name: 'Timothy Mellon', amount_range: '$50M+', connection: 'Banking-dynasty heir — single largest disclosed MAGA Inc donor in 2024' },
      { name: 'Warren Stephens', amount_range: '$3M+', connection: 'Arkansas investment banker; later named Trump ambassador to the UK' },
      { name: 'Patrick & Anne Welsh / energy-sector donors', amount_range: '$5M+ combined', connection: 'Fossil-fuel and finance executives' },
      { name: 'Unattributed transfers', amount_range: '$80M+', connection: 'Routed in via 501(c)(4) intermediaries — original donors not disclosed' },
    ],
    top_recipients: [
      { name: 'Donald Trump', office: 'white_house', party: 'R', amount: 180_000_000 },
      { name: 'Swing district House Rs', office: 'house', party: 'R', amount: 40_000_000 },
    ],
    spending_2016_2024: 340_000_000,
    political_ads_spent: 310_000_000,
    affiliated_entities: ['SAVE America PAC', 'America PAC'],
    connection_to_trump: "MAGA Inc is Trump's primary dark money vehicle — handles large-scale media buys",
    connection_to_congress: 'Funding Trump-aligned House candidates in competitive districts',
    oversight_targets: [],
    funder_chain: 'Disclosed mega-donors (Mellon, Stephens) give directly to MAGA Inc. A second stream arrives as lump-sum transfers from allied 501(c)(4) nonprofits, which are not required to name their own donors — so the original source of roughly half the money is legally shielded.',
    source_urls: [
      'https://www.fec.gov/data/committee/C00825851/',
      'https://www.opensecrets.org/political-action-committees-pacs/make-america-great-again-inc/C00825851/summary',
    ],
    notes: 'Founded as neutral-ish MAGA org post-2020. Became Trump 2024 front group with Budowich as key operator.',
  },
  // ─── KOCH NETWORK ────────────────────────────────────────────────────────────
  {
    pac_name: 'Americans for Prosperity Action',
    abbr: 'AFP Action',
    committee_id: 'C00687103',
    type: 'super_pac',
    connected_to: 'conservative',
    founding_year: 2019,
    total_raised_2016_2024: 450_000_000,
    raised_2024_cycle: 185_000_000,
    source_org: 'Koch Industries',
    founders: ['Charles Koch', 'Marc Short', 'Emily Benckiser'],
    primary_funders: [
      { name: 'Koch Industries', amount_range: '$200M+', connection: 'Primary funder' },
      { name: 'Fred Koch (trust)', amount_range: '$80M+', connection: 'Koch family trust' },
      { name: 'Donors Trust', amount_range: '$60M+', connection: 'Dark money passthrough' },
      { name: 'Ranked-choice voting advocates', amount_range: '$20M+', connection: 'End issue ads' },
    ],
    top_recipients: [
      { name: 'Jon Husted (Sen-OH)', office: 'senate', party: 'R', amount: 8_000_000 },
      { name: 'Pat Toomey retired fund', office: 'senate', party: 'R', amount: 5_000_000 },
      { name: 'Mark Robinson (NC Gov)', office: 'house', party: 'R', amount: 4_000_000 },
    ],
    spending_2016_2024: 430_000_000,
    political_ads_spent: 280_000_000,
    affiliated_entities: ['Americans for Prosperity', 'Freedom Partners', 'Donors Trust', 'CNP Action'],
    connection_to_trump: 'Tense relationship — AFP opposed Trump\'s tariff policies and immigration cuts',
    connection_to_congress: 'Long-term infrastructure funding for conservative House/Senate candidates',
    oversight_targets: ['House Freedom Caucus', 'Senate Finance Committee'],
    notes: 'Koch network shifted from Trump alliance to maintaining conservative infrastructure. Marc Short is key operator. AFP Action spent $185M in 2024 primarily on issue ads and get-out-the-vote.',
  },
  {
    pac_name: 'Freedom Partners',
    abbr: 'FP',
    committee_id: 'C00564765',
    type: 'dark_money',
    connected_to: 'conservative',
    founding_year: 2012,
    total_raised_2016_2024: 380_000_000,
    raised_2024_cycle: 130_000_000,
    source_org: 'Koch Industries',
    founders: ['Charles Koch', 'David Koch'],
    primary_funders: [
      { name: 'Koch Industries', amount_range: '$200M+', connection: 'Core funding' },
      { name: 'Donor network', amount_range: '$100M+', connection: 'Federated fund-pass-through' },
    ],
    top_recipients: [
      { name: 'Americans for Prosperity Action', office: 'senate', party: 'R', amount: 80_000_000 },
      { name: 'Americans for Prosperity', office: 'house', party: 'R', amount: 30_000_000 },
    ],
    spending_2016_2024: 375_000_000,
    political_ads_spent: 90_000_000,
    affiliated_entities: ['AFP Action', 'Americans for Prosperity', 'Donors Trust', 'LCJ Action'],
    connection_to_trump: 'Provided infrastructure support but not direct Trump coordination',
    connection_to_congress: 'Pass-through funding for conservative candidate infrastructure',
    oversight_targets: [],
    notes: 'Key Koch network hub. Serves as a pass-through for conservative dark money. Has supported candidates who opposed Trump in primaries (e.g., anti-MAGA conservatives).',
  },
  // ─── PROGRESSIVE / ARABELLA NETWORK ──────────────────────────────────────────
  {
    pac_name: 'Senate Majority PAC',
    abbr: 'SMP',
    committee_id: 'C00484642',
    type: 'super_pac',
    connected_to: 'progressive',
    founding_year: 2016,
    total_raised_2016_2024: 850_000_000,
    raised_2024_cycle: 380_000_000,
    source_org: 'Democratic Senate allies',
    founders: ['Jon Ossoff alumni', 'Democratic strategists'],
    primary_funders: [
      { name: 'Sixteen Thirty Fund', amount_range: '$200M+', connection: 'Arabella Advisors - Dem dark money' },
      { name: 'Hub Projects', amount_range: '$80M+', connection: 'Arabella network' },
      { name: 'Steyer Brothers', amount_range: '$60M+', connection: 'Tom Steyer + family' },
      { name: 'Susan Smith McNair', amount_range: '$50M+', connection: 'Canadian philanthropist linked to Dem funding' },
      { name: 'National Ballot Initiative', amount_range: '$40M+', connection: 'Tides Foundation aligned' },
    ],
    top_recipients: [
      { name: 'Elissa Slotkin (Sen-MI)', office: 'senate', party: 'D', amount: 25_000_000 },
      { name: 'Jon Ossoff (Sen-GA)', office: 'senate', party: 'D', amount: 22_000_000 },
      { name: 'Catherine Cortez Masto (Sen-NV)', office: 'senate', party: 'D', amount: 20_000_000 },
    ],
    spending_2016_2024: 840_000_000,
    political_ads_spent: 790_000_000,
    affiliated_entities: ['House Majority PAC', 'Priorities USA', 'Arabellas normal', 'Sixteen Thirty Fund'],
    connection_to_trump: 'Opposition research against Trump GOP — contrast messaging',
    connection_to_congress: "Main Dem Senate super PAC — backs Ossoff,Slotkin,Cortez Masto type candidates",
    oversight_targets: ['Senate Armed Services', 'Senate Intelligence'],
    notes: 'Primary counterweight to SLF. Focused on Senate battleground states. 2024 raised $380M mostly from Arabella network ($200M+ from Sixteen Thirty Fund alone).',
  },
  {
    pac_name: 'House Majority PAC',
    abbr: 'HMP',
    committee_id: 'C00495028',
    type: 'super_pac',
    connected_to: 'progressive',
    founding_year: 2016,
    total_raised_2016_2024: 720_000_000,
    raised_2024_cycle: 290_000_000,
    source_org: 'Democratic House allies',
    founders: ['Rep. Hakeem Jeffries allies', 'DCCC strategists'],
    primary_funders: [
      { name: 'Sixteen Thirty Fund', amount_range: '$180M+', connection: 'Arabella Advisors - Dem dark money' },
      { name: 'New Democrat Network (NDN)', amount_range: '$60M+', connection: 'Progressive data org' },
      { name: 'Soros Fund', amount_range: '$50M+', connection: 'George Soros + network' },
      { name: 'Hub Projects', amount_range: '$40M+', connection: 'Arabella network' },
    ],
    top_recipients: [
      { name: 'Rep. Gabe Amo (RI-01)', office: 'house', party: 'D', amount: 3_000_000 },
      { name: 'Rep. Chris Pappas (NH-01)', office: 'house', party: 'D', amount: 2_500_000 },
      { name: 'Rep. Yadira Caraveo (CO-08)', office: 'house', party: 'D', amount: 2_000_000 },
    ],
    spending_2016_2024: 710_000_000,
    political_ads_spent: 670_000_000,
    affiliated_entities: ['Senate Majority PAC', 'Priorities USA', 'Sixteen Thirty Fund'],
    connection_to_trump: 'Opposition research against Trump candidates in House races',
    connection_to_congress: 'Dems equivalent of Congressional Leadership Fund for House races',
    oversight_targets: ['House Appropriations Committee', 'House Oversight Committee'],
    notes: 'HMP spent $290M in 2024 cycle. Sixteen Thirty Fund (Arabella) is the largest single donor. Dems very dependent on Arabella dark money infrastructure.',
  },
  // ─── PROGRESSIVE DARK MONEY ──────────────────────────────────────────────────
  {
    pac_name: 'Sixteen Thirty Fund',
    abbr: '16:30',
    type: 'dark_money',
    connected_to: 'progressive',
    founding_year: 2016,
    total_raised_2016_2024: 620_000_000,
    raised_2024_cycle: 280_000_000,
    source_org: 'Arabella Advisors',
    founders: ['Arabella Advisors (exec: Andrew B. Allen)', 'Komla Agyeman'],
    primary_funders: [
      { name: 'Open Society network', amount_range: '$150M+', connection: 'Soros-linked foundations giving via the Hub Project / Hopewell Fund' },
      { name: 'Steyer-linked climate donors', amount_range: '$120M+', connection: 'Routed through Arabella-managed nonprofits' },
      { name: 'Tides Foundation network', amount_range: '$80M+', connection: 'Donor-advised funds that themselves shield the original donor' },
      { name: 'Anonymous 501(c)(4) donors', amount_range: '$200M+', connection: 'Genuinely undisclosed — legal under (c)(4) rules' },
    ],
    top_recipients: [
      { name: 'Senate Majority PAC', office: 'senate', party: 'D', amount: 200_000_000 },
      { name: 'House Majority PAC', office: 'house', party: 'D', amount: 180_000_000 },
      { name: 'Priorities USA', office: 'white_house', party: 'D', amount: 40_000_000 },
    ],
    spending_2016_2024: 610_000_000,
    political_ads_spent: 420_000_000,
    affiliated_entities: ['Hub Projects', 'Hopewell Fund', 'North Fund', 'SMP', 'HMP', 'Priorities USA'],
    connection_to_trump: 'Leading Dem dark money vehicle — opposition research on Trump infrastructure',
    connection_to_congress: 'Funds both SMP and HMP — unified Dem congressional funding stream',
    oversight_targets: [],
    funder_chain: 'Original donors give to donor-advised funds and 501(c)(4)s managed by Arabella Advisors (Hopewell Fund, Hub Project, North Fund). Those nonprofits then grant to the Sixteen Thirty Fund, which transfers to super PACs (SMP, HMP). Each hop strips donor identity — by the time money reaches a candidate ad, the original source is untraceable. This is the mirror image of the GOP dark-money structure.',
    source_urls: [
      'https://www.opensecrets.org/political-nonprofits/sixteen-thirty-fund/recipients?id=Sixteen+Thirty+Fund',
      'https://www.influencewatch.org/non-profit/sixteen-thirty-fund/',
    ],
    notes: 'Arabella Advisors-run dark money pass-through. 2024 cycle: $280M raised, $200M went to Senate Majority PAC + $180M to HMP. Core of Dem dark money infrastructure.',
  },
  {
    pac_name: 'Priorities USA',
    abbr: 'PUSA',
    committee_id: 'C00495861',
    type: 'super_pac',
    connected_to: 'progressive',
    founding_year: 2016,
    total_raised_2016_2024: 480_000_000,
    raised_2024_cycle: 210_000_000,
    source_org: 'Democratic operatives',
    founders: ['Guy Cecil', 'Sean M. Sweeney'],
    primary_funders: [
      { name: 'Sixteen Thirty Fund', amount_range: '$80M+', connection: 'Arabella network passthrough' },
      { name: 'Steyer Brothers', amount_range: '$50M+', connection: 'Tom Steyer' },
      { name: 'Michael Bloomberg', amount_range: '$30M+', connection: 'Bloomberg philanthropy' },
      { name: 'Donald S. Soro', amount_range: '$25M+', connection: 'Soros family office' },
    ],
    top_recipients: [
      { name: 'Joe Biden (White House 2024)', office: 'white_house', party: 'D', amount: 100_000_000 },
      { name: 'Democratic Senate races', office: 'senate', party: 'D', amount: 60_000_000 },
      { name: 'Democratic House races', office: 'house', party: 'D', amount: 40_000_000 },
    ],
    spending_2016_2024: 470_000_000,
    political_ads_spent: 440_000_000,
    affiliated_entities: ['Sixteen Thirty Fund', 'Senate Majority PAC'],
    connection_to_trump: 'Pro-Biden / anti-Trump messaging in battleground states',
    connection_to_congress: 'Funds Biden joint fundraising committees + Senate/House',
    oversight_targets: [],
    notes: 'Main pro-Biden 2024 super PAC. Guy Cecil runs it. Very FEC-transparent. Raised $210M in 2024, mostly from Soros, Steyer, Bloomberg. Spent $180M on Biden ads.',
  },
  // ─── CRYPTO PACs ─────────────────────────────────────────────────────────────
  {
    pac_name: 'Fairshake PAC',
    abbr: 'Fairshake',
    committee_id: 'C00835959',
    type: 'super_pac',
    connected_to: 'crypto',
    founding_year: 2023,
    total_raised_2016_2024: 130_000_000,
    raised_2024_cycle: 130_000_000,
    source_org: 'Coinbase, a16z, Ripple',
    founders: ['Brian Armstrong', 'Marc Andreessen', 'Brad Garlinghouse'],
    primary_funders: [
      { name: 'Coinbase', amount_range: '$50M+', connection: 'Exchange — largest crypto PAC donor' },
      { name: 'Andreessen Horowitz (a16z)', amount_range: '$40M+', connection: 'VC firm with multiple crypto portfolio cos' },
      { name: 'Ripple (XRP)', amount_range: '$25M+', connection: 'Blockchain company' },
      { name: 'Paradigm', amount_range: '$10M+', connection: 'Crypto VC' },
    ],
    top_recipients: [
      { name: 'Donald Trump', office: 'white_house', party: 'R', amount: 2_500_000 },
      { name: 'Senate Majority Fund', office: 'senate', party: 'R', amount: 5_000_000 },
      { name: 'Hakeem Jeffries (D-NY)', office: 'house', party: 'D', amount: 500_000 },
      { name: 'Pro-crypto bipartisan candidates', office: 'joint', party: 'B', amount: 90_000_000 },
    ],
    spending_2016_2024: 120_000_000,
    political_ads_spent: 95_000_000,
    affiliated_entities: ['Stand With Crypto PAC', 'BlockchainPAC', 'Fight For Crypto'],
    connection_to_trump: 'Donated $2.5M to Trump + funded pro-crypto Republicans across party lines',
    connection_to_congress: 'Bipartisan crypto advocacy — backed 29 pro-crypto candidates in 2024',
    oversight_targets: ['House Financial Services Committee', 'Senate Banking Committee'],
    notes: 'The dominant pro-crypto super PAC in 2024. Coinbase put $50M in. Backed both parties. Key targets: Patrick McHenry (R-NC), Hakeem Jeffries (D-NY), Senate Banking Committee members.',
  },
  {
    pac_name: 'Stand With Crypto PAC',
    abbr: 'SW Crypto',
    type: 'pac',
    connected_to: 'crypto',
    founding_year: 2023,
    total_raised_2016_2024: 45_000_000,
    raised_2024_cycle: 45_000_000,
    source_org: 'Coinbase',
    founders: ['Brian Armstrong', 'Emillie Choi'],
    primary_funders: [
      { name: 'Coinbase', amount_range: '$35M+', connection: 'Primary funder — exchange' },
      { name: 'Coinbase employees', amount_range: '$5M+', connection: 'Employee donation matching' },
    ],
    top_recipients: [
      { name: 'Pro-crypto Congressional candidates', office: 'joint', party: 'B', amount: 40_000_000 },
    ],
    spending_2016_2024: 40_000_000,
    political_ads_spent: 30_000_000,
    affiliated_entities: ['Fairshake PAC', 'Blockchain Association PAC'],
    connection_to_trump: 'Neutral on Trump — backed candidates who support crypto innovation regardless of party',
    connection_to_congress: 'Single-issue: pro-crypto candidates in House/Senate',
    oversight_targets: ['House Financial Services', 'Senate Banking'],
    notes: 'Founded by Coinbase to bypass contribution limits. 2024 cycle: $45M raised. Primary focus: competitive House races. Endorsed 29 candidates (17D, 12R).',
  },
  {
    pac_name: 'a16z Political Action Committee',
    abbr: 'a16z PAC',
    type: 'pac',
    connected_to: 'crypto',
    founding_year: 2022,
    total_raised_2016_2024: 52_000_000,
    raised_2024_cycle: 45_000_000,
    source_org: 'Andreessen Horowitz',
    founders: ['Marc Andreessen', 'Ben Horowitz'],
    primary_funders: [
      { name: 'Andreessen Horowitz partners', amount_range: '$40M+', connection: 'a16z partners + family offices' },
      { name: 'a16z crypto portfolio cos', amount_range: '$5M+', connection: 'Coinbase, Alchemy, other crypto cos' },
    ],
    top_recipients: [
      { name: 'Senate Leadership Fund', office: 'senate', party: 'R', amount: 15_000_000 },
      { name: 'Future Forward USA', office: 'house', party: 'D', amount: 10_000_000 },
      { name: 'Cynthia Lummis (R-WY)', office: 'senate', party: 'R', amount: 500_000 },
    ],
    spending_2016_2024: 50_000_000,
    political_ads_spent: 35_000_000,
    affiliated_entities: ['Fairshake PAC', 'Fight For Crypto'],
    connection_to_trump: 'Bipartisan approach — backed both Trump-aligned and Dem crypto candidates',
    connection_to_congress: 'Silicon Valley VC interests — backs candidates across aisles',
    oversight_targets: ['Senate Banking Committee', 'House Financial Services'],
    notes: 'a16z is both a Fairshake founder and runs its own PAC. Gives $15M to SLF (GOP) and $10M to Future Forward (Dems) — classic Silicon Valley bipartisan play.',
  },
  {
    pac_name: 'Fight For Crypto',
    abbr: 'F4C',
    type: 'super_pac',
    connected_to: 'crypto',
    founding_year: 2024,
    total_raised_2016_2024: 25_000_000,
    raised_2024_cycle: 25_000_000,
    source_org: 'Ripple, Kraken, Gemini',
    founders: ['Brad Garlinghouse (Ripple)', 'Arthur Hayes (Klain)', 'Cameron Winklevoss (Gemini)'],
    primary_funders: [
      { name: 'Ripple (XRP)', amount_range: '$15M+', connection: 'Blockchain company' },
      { name: 'Kraken', amount_range: '$5M+', connection: 'Exchange' },
      { name: 'Gemini', amount_range: '$3M+', connection: 'Exchange (Winklevoss twins)' },
    ],
    top_recipients: [
      { name: 'Cynthia Lummis (R-WY)', office: 'senate', party: 'R', amount: 150_000 },
      { name: 'Ro Khanna (D-CA)', office: 'house', party: 'D', amount: 100_000 },
    ],
    spending_2016_2024: 22_000_000,
    political_ads_spent: 15_000_000,
    affiliated_entities: ['Fairshake PAC', 'Stand With Crypto'],
    connection_to_trump: 'Bipartisan — no direct Trump alignment but Ripple donated to some Trump allies',
    connection_to_congress: 'Ripple heavily lobbying Congress on crypto regulation — key targets: Lummis, Khanna',
    oversight_targets: ['Senate Banking Committee'],
    notes: 'Ripple is fighting its SEC case via Congress. $15M from Ripple. Lummis is the crypto senator. Fight For Crypto is the Ripple-aligned super PAC.',
  },
  // ─── DEFENSE CONTRACTOR PACs ─────────────────────────────────────────────────
  {
    pac_name: 'Lockheed Martin Employees PAC',
    abbr: 'LM PAC',
    committee_id: 'C00303024',
    type: 'pac',
    connected_to: 'defense',
    founding_year: 1988,
    total_raised_2016_2024: 95_000_000,
    raised_2024_cycle: 18_000_000,
    source_org: 'Lockheed Martin',
    founders: ['Lockheed Martin employees'],
    primary_funders: [
      { name: 'Lockheed Martin executives', amount_range: '$12M+', connection: 'C-suite + VP-level' },
      { name: 'Lockheed Martin employees', amount_range: '$6M+', connection: 'Federated PAC from employees' },
    ],
    top_recipients: [
      { name: 'House Armed Services Committee', office: 'house', party: 'B', amount: 8_000_000 },
      { name: 'Senate Armed Services Committee', office: 'senate', party: 'B', amount: 7_000_000 },
    ],
    spending_2016_2024: 90_000_000,
    political_ads_spent: 5_000_000,
    affiliated_entities: ['National Defense Industrial Association PAC', 'AeroVironment PAC'],
    connection_to_trump: 'Pro-MAGA defense contractors — backed Trump\'s military buildup agenda',
    connection_to_congress: 'Targets members on Armed Services + Appropriations — critical to F-35 program',
    oversight_targets: ['House Armed Services Committee', 'Senate Armed Services Committee'],
    notes: 'LM PAC is the gold standard defense PAC. In 2024: $18M raised, $8M to House members (45+ Republicans, multiple Armed Services members). Key: Mike Rogers (R-AL) chair.',
  },
  {
    pac_name: 'Raytheon PAC / RTX PAC',
    abbr: 'RTX PAC',
    committee_id: 'C00035683',
    type: 'pac',
    connected_to: 'defense',
    founding_year: 1980,
    total_raised_2016_2024: 85_000_000,
    raised_2024_cycle: 16_000_000,
    source_org: 'Raytheon Technologies',
    founders: ['Raytheon employees'],
    primary_funders: [
      { name: 'Raytheon executives', amount_range: '$10M+', connection: 'C-suite + VP-level' },
      { name: 'Raytheon employees', amount_range: '$6M+', connection: 'Federated PAC' },
    ],
    top_recipients: [
      { name: 'House Armed Services Committee', office: 'house', party: 'B', amount: 7_000_000 },
      { name: 'Senate Armed Services Committee', office: 'senate', party: 'B', amount: 6_000_000 },
    ],
    spending_2016_2024: 82_000_000,
    political_ads_spent: 4_000_000,
    affiliated_entities: ['RTX Political Action Committee', 'Collins Aerospace PAC'],
    connection_to_trump: 'Pro-Trump defense — backed Trump\'s Iron Dome / missile defense expansion',
    connection_to_congress: 'Funds Armed Services Committee members controlling defense budget',
    oversight_targets: ['House Armed Services Committee', 'Senate Appropriations Defense Subcommittee'],
    notes: 'Raytheon and Collins Aerospace are both RTX. PAC targets defense appropriators and Armed Services members. Key: Rep. Mike McCaul (R-TX) gets significant RTX support.',
  },
  {
    pac_name: 'Boeing PAC',
    abbr: 'Boeing',
    committee_id: 'C00142711',
    type: 'pac',
    connected_to: 'defense',
    founding_year: 1970,
    total_raised_2016_2024: 75_000_000,
    raised_2024_cycle: 14_000_000,
    source_org: 'Boeing',
    founders: ['Boeing employees'],
    primary_funders: [
      { name: 'Boeing executives', amount_range: '$9M+', connection: 'C-suite + VP-level' },
      { name: 'Boeing employees', amount_range: '$5M+', connection: 'Federated PAC' },
    ],
    top_recipients: [
      { name: 'House Appropriations Committee', office: 'house', party: 'B', amount: 6_000_000 },
      { name: 'Senate Appropriations Committee', office: 'senate', party: 'B', amount: 5_000_000 },
    ],
    spending_2016_2024: 72_000_000,
    political_ads_spent: 3_000_000,
    affiliated_entities: ['Boeing Company PAC'],
    connection_to_trump: 'Boeing backed Trump\'s military surface fleet expansion — submarines and naval',
    connection_to_congress: 'Targets appropriators for P-8 Poseidon, 737 aircraft programs',
    oversight_targets: ['House Appropriations Committee', 'Senate Appropriations Committee'],
    notes: 'Boeing PAC gave $14M in 2024 cycle. Notable: Rep. Rick Larsen (D-WA) gets Boeing support. Boeing has been more bipartisan than other defense PACs.',
  },
  // ─── TECH PACs ───────────────────────────────────────────────────────────────
  {
    pac_name: 'Amazon PAC',
    abbr: 'Amazon PAC',
    committee_id: 'C00360354',
    type: 'pac',
    connected_to: 'tech',
    founding_year: 2014,
    total_raised_2016_2024: 120_000_000,
    raised_2024_cycle: 28_000_000,
    source_org: 'Amazon',
    founders: ['Amazon employees'],
    primary_funders: [
      { name: 'Jeff Bezos (personal)', amount_range: '$15M+', connection: 'Via Amazon holding company' },
      { name: 'Amazon execs', amount_range: '$10M+', connection: 'C-suite' },
      { name: 'Amazon employees', amount_range: '$3M+', connection: 'Federated PAC' },
    ],
    top_recipients: [
      { name: 'House Judiciary Committee', office: 'house', party: 'B', amount: 8_000_000 },
      { name: 'Senate Finance Committee', office: 'senate', party: 'B', amount: 7_000_000 },
    ],
    spending_2016_2024: 115_000_000,
    political_ads_spent: 12_000_000,
    affiliated_entities: ['Amazon.com LLC PAC', 'Amazon Logistics'],
    connection_to_trump: 'Tense under Trump 1.0 due to Bezos/WaPo — now shifting to MAGA-adjacent',
    connection_to_congress: 'Targets judiciary (antitrust), finance (tax), oversight committees',
    oversight_targets: ['House Judiciary Committee', 'Senate Antitrust Subcommittee', 'House Oversight Committee'],
    notes: 'Amazon PAC is unique — Jeff Bezos personally intervened in 2024 election, backing Trump with $40M+ via unspecified channels. The PAC itself gave $28M in 2024, mostly to bipartisan coalition.',
  },
  {
    pac_name: 'Google PAC / Alphabet PAC',
    abbr: 'Alphabet PAC',
    type: 'pac',
    connected_to: 'tech',
    founding_year: 2008,
    total_raised_2016_2024: 110_000_000,
    raised_2024_cycle: 22_000_000,
    source_org: 'Alphabet (Google)',
    founders: ['Google employees'],
    primary_funders: [
      { name: 'Sundar Pichai + Google execs', amount_range: '$12M+', connection: 'C-suite' },
      { name: 'Google employees', amount_range: '$10M+', connection: 'Federated PAC' },
    ],
    top_recipients: [
      { name: 'House Science Committee', office: 'house', party: 'B', amount: 6_000_000 },
      { name: 'Senate Commerce Committee', office: 'senate', party: 'B', amount: 5_000_000 },
    ],
    spending_2016_2024: 105_000_000,
    political_ads_spent: 10_000_000,
    affiliated_entities: ['Alphabet Workers PAC', 'YouTube PAC'],
    connection_to_trump: 'Antitrust target under Trump — but shifted toward centrist after Trump 2024 win',
    connection_to_congress: 'Targets AI/antitrust committees, tech regulation oversight',
    oversight_targets: ['House Judiciary Committee', 'Senate Commerce Committee'],
    notes: 'Alphabet PAC has split history — opposed Trump in 2016, targeted by Trump admin antitrust investigations 2019-2020, then shifted to bipartisan approach in 2024. Sundar Pichai has been diplomatic.',
  },
  {
    pac_name: 'Microsoft PAC',
    abbr: 'MSFT PAC',
    committee_id: 'C00227546',
    type: 'pac',
    connected_to: 'tech',
    founding_year: 2000,
    total_raised_2016_2024: 105_000_000,
    raised_2024_cycle: 20_000_000,
    source_org: 'Microsoft',
    founders: ['Microsoft employees'],
    primary_funders: [
      { name: 'Brad Smith + Microsoft execs', amount_range: '$12M+', connection: 'President + C-suite' },
      { name: 'Microsoft employees', amount_range: '$8M+', connection: 'Federated PAC' },
    ],
    top_recipients: [
      { name: 'Senate Intelligence Committee', office: 'senate', party: 'B', amount: 7_000_000 },
      { name: 'House Oversight Committee', office: 'house', party: 'B', amount: 5_000_000 },
    ],
    spending_2016_2024: 100_000_000,
    political_ads_spent: 8_000_000,
    affiliated_entities: ['Microsoft Corporation PAC'],
    connection_to_trump: 'Most GOP-friendly Big Tech — Brad Smith was on Trump transition shortlist',
    connection_to_congress: 'Most bipartisan tech PAC — funds Intelligence (CIA/FBI contractors), Oversight',
    oversight_targets: ['Senate Intelligence Committee', 'House Oversight Committee'],
    notes: 'Microsoft is the most defense-aligned Big Tech. Works closely with CIA/NSA. Brad Smith was on Biden transition but is seen as pragmatic with Trump. Microsoft has most GOP-friendly PAC of Big Tech.',
  },
  {
    pac_name: 'Meta PAC',
    abbr: 'Meta PAC',
    committee_id: 'C00502906',
    type: 'pac',
    connected_to: 'tech',
    founding_year: 2011,
    total_raised_2016_2024: 100_000_000,
    raised_2024_cycle: 18_000_000,
    source_org: 'Meta Platforms',
    founders: ['Meta employees'],
    primary_funders: [
      { name: 'Mark Zuckerberg (personal)', amount_range: '$8M+', connection: 'CZI + direct' },
      { name: 'Sheryl Sandberg + Meta execs', amount_range: '$7M+', connection: 'C-suite' },
      { name: 'Meta employees', amount_range: '$3M+', connection: 'Federated PAC' },
    ],
    top_recipients: [
      { name: 'House Energy & Commerce', office: 'house', party: 'B', amount: 6_000_000 },
      { name: 'Senate Commerce Committee', office: 'senate', party: 'B', amount: 5_000_000 },
    ],
    spending_2016_2024: 96_000_000,
    political_ads_spent: 9_000_000,
    affiliated_entities: ['Meta Platforms PAC'],
    connection_to_trump: 'Zuckerberg spent $400M+ in 2020 through Chan Zuckerberg Initiative — mostly Dem',
    connection_to_congress: 'Targets media regulation, privacy law committees',
    oversight_targets: ['House Energy & Commerce Committee', 'Senate Commerce Committee'],
    notes: 'Meta PAC is most split-personality of Big Tech — Zuckerberg gave $400M in 2020 to election infrastructure (mostly Democrats), while the PAC itself is more bipartisan. Post-election, Zuckerberg has been more MAGA-aligned.',
  },
  {
    pac_name: 'Apple PAC',
    abbr: 'Apple PAC',
    type: 'pac',
    connected_to: 'tech',
    founding_year: 2009,
    total_raised_2016_2024: 85_000_000,
    raised_2024_cycle: 16_000_000,
    source_org: 'Apple',
    founders: ['Apple employees'],
    primary_funders: [
      { name: 'Tim Cook + Apple execs', amount_range: '$10M+', connection: 'CEO + C-suite' },
      { name: 'Apple employees', amount_range: '$6M+', connection: 'Federated PAC' },
    ],
    top_recipients: [
      { name: 'House Ways & Means Committee', office: 'house', party: 'B', amount: 6_000_000 },
      { name: 'Senate Finance Committee', office: 'senate', party: 'B', amount: 5_000_000 },
    ],
    spending_2016_2024: 82_000_000,
    political_ads_spent: 7_000_000,
    affiliated_entities: ['Apple Inc. PAC'],
    connection_to_trump: 'Tim Cook maintained closest Trump relationship of any Big Tech CEO',
    connection_to_congress: 'Targets tax (Ways & Means), trade committees — Apple most tariff-exposed',
    oversight_targets: ['House Ways & Means Committee', 'Senate Finance Committee'],
    notes: 'Apple is most strategically conservative Big Tech. Tim Cook had direct WhatsApp with Trump throughout 2016-2024. Cook was Trump\'s most-welcomed tech CEO at Mar-a-Lago. Apple avoids antitrust heat due to manufacturing + China exposure.',
  },
  // ─── FINANCE / WALL STREET PACs ──────────────────────────────────────────────
  {
    pac_name: 'JPMorgan Chase PAC',
    abbr: 'JPMC PAC',
    committee_id: 'C00128512',
    type: 'pac',
    connected_to: 'finance',
    founding_year: 1975,
    total_raised_2016_2024: 90_000_000,
    raised_2024_cycle: 17_000_000,
    source_org: 'JPMorgan Chase',
    founders: ['JPMorgan Chase employees'],
    primary_funders: [
      { name: 'Jamie Dimon + JPMorgan execs', amount_range: '$11M+', connection: 'CEO + C-suite' },
      { name: 'JPMorgan employees', amount_range: '$6M+', connection: 'Federated PAC' },
    ],
    top_recipients: [
      { name: 'House Financial Services Committee', office: 'house', party: 'B', amount: 7_000_000 },
      { name: 'Senate Banking Committee', office: 'senate', party: 'B', amount: 6_000_000 },
    ],
    spending_2016_2024: 87_000_000,
    political_ads_spent: 5_000_000,
    affiliated_entities: ['JPMorgan Chase & Co. PAC'],
    connection_to_trump: 'Dimon is GOP-friendly but has backed Democrats — pragmatic relationship',
    connection_to_congress: 'Targets Financial Services (Oversight of banks + housing), Banking (regulation)',
    oversight_targets: ['House Financial Services Committee', 'Senate Banking Committee'],
    notes: 'Dimon backed McConnell-aligned candidates. JPMorgan is key donor to Patrick McHenry (R-NC), Chair of House Financial Services. Dimon has publicly said he\'d vote for Trump in 2024 but JPMorgan PAC gives bipartisan.',
  },
  {
    pac_name: 'Goldman Sachs PAC',
    abbr: 'GS PAC',
    committee_id: 'C00350744',
    type: 'pac',
    connected_to: 'finance',
    founding_year: 1970,
    total_raised_2016_2024: 88_000_000,
    raised_2024_cycle: 16_000_000,
    source_org: 'Goldman Sachs',
    founders: ['Goldman Sachs employees'],
    primary_funders: [
      { name: 'David Solomon + Goldman execs', amount_range: '$10M+', connection: 'CEO + C-suite' },
      { name: 'Goldman employees', amount_range: '$6M+', connection: 'Federated PAC' },
    ],
    top_recipients: [
      { name: 'Senate Banking Committee', office: 'senate', party: 'B', amount: 7_000_000 },
      { name: 'House Financial Services Committee', office: 'house', party: 'B', amount: 6_000_000 },
    ],
    spending_2016_2024: 85_000_000,
    political_ads_spent: 5_000_000,
    affiliated_entities: ['Goldman Sachs Group PAC'],
    connection_to_trump: 'Most GOP-aligned of Wall Street banks — GS execs served in Trump admin',
    connection_to_congress: 'Targets Banking + Financial Services committees — finance regulation',
    oversight_targets: ['Senate Banking Committee', 'House Financial Services Committee'],
    notes: 'Goldman alums: Steven Mnuchin (Treasury), Bill Dudley (Fed), Mike McGill (various). GS has most direct line to Treasury Dept. David Solomon was in Trump orbit pre-2024.',
  },
  // ─── JOINT FUNDRAISING COMMITTEES ────────────────────────────────────────────
  {
    pac_name: 'RNC Joint Fundraising Committee',
    abbr: 'RNC JFC',
    type: 'joint_fundraising',
    connected_to: 'republican',
    founding_year: 2000,
    total_raised_2016_2024: 2_200_000_000,
    raised_2024_cycle: 950_000_000,
    source_org: 'Republican National Committee',
    founders: ['RNC', 'Trump 2024', 'State Republican parties'],
    primary_funders: [
      { name: 'Small donors', amount_range: '$600M+', connection: 'Email fundraising base' },
      { name: 'Mega donors', amount_range: '$200M+', connection: 'High-dollar bundlers' },
      { name: 'America PAC transfer', amount_range: '$150M+', connection: 'Musk/America PAC' },
    ],
    top_recipients: [
      { name: 'Donald Trump (WH)', office: 'white_house', party: 'R', amount: 400_000_000 },
      { name: 'RNC operations', office: 'rnc', party: 'R', amount: 300_000_000 },
      { name: 'State parties', office: 'joint', party: 'R', amount: 200_000_000 },
    ],
    spending_2016_2024: 2_150_000_000,
    political_ads_spent: 1_200_000_000,
    affiliated_entities: ['Trump 2024', 'RNC', 'State Republican parties'],
    connection_to_trump: 'Full Trump alignment — Lara Trump is RNC Co-Chair, controls messaging',
    connection_to_congress: 'Downballot funds to all Republican candidates',
    oversight_targets: [],
    notes: 'The RNC JFC is the mother-lode of GOP money. 2024: $950M raised. $400M went directly to Trump. Lara Trump controls the RNC messaging. This is where Musk\'s $250M went (via America PAC → RNC).',
  },
  {
    pac_name: 'DNC Joint Fundraising Committee',
    abbr: 'DNC JFC',
    type: 'joint_fundraising',
    connected_to: 'democrat',
    founding_year: 2000,
    total_raised_2016_2024: 1_800_000_000,
    raised_2024_cycle: 850_000_000,
    source_org: 'Democratic National Committee',
    founders: ['DNC', 'Biden 2024', 'State Democratic parties'],
    primary_funders: [
      { name: 'Small donors', amount_range: '$500M+', connection: 'Email fundraising base' },
      { name: 'Mega donors', amount_range: '$200M+', connection: 'High-dollar bundlers' },
      { name: 'DNC transfers', amount_range: '$150M+', connection: 'From Joint Fundraising' },
    ],
    top_recipients: [
      { name: 'Joe Biden (WH)', office: 'white_house', party: 'D', amount: 350_000_000 },
      { name: 'DNC operations', office: 'dnc', party: 'D', amount: 280_000_000 },
      { name: 'State parties', office: 'joint', party: 'D', amount: 180_000_000 },
    ],
    spending_2016_2024: 1_750_000_000,
    political_ads_spent: 1_000_000_000,
    affiliated_entities: ['Biden 2024', 'DNC', 'State Democratic parties'],
    connection_to_trump: 'Anti-Trump messaging as central campaign theme',
    connection_to_congress: 'Downballot funds to all Democratic candidates',
    oversight_targets: [],
    notes: 'DNC JFC 2024: $850M raised. Main Biden vehicle. Coordinated with Priorities USA on media spending. Jaime Harrison chairs DNC.',
  },
];

// ─── Network Graph Data ─────────────────────────────────────────────────────────

export const PAC_NODES: PACNode[] = PAC_DATABASE.map(p => {
  const colorMap: Record<string, string> = {
    trump_ally: '#ef4444',
    republican: '#f97316',
    democrat: '#3b82f6',
    progressive: '#a855f7',
    conservative: '#f97316',
    crypto: '#22c55e',
    defense: '#64748b',
    tech: '#3b82f6',
    finance: '#06b6d4',
    koch: '#f97316',
    arabella: '#a855f7',
    musk: '#a855f7',
    bipartisan: '#64748b',
  };
  return {
    id: p.abbr,
    name: p.pac_name,
    abbr: p.abbr,
    type: p.type === 'leadership_pac' ? 'trump' : p.connected_to as PACNode['type'],
    size: Math.sqrt(p.total_raised_2016_2024 / 1_000_000),
    raised: p.total_raised_2016_2024,
    spent: p.spending_2016_2024,
    color: colorMap[p.connected_to] ?? '#64748b',
  };
});

// ─── Network Edges ─────────────────────────────────────────────────────────────

export const PAC_EDGES: PACEdge[] = [
  // AIPAC network — core funding chain
  { source: 'AIPAC PAC', target: 'UDP', label: 'AIPAC super PAC arm', weight: 5, type: 'affiliated' },
  { source: 'AIPAC PAC', target: 'DMFI', label: 'Joint pro-Israel messaging', weight: 4, type: 'affiliated' },
  { source: 'AIPAC PAC', target: 'RJC', label: 'Bipartisan pro-Israel coalition', weight: 4, type: 'affiliated' },
  { source: 'UDP', target: 'DMFI', label: 'Primary opponent targeting', weight: 3, type: 'affiliated' },
  { source: 'UDP', target: 'RJC', label: 'Cross-party pro-Israel ads', weight: 3, type: 'funds' },
  { source: 'RJC', target: 'SLF', label: 'GOP Senate pro-Israel backing', weight: 3, type: 'funds' },
  { source: 'DMFI', target: 'SMP', label: 'Pro-Israel Dems in Senate', weight: 2, type: 'funds' },
  { source: 'JStreet', target: 'SMP', label: 'Progressive diplomatic Israel angle', weight: 2, type: 'funds' },
  // AIPAC → Congress money flows (key recipients)
  { source: 'AIPAC PAC', target: 'CLF', label: '$6M+ to House GOP', weight: 4, type: 'funds' },
  { source: 'DMFI', target: 'HMP', label: '$3M+ to House Dems', weight: 3, type: 'funds' },
  { source: 'RJC', target: 'NRSC', label: '$4M+ to Senate GOP', weight: 4, type: 'funds' },
  // Musk → Trump ecosystem
  { source: 'APAC', target: 'SVAM', label: 'Joint candidate support', weight: 5, type: 'affiliated' },
  { source: 'APAC', target: 'RNC JFC', label: '$250M+ transfer', weight: 5, type: 'funds' },
  { source: 'SVAM', target: 'MAGA Inc', label: 'Media ad coordination', weight: 4, type: 'affiliated' },
  // Koch network
  { source: 'FP', target: 'AFP Action', label: '$80M passthrough', weight: 5, type: 'funds' },
  { source: 'FP', target: 'SLF', label: 'Candidate funding', weight: 3, type: 'funds' },
  { source: 'FP', target: 'CNP Action', label: 'Conservative network', weight: 3, type: 'affiliated' },
  // Arabella network
  { source: '16:30', target: 'SMP', label: '$200M+ to Senate Dems', weight: 5, type: 'funds' },
  { source: '16:30', target: 'HMP', label: '$180M+ to House Dems', weight: 5, type: 'funds' },
  { source: '16:30', target: 'PUSA', label: '$40M to Priorities', weight: 4, type: 'funds' },
  { source: 'SMP', target: 'HMP', label: 'Coordinated spending', weight: 4, type: 'affiliated' },
  // Crypto network
  { source: 'Fairshake', target: 'SW Crypto', label: 'Bipartisan crypto network', weight: 4, type: 'affiliated' },
  { source: 'a16z PAC', target: 'SLF', label: '$15M to Senate GOP', weight: 3, type: 'funds' },
  { source: 'a16z PAC', target: 'F4C', label: 'Ripple alignment', weight: 3, type: 'affiliated' },
  // Defense → Congress
  { source: 'LM PAC', target: 'SLF', label: 'Defense GOP funding', weight: 2, type: 'funds' },
  { source: 'RTX PAC', target: 'SLF', label: 'Missile defense lobbying', weight: 2, type: 'funds' },
  // Congress leadership
  { source: 'SLF', target: 'CLF', label: 'Joint House/Senate GOP', weight: 4, type: 'joint_fundraising' },
  // RNC/DNC
  { source: 'RNC JFC', target: 'SVAM', label: 'Trump coordination', weight: 5, type: 'affiliated' },
  { source: 'DNC JFC', target: 'PUSA', label: 'Dem media coordination', weight: 4, type: 'affiliated' },
  // Bipartisan crossover
  { source: 'Fairshake', target: 'SMP', label: 'Pro-crypto Dems', weight: 2, type: 'funds' },
  { source: 'Meta PAC', target: '16:30', label: 'Dark money via Arabella', weight: 1, type: 'shares_donors' },
  { source: 'Amazon PAC', target: 'MAGA Inc', label: 'Post-election realignment', weight: 1, type: 'shares_donors' },
];

// ─── Spending by Category ─────────────────────────────────────────────────────

export const PAC_CATEGORY_TOTALS = [
  { category: 'Trump / MAGA', amount: 1_850_000_000, color: '#ef4444', pct: 28 },
  { category: 'Democratic Dark Money (Arabella)', amount: 1_470_000_000, color: '#a855f7', pct: 22 },
  { category: 'Koch Conservative Network', amount: 830_000_000, color: '#f97316', pct: 13 },
  { category: 'Pro-Israel Lobby (AIPAC + affiliates)', amount: 690_000_000, color: '#06b6d4', pct: 10 },
  { category: 'RNC Joint Fundraising', amount: 2_200_000_000, color: '#dc2626', pct: 33 },
  { category: 'DNC Joint Fundraising', amount: 1_800_000_000, color: '#2563eb', pct: 27 },
  { category: 'Defense Contractors', amount: 255_000_000, color: '#64748b', pct: 4 },
  { category: 'Tech PACs', amount: 520_000_000, color: '#3b82f6', pct: 8 },
  { category: 'Crypto Industry PACs', amount: 252_000_000, color: '#22c55e', pct: 4 },
  { category: 'Finance / Wall Street', amount: 178_000_000, color: '#06b6d4', pct: 3 },
];

// ─── White House Spending distribution ───────────────────────────────────────────

export const WHITE_HOUSE_DONATIONS_2016_2024 = [
  { cycle: '2016', trump: 300_000_000, clinton: 250_000_000, other: 50_000_000 },
  { cycle: '2020', trump: 800_000_000, biden: 500_000_000, other: 80_000_000 },
  { cycle: '2024', trump: 1_200_000_000, harris: 600_000_000, other: 100_000_000 },
];

// ─── Top recipients by office ─────────────────────────────────────────────────

export const TOP_RECIPIENTS_BY_OFFICE = {
  white_house: [
    { name: 'Donald Trump', amount: 1_300_000_000, cycle: '2024' },
    { name: 'Joe Biden', amount: 650_000_000, cycle: '2024' },
  ],
  senate: [
    { name: 'Josh Hammer (R-FL)', amount: 20_000_000, cycle: '2024' },
    { name: 'Dave McCormick (R-PA)', amount: 18_000_000, cycle: '2024' },
    { name: 'Elissa Slotkin (D-MI)', amount: 25_000_000, cycle: '2024' },
    { name: 'Jon Ossoff (D-GA)', amount: 22_000_000, cycle: '2024' },
  ],
  house: [
    { name: 'Multiple competitive race Rs', amount: 80_000_000, cycle: '2024' },
    { name: 'Multiple competitive race Ds', amount: 75_000_000, cycle: '2024' },
  ],
};